------------------------------------------------------------------------------
-- TASK				: 	OWC RECEPTION TABLES CREATION 
--
-- AUTHOR         		: 	Surinder Badhan
--
-- FILENAME       		: 	02_DDL_CREATE_OWC_TABLES.sql
--
-- CREATED        		: 	09/09/2016
--	
-- Subversion $Revision: 5702 $
--
-- DESCRIPTION 		   	: 	Creates all database tables for OWC file reception area
--                        as received from OWC
--
---------------------------- Modification History ----------------------------------------------------------
--
-- Version     		Date        	 	Author         	Description
-- --------------------------------------------------------------------------------------------------------
-- V0.01	       	09/09/2016   	 	S.Badhan      	Initial version
-- V0.02          20/09/2016      D.Cheung        Increase length of OWC field
-- V0.03          28/09/2016      K.Burton        Added Water files tables
--------------------------------------------------------------------------------------------------------


--------------------------------------------------------------------------------------------------------
-- OWC_DISCHARGE_POINT
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_DISCHARGE_POINT
  (
    SPID_PK                        VARCHAR2(13 BYTE) NOT NULL ENABLE,
    DPID_PK                        VARCHAR2(32 BYTE) NOT NULL ENABLE,
    TARRIFCODE                     VARCHAR2(32 BYTE) NOT NULL ENABLE,
    TARRIFBAND                     NUMBER(2,0),
    TREFODCHEMOXYGENDEMAND         NUMBER(6,0),
    TREFODCHEMSUSPSOLDEMAND        NUMBER(6,0),
    TREFODCHEMAMONIANITROGENDEMAND NUMBER(6,0),
    TREFODCHEMCOMPXDEMAND          NUMBER(6,0),
    TREFODCHEMCOMPYDEMAND          NUMBER(6,0),
    TREFODCHEMCOMPZDEMAND          NUMBER(6,0),
    SEWERAGEVOLUMEADJMENTHOD       VARCHAR2(8 BYTE) NOT NULL ENABLE,
    RECEPTIONTREATMENTINDICATOR    NUMBER(1,0) NOT NULL ENABLE,
    PRIMARYTREATMENTINDICATOR      NUMBER(1,0) NOT NULL ENABLE,
    MARINETREATMENTINDICATOR       NUMBER(1,0) NOT NULL ENABLE,
    BIOLOGICALTREATMENTINDICATOR   NUMBER(1,0) NOT NULL ENABLE,
    SLUDGETREATMENTINDICATOR       NUMBER(1,0) NOT NULL ENABLE,
    AMMONIATREATMENTINDICATOR      NUMBER(1,0) NOT NULL ENABLE,
    TEFXTREATMENTINDICATOR         NUMBER(1,0) NOT NULL ENABLE,
    TEFYTREATMENTINDICATOR         NUMBER(1,0) NOT NULL ENABLE,
    TEFZTREATMENTINDICATOR         NUMBER(1,0) NOT NULL ENABLE,
    TEFAVAILABILITYDATAX           NUMBER(9,0),
    TEFAVAILABILITYDATAY           NUMBER(9,0),
    TEFAVAILABILITYDATAZ           NUMBER(9,0),
    CHARGEABLEDAILYVOL             NUMBER(12,0),
    CHEMICALOXYGENDEMAND           NUMBER(12,0),
    SUSPENDEDSOLIDSLOAD            NUMBER(12,0),
    AMMONIANITROCAL                NUMBER(12,0),
    FIXEDALLOWANCE                 NUMBER(12,0) NOT NULL ENABLE,
    PERCENTAGEALLOWANCE            NUMBER(3,0) NOT NULL ENABLE,
    DOMMESTICALLOWANCE             NUMBER(12,0),
    SEASONALFACTOR                 NUMBER(3,0),
    DPIDSPECIALAGREEMENTINPLACE    NUMBER(1,0) NOT NULL ENABLE,
    DPIDSPECIALAGREEMENTFACTOR     NUMBER(3,0),
    DPIDSPECIALAGREEMENTREFERENCE  VARCHAR2(12 BYTE),
    FREETEXTDESCRIPTOR             VARCHAR2(255 BYTE),
    SECONDADDRESSABLEOBJ           VARCHAR2(100 BYTE),
    PRIMARYADDRESSABLEOBJ          VARCHAR2(100 BYTE),
    ADDRESSLINE01                  VARCHAR2(60 BYTE) NOT NULL ENABLE,
    ADDRESSLINE02                  VARCHAR2(60 BYTE),
    ADDRESSLINE03                  VARCHAR2(60 BYTE),
    ADDRESSLINE04                  VARCHAR2(60 BYTE),
    ADDRESSLINE05                  VARCHAR2(60 BYTE),
    POSTCODE                       VARCHAR2(8 BYTE) NOT NULL ENABLE,
    PAFADDRESSKEY                  NUMBER(9,0),
    VALIDTETARIFFCODE              NUMBER NOT NULL ENABLE,
    TARIFFBANDCOUNT                NUMBER NOT NULL ENABLE,
    AMMONIACALNITROGEN             NUMBER NOT NULL ENABLE,
    XCOMP                          NUMBER NOT NULL ENABLE,
    YCOMP                          NUMBER NOT NULL ENABLE,
    ZCOMP                          NUMBER NOT NULL ENABLE,
    STWIWCS                        VARCHAR2(12 BYTE),
    SAPFLOCNUMBER                  VARCHAR2(10 BYTE),
    STWCONSENTNUMBER               VARCHAR2(12 BYTE),
    OWC                            VARCHAR2(32)  NOT NULL
  );

CREATE INDEX OWC_DISCHARGE_POINT_IDX1 ON RECEPTION.OWC_DISCHARGE_POINT (SPID_PK);

--------------------------------------------------------------------------------------------------------
-- OWC_METER
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_METER
  (
    MANUFACTURERSERIALNUM_PK  VARCHAR2(32 BYTE) NOT NULL ENABLE,
    MANUFACTURER_PK           VARCHAR2(32 BYTE) NOT NULL ENABLE,
    NUMBEROFDIGITS            NUMBER(1,0) NOT NULL ENABLE,
    MEASUREUNITATMETER        VARCHAR2(12 BYTE) NOT NULL ENABLE,
    MEASUREUNITFREEDESCRIPTOR VARCHAR2(255 BYTE),
    PHYSICALMETERSIZE         NUMBER(4,0),
    METERREADFREQUENCY        VARCHAR2(1 BYTE) NOT NULL ENABLE,
    INITIALMETERREADDATE DATE,
    RETURNTOSEWER              NUMBER(3,0),
    WATERCHARGEMETERSIZE       NUMBER(4,0) NOT NULL ENABLE,
    SEWCHARGEABLEMETERSIZE     NUMBER(4,0),
    DATALOGGERWHOLESALER       NUMBER(1,0) NOT NULL ENABLE,
    DATALOGGERNONWHOLESALER    NUMBER(1,0) NOT NULL ENABLE,
    GPSX                       NUMBER(7,1),
    GPSY                       NUMBER(7,1),
    METERLOCFREEDESCRIPTOR     VARCHAR2(255 BYTE),
    METEROUTREADERGPSX         NUMBER(7,1),
    METEROUTREADERGPSY         NUMBER(7,1),
    OUTREADERLOCFREEDES        VARCHAR2(255 BYTE),
    METEROUTREADERLOCCODE      VARCHAR2(1 BYTE),
    METERTREATMENT             VARCHAR2(32 BYTE) NOT NULL ENABLE,
    METERLOCATIONCODE          VARCHAR2(1 BYTE) NOT NULL ENABLE,
    COMBIMETERFLAG             NUMBER(1,0) NOT NULL ENABLE,
    YEARLYVOLESTIMATE          NUMBER(13,0),
    REMOTEREADFLAG             NUMBER(1,0) NOT NULL ENABLE,
    REMOTEREADTYPE             VARCHAR2(12 BYTE),
    OUTREADERID                VARCHAR2(32 BYTE),
    OUTREADERPROTOCOL          VARCHAR2(255 BYTE),
    LOCATIONFREETEXTDESCRIPTOR VARCHAR2(255 BYTE),
    SECONDADDRESABLEOBJECT     VARCHAR2(100 BYTE),
    PRIMARYADDRESSABLEOBJECT   VARCHAR2(100 BYTE),
    ADDRESSLINE01              VARCHAR2(60 BYTE) NOT NULL ENABLE,
    ADDRESSLINE02              VARCHAR2(60 BYTE),
    ADDRESSLINE03              VARCHAR2(60 BYTE),
    ADDRESSLINE04              VARCHAR2(60 BYTE),
    ADDRESSLINE05              VARCHAR2(60 BYTE),
    POSTCODE                   VARCHAR2(8 BYTE) NOT NULL ENABLE,
    PAFADDRESSKEY              NUMBER(8,0),
    SPID                       VARCHAR2(13 BYTE),
    NONMARKETMETERFLAG         NUMBER(1,0),
    SAPEQUIPMENT               VARCHAR2(10 BYTE),
    SAPFLOCNUMBER              VARCHAR2(10 BYTE),
    OWC                        VARCHAR2(32)  NOT NULL
  );

CREATE INDEX OWC_METER_IDX1 ON RECEPTION.OWC_METER (SPID);

--------------------------------------------------------------------------------------------------------
-- OWC_METER_DISCHARGE_POINT
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_METER_DISCHARGE_POINT
  (
    MANUFACTURERSERIALNUM_PK VARCHAR2(32 BYTE) NOT NULL ENABLE,
    MANUFACTURER_PK          VARCHAR2(32 BYTE) NOT NULL ENABLE,
    DPID_PK                  VARCHAR2(32 BYTE) NOT NULL ENABLE,
    PERCENTAGEDISCHARGE      NUMBER(5,2) NOT NULL ENABLE,
    SAPEQUIPMENT             VARCHAR2(10 BYTE),
    OWC                      VARCHAR2(32)  NOT NULL
  );

--------------------------------------------------------------------------------------------------------
-- OWC_METER_NETWORK
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_METER_NETWORK
  (
    SPID_PK                   VARCHAR2(13 BYTE),
    MAINMANUFACTURERSERIALNUM VARCHAR2(32 BYTE) NOT NULL ENABLE,
    MAINMANUFACTURER          VARCHAR2(32 BYTE) NOT NULL ENABLE,
    MAINMETERTREATMENT        VARCHAR2(32 BYTE),
    SUBMANUFACTURERSERIALNUM  VARCHAR2(32 BYTE) NOT NULL ENABLE,
    SUBMANUFACTURER           VARCHAR2(32 BYTE) NOT NULL ENABLE,
    SUBMETERTREATMENT         VARCHAR2(32 BYTE),
    MAINNONMARKETFLAG         NUMBER(1,0),
    MAINSAPEQUIPMENT          VARCHAR2(10 BYTE),
    SUBSAPEQUIPMENT           VARCHAR2(10 BYTE),
    OWC                       VARCHAR2(32)  NOT NULL
  );

--------------------------------------------------------------------------------------------------------
-- OWC_METER_READING
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_METER_READING
  (
    MANUFACTURERSERIALNUM_PK VARCHAR2(32 BYTE) NOT NULL ENABLE,
    MANUFACTURER_PK          VARCHAR2(32 BYTE) NOT NULL ENABLE,
    METERREAD                NUMBER(12,0) NOT NULL ENABLE,
    METERREADMETHOD          VARCHAR2(9 BYTE) NOT NULL ENABLE,
    METERREADDATE DATE NOT NULL ENABLE,
    ROLLOVERINDICATOR            NUMBER(1,0) NOT NULL ENABLE,
    ESTIMATEDREADREASONCODE      VARCHAR2(2 BYTE),
    ESTIMATEDREADREMEDIALWORKIND NUMBER(1,0),
    METERREADTYPE                VARCHAR2(1 BYTE),
    PREVIOUSMETERREADING         NUMBER(12,0),
    METERREF                     NUMBER(15,0),
    PREVMETERREF                 NUMBER(15,0),
    SAPEQUIPMENT                 VARCHAR2(10 BYTE),
    OWC                          VARCHAR2(32)  NOT NULL
  );

--------------------------------------------------------------------------------------------------------
-- OWC_METER_SUPPLY_POINT
--------------------------------------------------------------------------------------------------------  
CREATE TABLE RECEPTION.OWC_METER_SUPPLY_POINT
  (
    MANUFACTURERSERIALNUM_PK VARCHAR2(32 BYTE) NOT NULL ENABLE,
    MANUFACTURER_PK          VARCHAR2(32 BYTE) NOT NULL ENABLE,
    SPID_PK                  VARCHAR2(13 BYTE) NOT NULL ENABLE,
    SAPEQUIPMENT             VARCHAR2(10 BYTE),
    OWC                      VARCHAR2(32)  NOT NULL
  );

CREATE INDEX OWC_METER_SUPPLY_POINT_IDX1 ON RECEPTION.OWC_METER_SUPPLY_POINT (SPID_PK);

--------------------------------------------------------------------------------------------------------
-- OWC_SERVICE_COMPONENT
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_SERVICE_COMPONENT
  (
    SPID_PK                        VARCHAR2(13 BYTE) NOT NULL ENABLE,
    METEREDPWTARIFFCODE            VARCHAR2(32 BYTE),
    MPWSPECIALAGREEMENTFLAG        NUMBER(1,0),
    MPWSPECIALAGREEMENTFACTOR      NUMBER(5,2),
    MPWSPECIALAGREEMENTREF         VARCHAR2(12 BYTE),
    METEREDPWMAXDAILYDEMAND        NUMBER(12,0),
    MPWMAXIMUMDEMANDTARIFF         NUMBER(9,2),
    DAILYRESERVEDCAPACITY          NUMBER(12,0),
    MPWDAILYSTANDBYUSAGEVOLCHARGE  NUMBER(9,2),
    METEREDNPWTARIFFCODE           VARCHAR2(32 BYTE),
    MNPWSPECIALAGREEMENTFLAG       NUMBER(1,0),
    MNPWSPECIALAGREEMENTFACTOR     NUMBER(5,2),
    MNPWSPECIALAGREEMENTREF        VARCHAR2(12 BYTE),
    METEREDNPWMAXDAILYDEMAND       NUMBER(12,0),
    MNPWMAXIMUMDEMANDTARIFF        NUMBER(9,2),
    METEREDNPWDAILYRESVDCAPACITY   NUMBER(12,0),
    MNPWDAILYSTANDBYUSAGEVOLCHARGE NUMBER(9,2),
    AWASSESSEDTARIFFCODE           VARCHAR2(32 BYTE),
    AWSPECIALAGREEMENTFLAG         NUMBER(1,0),
    AWSPECIALAGREEMENTFACTOR       NUMBER(5,2),
    AWSPECIALAGREEMENTREF          VARCHAR2(12 BYTE),
    AWASSESSEDCHARGEMETERSIZE      NUMBER(4,0),
    AWASSESSEDDVOLUMETRICRATE      NUMBER(12,0),
    AWASSESSEDTARIFBAND            NUMBER(2,0),
    AWFIXEDCHARGE                  NUMBER(9,2),
    AWVOLUMETRICCHARGE             NUMBER(9,2),
    AWTARIFFBAND                   NUMBER,
    UWUNMEASUREDTARIFFCODE         VARCHAR2(32 BYTE),
    UWSPECIALAGREEMENTFLAG         NUMBER(1,0),
    UWSPECIALAGREEMENTFACTOR       NUMBER(5,2),
    UWSPECIALAGREEMENTREF          VARCHAR2(12 BYTE),
    UWUNMEASUREDTYPEACOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPEADESCRIPTION   VARCHAR2(255 BYTE),
    UWUNMEASUREDTYPEBCOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPEBDESCRIPTION   VARCHAR2(255 BYTE),
    UWUNMEASUREDTYPECCOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPECDESCRIPTION   VARCHAR2(255 BYTE),
    UWUNMEASUREDTYPEDCOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPEDDESCRIPTION   VARCHAR2(255 BYTE),
    UWUNMEASUREDTYPEECOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPEEDESCRIPTION   VARCHAR2(255 BYTE),
    UWUNMEASUREDTYPEFCOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPEFDESCRIPTION   VARCHAR2(255 BYTE),
    UWUNMEASUREDTYPEGCOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPEGDESCRIPTION   VARCHAR2(255 BYTE),
    UWUNMEASUREDTYPEHCOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPEHDESCRIPTION   VARCHAR2(255 BYTE),
    UWPIPESIZE                     NUMBER(4,0),
    WADJCHARGEADJTARIFFCODE        VARCHAR2(32 BYTE),
    METEREDFSTARIFFCODE            VARCHAR2(32 BYTE),
    MFSSPECIALAGREEMENTFLAG        NUMBER(1,0),
    MFSSPECIALAGREEMENTFACTOR      NUMBER(5,2),
    MFSSPECIALAGREEMENTREF         VARCHAR2(12 BYTE),
    ASASSESSEDTARIFFCODE           VARCHAR2(32 BYTE),
    ASSPECIALAGREEMENTFLAG         NUMBER(1,0),
    ASSPECIALAGREEMENTFACTOR       NUMBER(5,2),
    ASSPECIALAGREEMENTREF          VARCHAR2(12 BYTE),
    ASASSESSEDCHARGEMETERSIZE      NUMBER(4,0),
    ASASSESSEDDVOLUMETRICRATE      NUMBER(12,0),
    ASASSESSEDTARIFBAND            NUMBER(2,0),
    ASFIXEDCHARGE                  NUMBER(9,2),
    ASVOLMETCHARGE                 NUMBER(9,2),
    ASTARIFFBAND                   NUMBER,
    USUNMEASUREDTARIFFCODE         VARCHAR2(32 BYTE),
    USSPECIALAGREEMENTFLAG         NUMBER(1,0),
    USSPECIALAGREEMENTFACTOR       NUMBER(5,2),
    USSPECIALAGREEMENTREF          VARCHAR2(12 BYTE),
    USUNMEASUREDTYPEACOUNT         NUMBER(3,0),
    USUNMEASUREDTYPEADESCRIPTION   VARCHAR2(255 BYTE),
    USUNMEASUREDTYPEBCOUNT         NUMBER(3,0),
    USUNMEASUREDTYPEBDESCRIPTION   VARCHAR2(255 BYTE),
    USUNMEASUREDTYPECCOUNT         NUMBER(3,0),
    USUNMEASUREDTYPECDESCRIPTION   VARCHAR2(255 BYTE),
    USUNMEASUREDTYPEDCOUNT         NUMBER(3,0),
    USUNMEASUREDTYPEDDESCRIPTION   VARCHAR2(255 BYTE),
    USUNMEASUREDTYPEECOUNT         NUMBER(3,0),
    USUNMEASUREDTYPEEDESCRIPTION   VARCHAR2(255 BYTE),
    USUNMEASUREDTYPEFCOUNT         NUMBER(3,0),
    USUNMEASUREDTYPEFDESCRIPTION   VARCHAR2(255 BYTE),
    USUNMEASUREDTYPEGCOUNT         NUMBER(3,0),
    USUNMEASUREDTYPEGDESCRIPTION   VARCHAR2(255 BYTE),
    USUNMEASUREDTYPEHCOUNT         NUMBER(3,0),
    USUNMEASUREDTYPEHDESCRIPTION   VARCHAR2(255 BYTE),
    USPIPESIZE                     NUMBER(4,0),
    SADJCHARGEADJTARIFFCODE        VARCHAR2(32 BYTE),
    SRFCWATERTARRIFCODE            VARCHAR2(32 BYTE),
    SRFCWATERAREADRAINED           NUMBER(12,0),
    SRFCWATERCOMMUNITYCONFLAG      NUMBER(1,0),
    SWSPECIALAGREEMENTFLAG         NUMBER(1,0),
    SWSPECIALAGREEMENTFACTOR       NUMBER(5,2),
    SWSPECIALAGREEMENTREF          VARCHAR2(12 BYTE),
    HWAYDRAINAGETARIFFCODE         VARCHAR2(32 BYTE),
    HWAYSURFACEAREA                NUMBER(12,0),
    HWAYCOMMUNITYCONFLAG           NUMBER(1,0),
    HDSPECIALAGREEMENTFLAG         NUMBER(1,0),
    HDSPECIALAGREEMENTFACTOR       NUMBER(5,2),
    HDSPECIALAGREEMENTREF          VARCHAR2(12 BYTE),
    SAPFLOCNUMBER                  VARCHAR2(10 BYTE),
    OWC                            VARCHAR2(32)  NOT NULL
  );

CREATE INDEX OWC_SERVICE_COMPONENT_IDX1 ON RECEPTION.OWC_SERVICE_COMPONENT (SPID_PK)  ;

--------------------------------------------------------------------------------------------------------
-- OWC_SUPPLY_POINT
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_SUPPLY_POINT
  (
    SPID_PK         VARCHAR2(13 BYTE),
    WHOLESALERID    VARCHAR2(12 BYTE) NOT NULL ENABLE,
    RETAILERID      VARCHAR2(12 BYTE) NOT NULL ENABLE,
    SERVICECATEGORY VARCHAR2(1 BYTE) NOT NULL ENABLE,
    SUPPLYPOINTEFFECTIVEFROMDATE DATE,
    PAIRINGREFREASONCODE           VARCHAR2(12 BYTE),
    OTHERWHOLESALERID              VARCHAR2(12 BYTE),
    MULTIPLEWHOLESALERFLAG         NUMBER(1,0) NOT NULL ENABLE,
    DISCONRECONDEREGSTATUS         VARCHAR2(5 BYTE),
    VOABAREFERENCE                 VARCHAR2(32 BYTE),
    VOABAREFRSNCODE                VARCHAR2(2 BYTE),
    UPRN                           NUMBER(13,0),
    UPRNREASONCODE                 VARCHAR2(2 BYTE),
    CUSTOMERCLASSIFICATION         VARCHAR2(5 BYTE) NOT NULL ENABLE,
    PUBHEALTHRELSITEARR            NUMBER(1,0) NOT NULL ENABLE,
    NONPUBHEALTHRELSITE            NUMBER(1,0) NOT NULL ENABLE,
    NONPUBHEALTHRELSITEDSC         VARCHAR2(255 BYTE),
    STDINDUSTRYCLASSCODE           VARCHAR2(12 BYTE),
    STDINDUSTRYCLASSCODETYPE       VARCHAR2(4 BYTE),
    RATEABLEVALUE                  NUMBER(10,2),
    OCCUPENCYSTATUS                VARCHAR2(12 BYTE) NOT NULL ENABLE,
    BUILDINGWATERSTATUS            NUMBER(1,0) NOT NULL ENABLE,
    LANDLORDSPID                   VARCHAR2(32 BYTE),
    SECTION154                     NUMBER(4,0),
    CUSTOMERNAME                   VARCHAR2(255 BYTE) NOT NULL ENABLE,
    CUSTOMERBANNERNAME             VARCHAR2(255 BYTE),
    PREMLOCATIONFREETEXTDESCRIPTOR VARCHAR2(255 BYTE),
    PREMSECONDADDRESABLEOBJECT     VARCHAR2(255 BYTE),
    PREMPRIMARYADDRESSABLEOBJECT   VARCHAR2(100 BYTE),
    PREMADDRESSLINE01              VARCHAR2(60 BYTE) NOT NULL ENABLE,
    PREMADDRESSLINE02              VARCHAR2(60 BYTE),
    PREMADDRESSLINE03              VARCHAR2(60 BYTE),
    PREMADDRESSLINE04              VARCHAR2(60 BYTE),
    PREMADDRESSLINE05              VARCHAR2(60 BYTE),
    PREMPOSTCODE                   VARCHAR2(8 BYTE) NOT NULL ENABLE,
    PREMPAFADDRESSKEY              NUMBER(9,0),
    CUSTLOCATIONFREETEXTDESCRIPTOR VARCHAR2(255 BYTE),
    CUSTSECONDADDRESABLEOBJECT     VARCHAR2(255 BYTE),
    CUSTPRIMARYADDRESSABLEOBJECT   VARCHAR2(100 BYTE),
    CUSTADDRESSLINE01              VARCHAR2(60 BYTE) NOT NULL ENABLE,
    CUSTADDRESSLINE02              VARCHAR2(60 BYTE),
    CUSTADDRESSLINE03              VARCHAR2(60 BYTE),
    CUSTADDRESSLINE04              VARCHAR2(60 BYTE),
    CUSTADDRESSLINE05              VARCHAR2(60 BYTE),
    CUSTPOSTCODE                   VARCHAR2(8 BYTE) NOT NULL ENABLE,
    CUSTCOUNTRY                    VARCHAR2(32 BYTE),
    CUSTPAFADDRESSKEY              NUMBER(9,0),
    STWPROPERTYNUMBER              VARCHAR2(9 BYTE),
    SAPFLOCNUMBER                  VARCHAR2(10 BYTE),
    STWCUSTOMERNUMBER              VARCHAR2(9 BYTE),
    OWC                            VARCHAR2(32)  NOT NULL
  );
ALTER TABLE OWC_SUPPLY_POINT ADD CONSTRAINT PK_OWC_SPID PRIMARY KEY (SPID_PK);

--------------------------------------------------------------------------------------------------------
-- OWC_CALCULATED_DISCHARGE
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_CALCULATED_DISCHARGE
  (
    DPID_PK             VARCHAR2(32 BYTE) NOT NULL ENABLE,
    CALCDISCHARGEID_PK  VARCHAR2(15 BYTE) NOT NULL ENABLE,
    DISCHARGETYPE       VARCHAR2(12 BYTE) NOT NULL ENABLE,
    SUBMISSIONFREQ      VARCHAR2(1 BYTE) NOT NULL ENABLE,
    TEYEARLYVOLESTIMATE NUMBER(13,0) NOT NULL ENABLE,
    OWC                 VARCHAR2(32)  NOT NULL
  );

--------------------------------------------------------------------------------------------------------
-- WATER FILES TABLES
--------------------------------------------------------------------------------------------------------
-- OWC_DISCHARGE_POINT_W
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_DISCHARGE_POINT_W
  (
    SPID_PK                        VARCHAR2(13 BYTE) NOT NULL ENABLE,
    DPID_PK                        VARCHAR2(32 BYTE) NOT NULL ENABLE,
    TARRIFCODE                     VARCHAR2(32 BYTE) NOT NULL ENABLE,
    TARRIFBAND                     NUMBER(2,0),
    TREFODCHEMOXYGENDEMAND         NUMBER(6,0),
    TREFODCHEMSUSPSOLDEMAND        NUMBER(6,0),
    TREFODCHEMAMONIANITROGENDEMAND NUMBER(6,0),
    TREFODCHEMCOMPXDEMAND          NUMBER(6,0),
    TREFODCHEMCOMPYDEMAND          NUMBER(6,0),
    TREFODCHEMCOMPZDEMAND          NUMBER(6,0),
    SEWERAGEVOLUMEADJMENTHOD       VARCHAR2(8 BYTE) NOT NULL ENABLE,
    RECEPTIONTREATMENTINDICATOR    NUMBER(1,0) NOT NULL ENABLE,
    PRIMARYTREATMENTINDICATOR      NUMBER(1,0) NOT NULL ENABLE,
    MARINETREATMENTINDICATOR       NUMBER(1,0) NOT NULL ENABLE,
    BIOLOGICALTREATMENTINDICATOR   NUMBER(1,0) NOT NULL ENABLE,
    SLUDGETREATMENTINDICATOR       NUMBER(1,0) NOT NULL ENABLE,
    AMMONIATREATMENTINDICATOR      NUMBER(1,0) NOT NULL ENABLE,
    TEFXTREATMENTINDICATOR         NUMBER(1,0) NOT NULL ENABLE,
    TEFYTREATMENTINDICATOR         NUMBER(1,0) NOT NULL ENABLE,
    TEFZTREATMENTINDICATOR         NUMBER(1,0) NOT NULL ENABLE,
    TEFAVAILABILITYDATAX           NUMBER(9,0),
    TEFAVAILABILITYDATAY           NUMBER(9,0),
    TEFAVAILABILITYDATAZ           NUMBER(9,0),
    CHARGEABLEDAILYVOL             NUMBER(12,0),
    CHEMICALOXYGENDEMAND           NUMBER(12,0),
    SUSPENDEDSOLIDSLOAD            NUMBER(12,0),
    AMMONIANITROCAL                NUMBER(12,0),
    FIXEDALLOWANCE                 NUMBER(12,0) NOT NULL ENABLE,
    PERCENTAGEALLOWANCE            NUMBER(3,0) NOT NULL ENABLE,
    DOMMESTICALLOWANCE             NUMBER(12,0),
    SEASONALFACTOR                 NUMBER(3,0),
    DPIDSPECIALAGREEMENTINPLACE    NUMBER(1,0) NOT NULL ENABLE,
    DPIDSPECIALAGREEMENTFACTOR     NUMBER(3,0),
    DPIDSPECIALAGREEMENTREFERENCE  VARCHAR2(12 BYTE),
    FREETEXTDESCRIPTOR             VARCHAR2(255 BYTE),
    SECONDADDRESSABLEOBJ           VARCHAR2(100 BYTE),
    PRIMARYADDRESSABLEOBJ          VARCHAR2(100 BYTE),
    ADDRESSLINE01                  VARCHAR2(60 BYTE) NOT NULL ENABLE,
    ADDRESSLINE02                  VARCHAR2(60 BYTE),
    ADDRESSLINE03                  VARCHAR2(60 BYTE),
    ADDRESSLINE04                  VARCHAR2(60 BYTE),
    ADDRESSLINE05                  VARCHAR2(60 BYTE),
    POSTCODE                       VARCHAR2(8 BYTE) NOT NULL ENABLE,
    PAFADDRESSKEY                  NUMBER(9,0),
    VALIDTETARIFFCODE              NUMBER NOT NULL ENABLE,
    TARIFFBANDCOUNT                NUMBER NOT NULL ENABLE,
    AMMONIACALNITROGEN             NUMBER NOT NULL ENABLE,
    XCOMP                          NUMBER NOT NULL ENABLE,
    YCOMP                          NUMBER NOT NULL ENABLE,
    ZCOMP                          NUMBER NOT NULL ENABLE,
    STWIWCS                        VARCHAR2(12 BYTE),
    SAPFLOCNUMBER                  VARCHAR2(10 BYTE),
    STWCONSENTNUMBER               VARCHAR2(12 BYTE),
    OWC                            VARCHAR2(32)  NOT NULL
  );

CREATE INDEX OWC_DISCHARGE_POINT_IDX1_W ON RECEPTION.OWC_DISCHARGE_POINT_W (SPID_PK);

--------------------------------------------------------------------------------------------------------
-- OWC_METER_W
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_METER_W
  (
    MANUFACTURERSERIALNUM_PK  VARCHAR2(32 BYTE) NOT NULL ENABLE,
    MANUFACTURER_PK           VARCHAR2(32 BYTE) NOT NULL ENABLE,
    NUMBEROFDIGITS            NUMBER(1,0) NOT NULL ENABLE,
    MEASUREUNITATMETER        VARCHAR2(12 BYTE) NOT NULL ENABLE,
    MEASUREUNITFREEDESCRIPTOR VARCHAR2(255 BYTE),
    PHYSICALMETERSIZE         NUMBER(4,0),
    METERREADFREQUENCY        VARCHAR2(1 BYTE) NOT NULL ENABLE,
    INITIALMETERREADDATE DATE,
    RETURNTOSEWER              NUMBER(3,0),
    WATERCHARGEMETERSIZE       NUMBER(4,0) NOT NULL ENABLE,
    SEWCHARGEABLEMETERSIZE     NUMBER(4,0),
    DATALOGGERWHOLESALER       NUMBER(1,0) NOT NULL ENABLE,
    DATALOGGERNONWHOLESALER    NUMBER(1,0) NOT NULL ENABLE,
    GPSX                       NUMBER(7,1),
    GPSY                       NUMBER(7,1),
    METERLOCFREEDESCRIPTOR     VARCHAR2(255 BYTE),
    METEROUTREADERGPSX         NUMBER(7,1),
    METEROUTREADERGPSY         NUMBER(7,1),
    OUTREADERLOCFREEDES        VARCHAR2(255 BYTE),
    METEROUTREADERLOCCODE      VARCHAR2(1 BYTE),
    METERTREATMENT             VARCHAR2(32 BYTE) NOT NULL ENABLE,
    METERLOCATIONCODE          VARCHAR2(1 BYTE) NOT NULL ENABLE,
    COMBIMETERFLAG             NUMBER(1,0) NOT NULL ENABLE,
    YEARLYVOLESTIMATE          NUMBER(13,0),
    REMOTEREADFLAG             NUMBER(1,0) NOT NULL ENABLE,
    REMOTEREADTYPE             VARCHAR2(12 BYTE),
    OUTREADERID                VARCHAR2(32 BYTE),
    OUTREADERPROTOCOL          VARCHAR2(255 BYTE),
    LOCATIONFREETEXTDESCRIPTOR VARCHAR2(255 BYTE),
    SECONDADDRESABLEOBJECT     VARCHAR2(100 BYTE),
    PRIMARYADDRESSABLEOBJECT   VARCHAR2(100 BYTE),
    ADDRESSLINE01              VARCHAR2(60 BYTE) NOT NULL ENABLE,
    ADDRESSLINE02              VARCHAR2(60 BYTE),
    ADDRESSLINE03              VARCHAR2(60 BYTE),
    ADDRESSLINE04              VARCHAR2(60 BYTE),
    ADDRESSLINE05              VARCHAR2(60 BYTE),
    POSTCODE                   VARCHAR2(8 BYTE) NOT NULL ENABLE,
    PAFADDRESSKEY              NUMBER(8,0),
    SPID                       VARCHAR2(13 BYTE),
    NONMARKETMETERFLAG         NUMBER(1,0),
    SAPEQUIPMENT               VARCHAR2(10 BYTE),
    SAPFLOCNUMBER              VARCHAR2(10 BYTE),
    OWC                        VARCHAR2(32)  NOT NULL
  );

CREATE INDEX OWC_METER_IDX1_W ON RECEPTION.OWC_METER_W (SPID);

--------------------------------------------------------------------------------------------------------
-- OWC_METER_DISCHARGE_POINT_W
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_METER_DISCHARGE_POINT_W
  (
    MANUFACTURERSERIALNUM_PK VARCHAR2(32 BYTE) NOT NULL ENABLE,
    MANUFACTURER_PK          VARCHAR2(32 BYTE) NOT NULL ENABLE,
    DPID_PK                  VARCHAR2(32 BYTE) NOT NULL ENABLE,
    PERCENTAGEDISCHARGE      NUMBER(5,2) NOT NULL ENABLE,
    SAPEQUIPMENT             VARCHAR2(10 BYTE),
    OWC                      VARCHAR2(32)  NOT NULL
  );

--------------------------------------------------------------------------------------------------------
-- OWC_METER_NETWORK_W
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_METER_NETWORK_W
  (
    SPID_PK                   VARCHAR2(13 BYTE),
    MAINMANUFACTURERSERIALNUM VARCHAR2(32 BYTE) NOT NULL ENABLE,
    MAINMANUFACTURER          VARCHAR2(32 BYTE) NOT NULL ENABLE,
    MAINMETERTREATMENT        VARCHAR2(32 BYTE),
    SUBMANUFACTURERSERIALNUM  VARCHAR2(32 BYTE) NOT NULL ENABLE,
    SUBMANUFACTURER           VARCHAR2(32 BYTE) NOT NULL ENABLE,
    SUBMETERTREATMENT         VARCHAR2(32 BYTE),
    MAINNONMARKETFLAG         NUMBER(1,0),
    MAINSAPEQUIPMENT          VARCHAR2(10 BYTE),
    SUBSAPEQUIPMENT           VARCHAR2(10 BYTE),
    OWC                       VARCHAR2(32)  NOT NULL
  );

--------------------------------------------------------------------------------------------------------
-- OWC_METER_READING_W
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_METER_READING_W
  (
    MANUFACTURERSERIALNUM_PK VARCHAR2(32 BYTE) NOT NULL ENABLE,
    MANUFACTURER_PK          VARCHAR2(32 BYTE) NOT NULL ENABLE,
    METERREAD                NUMBER(12,0) NOT NULL ENABLE,
    METERREADMETHOD          VARCHAR2(9 BYTE) NOT NULL ENABLE,
    METERREADDATE DATE NOT NULL ENABLE,
    ROLLOVERINDICATOR            NUMBER(1,0) NOT NULL ENABLE,
    ESTIMATEDREADREASONCODE      VARCHAR2(2 BYTE),
    ESTIMATEDREADREMEDIALWORKIND NUMBER(1,0),
    METERREADTYPE                VARCHAR2(1 BYTE),
    PREVIOUSMETERREADING         NUMBER(12,0),
    METERREF                     NUMBER(15,0),
    PREVMETERREF                 NUMBER(15,0),
    SAPEQUIPMENT                 VARCHAR2(10 BYTE),
    OWC                          VARCHAR2(32)  NOT NULL
  );

--------------------------------------------------------------------------------------------------------
-- OWC_METER_SUPPLY_POINT_W
--------------------------------------------------------------------------------------------------------  
CREATE TABLE RECEPTION.OWC_METER_SUPPLY_POINT_W
  (
    MANUFACTURERSERIALNUM_PK VARCHAR2(32 BYTE) NOT NULL ENABLE,
    MANUFACTURER_PK          VARCHAR2(32 BYTE) NOT NULL ENABLE,
    SPID_PK                  VARCHAR2(13 BYTE) NOT NULL ENABLE,
    SAPEQUIPMENT             VARCHAR2(10 BYTE),
    OWC                      VARCHAR2(32)  NOT NULL
  );

CREATE INDEX OWC_METER_SUPPLY_POINT_IDX1_W ON RECEPTION.OWC_METER_SUPPLY_POINT_W (SPID_PK);

--------------------------------------------------------------------------------------------------------
-- OWC_SERVICE_COMPONENT_W
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_SERVICE_COMPONENT_W
  (
    SPID_PK                        VARCHAR2(13 BYTE) NOT NULL ENABLE,
    METEREDPWTARIFFCODE            VARCHAR2(32 BYTE),
    MPWSPECIALAGREEMENTFLAG        NUMBER(1,0),
    MPWSPECIALAGREEMENTFACTOR      NUMBER(5,2),
    MPWSPECIALAGREEMENTREF         VARCHAR2(12 BYTE),
    METEREDPWMAXDAILYDEMAND        NUMBER(12,0),
    MPWMAXIMUMDEMANDTARIFF         NUMBER(9,2),
    DAILYRESERVEDCAPACITY          NUMBER(12,0),
    MPWDAILYSTANDBYUSAGEVOLCHARGE  NUMBER(9,2),
    METEREDNPWTARIFFCODE           VARCHAR2(32 BYTE),
    MNPWSPECIALAGREEMENTFLAG       NUMBER(1,0),
    MNPWSPECIALAGREEMENTFACTOR     NUMBER(5,2),
    MNPWSPECIALAGREEMENTREF        VARCHAR2(12 BYTE),
    METEREDNPWMAXDAILYDEMAND       NUMBER(12,0),
    MNPWMAXIMUMDEMANDTARIFF        NUMBER(9,2),
    METEREDNPWDAILYRESVDCAPACITY   NUMBER(12,0),
    MNPWDAILYSTANDBYUSAGEVOLCHARGE NUMBER(9,2),
    AWASSESSEDTARIFFCODE           VARCHAR2(32 BYTE),
    AWSPECIALAGREEMENTFLAG         NUMBER(1,0),
    AWSPECIALAGREEMENTFACTOR       NUMBER(5,2),
    AWSPECIALAGREEMENTREF          VARCHAR2(12 BYTE),
    AWASSESSEDCHARGEMETERSIZE      NUMBER(4,0),
    AWASSESSEDDVOLUMETRICRATE      NUMBER(12,0),
    AWASSESSEDTARIFBAND            NUMBER(2,0),
    AWFIXEDCHARGE                  NUMBER(9,2),
    AWVOLUMETRICCHARGE             NUMBER(9,2),
    AWTARIFFBAND                   NUMBER,
    UWUNMEASUREDTARIFFCODE         VARCHAR2(32 BYTE),
    UWSPECIALAGREEMENTFLAG         NUMBER(1,0),
    UWSPECIALAGREEMENTFACTOR       NUMBER(5,2),
    UWSPECIALAGREEMENTREF          VARCHAR2(12 BYTE),
    UWUNMEASUREDTYPEACOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPEADESCRIPTION   VARCHAR2(255 BYTE),
    UWUNMEASUREDTYPEBCOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPEBDESCRIPTION   VARCHAR2(255 BYTE),
    UWUNMEASUREDTYPECCOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPECDESCRIPTION   VARCHAR2(255 BYTE),
    UWUNMEASUREDTYPEDCOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPEDDESCRIPTION   VARCHAR2(255 BYTE),
    UWUNMEASUREDTYPEECOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPEEDESCRIPTION   VARCHAR2(255 BYTE),
    UWUNMEASUREDTYPEFCOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPEFDESCRIPTION   VARCHAR2(255 BYTE),
    UWUNMEASUREDTYPEGCOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPEGDESCRIPTION   VARCHAR2(255 BYTE),
    UWUNMEASUREDTYPEHCOUNT         NUMBER(3,0),
    UWUNMEASUREDTYPEHDESCRIPTION   VARCHAR2(255 BYTE),
    UWPIPESIZE                     NUMBER(4,0),
    WADJCHARGEADJTARIFFCODE        VARCHAR2(32 BYTE),
    METEREDFSTARIFFCODE            VARCHAR2(32 BYTE),
    MFSSPECIALAGREEMENTFLAG        NUMBER(1,0),
    MFSSPECIALAGREEMENTFACTOR      NUMBER(5,2),
    MFSSPECIALAGREEMENTREF         VARCHAR2(12 BYTE),
    ASASSESSEDTARIFFCODE           VARCHAR2(32 BYTE),
    ASSPECIALAGREEMENTFLAG         NUMBER(1,0),
    ASSPECIALAGREEMENTFACTOR       NUMBER(5,2),
    ASSPECIALAGREEMENTREF          VARCHAR2(12 BYTE),
    ASASSESSEDCHARGEMETERSIZE      NUMBER(4,0),
    ASASSESSEDDVOLUMETRICRATE      NUMBER(12,0),
    ASASSESSEDTARIFBAND            NUMBER(2,0),
    ASFIXEDCHARGE                  NUMBER(9,2),
    ASVOLMETCHARGE                 NUMBER(9,2),
    ASTARIFFBAND                   NUMBER,
    USUNMEASUREDTARIFFCODE         VARCHAR2(32 BYTE),
    USSPECIALAGREEMENTFLAG         NUMBER(1,0),
    USSPECIALAGREEMENTFACTOR       NUMBER(5,2),
    USSPECIALAGREEMENTREF          VARCHAR2(12 BYTE),
    USUNMEASUREDTYPEACOUNT         NUMBER(3,0),
    USUNMEASUREDTYPEADESCRIPTION   VARCHAR2(255 BYTE),
    USUNMEASUREDTYPEBCOUNT         NUMBER(3,0),
    USUNMEASUREDTYPEBDESCRIPTION   VARCHAR2(255 BYTE),
    USUNMEASUREDTYPECCOUNT         NUMBER(3,0),
    USUNMEASUREDTYPECDESCRIPTION   VARCHAR2(255 BYTE),
    USUNMEASUREDTYPEDCOUNT         NUMBER(3,0),
    USUNMEASUREDTYPEDDESCRIPTION   VARCHAR2(255 BYTE),
    USUNMEASUREDTYPEECOUNT         NUMBER(3,0),
    USUNMEASUREDTYPEEDESCRIPTION   VARCHAR2(255 BYTE),
    USUNMEASUREDTYPEFCOUNT         NUMBER(3,0),
    USUNMEASUREDTYPEFDESCRIPTION   VARCHAR2(255 BYTE),
    USUNMEASUREDTYPEGCOUNT         NUMBER(3,0),
    USUNMEASUREDTYPEGDESCRIPTION   VARCHAR2(255 BYTE),
    USUNMEASUREDTYPEHCOUNT         NUMBER(3,0),
    USUNMEASUREDTYPEHDESCRIPTION   VARCHAR2(255 BYTE),
    USPIPESIZE                     NUMBER(4,0),
    SADJCHARGEADJTARIFFCODE        VARCHAR2(32 BYTE),
    SRFCWATERTARRIFCODE            VARCHAR2(32 BYTE),
    SRFCWATERAREADRAINED           NUMBER(12,0),
    SRFCWATERCOMMUNITYCONFLAG      NUMBER(1,0),
    SWSPECIALAGREEMENTFLAG         NUMBER(1,0),
    SWSPECIALAGREEMENTFACTOR       NUMBER(5,2),
    SWSPECIALAGREEMENTREF          VARCHAR2(12 BYTE),
    HWAYDRAINAGETARIFFCODE         VARCHAR2(32 BYTE),
    HWAYSURFACEAREA                NUMBER(12,0),
    HWAYCOMMUNITYCONFLAG           NUMBER(1,0),
    HDSPECIALAGREEMENTFLAG         NUMBER(1,0),
    HDSPECIALAGREEMENTFACTOR       NUMBER(5,2),
    HDSPECIALAGREEMENTREF          VARCHAR2(12 BYTE),
    SAPFLOCNUMBER                  VARCHAR2(10 BYTE),
    OWC                            VARCHAR2(32)  NOT NULL
  );

CREATE INDEX OWC_SERVICE_COMPONENT_IDX1_W ON RECEPTION.OWC_SERVICE_COMPONENT_W (SPID_PK)  ;

--------------------------------------------------------------------------------------------------------
-- OWC_SUPPLY_POINT_W
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_SUPPLY_POINT_W
  (
    SPID_PK         VARCHAR2(13 BYTE),
    WHOLESALERID    VARCHAR2(12 BYTE) NOT NULL ENABLE,
    RETAILERID      VARCHAR2(12 BYTE) NOT NULL ENABLE,
    SERVICECATEGORY VARCHAR2(1 BYTE) NOT NULL ENABLE,
    SUPPLYPOINTEFFECTIVEFROMDATE DATE,
    PAIRINGREFREASONCODE           VARCHAR2(12 BYTE),
    OTHERWHOLESALERID              VARCHAR2(12 BYTE),
    MULTIPLEWHOLESALERFLAG         NUMBER(1,0) NOT NULL ENABLE,
    DISCONRECONDEREGSTATUS         VARCHAR2(5 BYTE),
    VOABAREFERENCE                 VARCHAR2(32 BYTE),
    VOABAREFRSNCODE                VARCHAR2(2 BYTE),
    UPRN                           NUMBER(13,0),
    UPRNREASONCODE                 VARCHAR2(2 BYTE),
    CUSTOMERCLASSIFICATION         VARCHAR2(5 BYTE) NOT NULL ENABLE,
    PUBHEALTHRELSITEARR            NUMBER(1,0) NOT NULL ENABLE,
    NONPUBHEALTHRELSITE            NUMBER(1,0) NOT NULL ENABLE,
    NONPUBHEALTHRELSITEDSC         VARCHAR2(255 BYTE),
    STDINDUSTRYCLASSCODE           VARCHAR2(12 BYTE),
    STDINDUSTRYCLASSCODETYPE       VARCHAR2(4 BYTE),
    RATEABLEVALUE                  NUMBER(10,2),
    OCCUPENCYSTATUS                VARCHAR2(12 BYTE) NOT NULL ENABLE,
    BUILDINGWATERSTATUS            NUMBER(1,0) NOT NULL ENABLE,
    LANDLORDSPID                   VARCHAR2(32 BYTE),
    SECTION154                     NUMBER(4,0),
    CUSTOMERNAME                   VARCHAR2(255 BYTE) NOT NULL ENABLE,
    CUSTOMERBANNERNAME             VARCHAR2(255 BYTE),
    PREMLOCATIONFREETEXTDESCRIPTOR VARCHAR2(255 BYTE),
    PREMSECONDADDRESABLEOBJECT     VARCHAR2(255 BYTE),
    PREMPRIMARYADDRESSABLEOBJECT   VARCHAR2(100 BYTE),
    PREMADDRESSLINE01              VARCHAR2(60 BYTE) NOT NULL ENABLE,
    PREMADDRESSLINE02              VARCHAR2(60 BYTE),
    PREMADDRESSLINE03              VARCHAR2(60 BYTE),
    PREMADDRESSLINE04              VARCHAR2(60 BYTE),
    PREMADDRESSLINE05              VARCHAR2(60 BYTE),
    PREMPOSTCODE                   VARCHAR2(8 BYTE) NOT NULL ENABLE,
    PREMPAFADDRESSKEY              NUMBER(9,0),
    CUSTLOCATIONFREETEXTDESCRIPTOR VARCHAR2(255 BYTE),
    CUSTSECONDADDRESABLEOBJECT     VARCHAR2(255 BYTE),
    CUSTPRIMARYADDRESSABLEOBJECT   VARCHAR2(100 BYTE),
    CUSTADDRESSLINE01              VARCHAR2(60 BYTE) NOT NULL ENABLE,
    CUSTADDRESSLINE02              VARCHAR2(60 BYTE),
    CUSTADDRESSLINE03              VARCHAR2(60 BYTE),
    CUSTADDRESSLINE04              VARCHAR2(60 BYTE),
    CUSTADDRESSLINE05              VARCHAR2(60 BYTE),
    CUSTPOSTCODE                   VARCHAR2(8 BYTE) NOT NULL ENABLE,
    CUSTCOUNTRY                    VARCHAR2(32 BYTE),
    CUSTPAFADDRESSKEY              NUMBER(9,0),
    STWPROPERTYNUMBER              VARCHAR2(9 BYTE),
    SAPFLOCNUMBER                  VARCHAR2(10 BYTE),
    STWCUSTOMERNUMBER              VARCHAR2(9 BYTE),
    S_SPID_PK                      VARCHAR2(13 BYTE), --SEWERAGE SPID CORRESPONDING TO WATER SPID
    OWC                            VARCHAR2(32)  NOT NULL
  );
  ALTER TABLE OWC_SUPPLY_POINT_W ADD CONSTRAINT PK_OWC_SPID_W PRIMARY KEY (SPID_PK);

--------------------------------------------------------------------------------------------------------
-- OWC_CALCULATED_DISCHARGE_W
--------------------------------------------------------------------------------------------------------
CREATE TABLE RECEPTION.OWC_CALCULATED_DISCHARGE_W
  (
    DPID_PK             VARCHAR2(32 BYTE) NOT NULL ENABLE,
    CALCDISCHARGEID_PK  VARCHAR2(15 BYTE) NOT NULL ENABLE,
    DISCHARGETYPE       VARCHAR2(12 BYTE) NOT NULL ENABLE,
    SUBMISSIONFREQ      VARCHAR2(1 BYTE) NOT NULL ENABLE,
    TEYEARLYVOLESTIMATE NUMBER(13,0) NOT NULL ENABLE,
    OWC                 VARCHAR2(32)  NOT NULL
  );
COMMIT;
show errors;
exit;  