--
-- Updated DWRCYMRU SPIDs to SPIDs from designated STW SPID range
--
-- Subversion $Revision: 6122 $	
--
---------------------------------------------------------------------------------------
-- Version     Date        Author     Description
-- ---------   ----------  --------   --------------------------------------------------
-- V 0.01      03/11/2016  S.Badhan   Intial version. SAP version of 03_UPDATE_DWRCYMRU_SPIDS
-- V 0.02      07/11/2016  K.Burton   Added update to OWC_SUPPLY_POIINT.STWPROPERTYNUMBER
--                                    For TE mapped properties
----------------------------------------------------------------------------------------

UPDATE OWC_SUPPLY_POINT OSP
SET OSP.LANDLORDSPID = NVL((SELECT LANDLORDSPID FROM SAPTRAN.LU_SS_LANDLORD WHERE SPID = OSP.SPID_PK), OSP.LANDLORDSPID);

UPDATE OWC_SERVICE_COMPONENT OSC
SET OSC.SPID_PK = NVL((SELECT SPID_PK FROM SAPTRAN.LU_SPID_RANGE_DWRCYMRU WHERE DWRCYMRU_SPID = OSC.SPID_PK),OSC.SPID_PK)
WHERE OWC = 'DWRCYMRU-W'
AND EXISTS (SELECT 1 FROM OWC_SUPPLY_POINT WHERE OWC = 'DWRCYMRU-W' AND SPID_PK = OSC.SPID_PK);

UPDATE OWC_METER_SUPPLY_POINT OMSP
SET OMSP.SPID_PK = NVL((SELECT SPID_PK FROM SAPTRAN.LU_SPID_RANGE_DWRCYMRU WHERE DWRCYMRU_SPID = OMSP.SPID_PK),OMSP.SPID_PK)
WHERE OWC = 'DWRCYMRU-W'
AND EXISTS (SELECT 1 FROM OWC_SUPPLY_POINT WHERE OWC = 'DWRCYMRU-W' AND SPID_PK = OMSP.SPID_PK);

UPDATE OWC_SUPPLY_POINT OSP
SET OSP.SPID_PK = NVL((SELECT SPID_PK FROM SAPTRAN.LU_SPID_RANGE_DWRCYMRU WHERE DWRCYMRU_SPID = OSP.SPID_PK),OSP.SPID_PK)
WHERE OWC = 'DWRCYMRU-W';

UPDATE OWC_METER OM
SET OM.SPID = (SELECT DISTINCT SPID_PK FROM OWC_METER_SUPPLY_POINT WHERE MANUFACTURER_PK = OM.MANUFACTURER_PK AND MANUFACTURERSERIALNUM_PK = OM.MANUFACTURERSERIALNUM_PK)
WHERE OWC = 'DWRCYMRU-W';

-- Update NOSPID SPIDs from OWCs to STW SPIDs
UPDATE OWC_SERVICE_COMPONENT OSC
SET OSC.SPID_PK = NVL((SELECT SPID_PK FROM SAPTRAN.LU_SPID_RANGE_NOSPID WHERE NOSPID_SPID = OSC.SPID_PK),OSC.SPID_PK)
WHERE EXISTS (SELECT 1 FROM OWC_SUPPLY_POINT WHERE PAIRINGREFREASONCODE = 'NOSPID' AND SPID_PK = OSC.SPID_PK);

UPDATE OWC_SUPPLY_POINT OSP
SET OSP.SPID_PK = NVL((SELECT SPID_PK FROM SAPTRAN.LU_SPID_RANGE_NOSPID WHERE NOSPID_SPID = OSP.SPID_PK),OSP.SPID_PK)
WHERE PAIRINGREFREASONCODE = 'NOSPID';

-- Update STW Properties from LU_OWC_TE_METERS table
UPDATE OWC_SUPPLY_POINT OSP
SET OSP.STWPROPERTYNUMBER = (SELECT DISTINCT STW_PROPERTYNUMBER FROM SAPTRAN.LU_OWC_TE_METERS WHERE OWC_SPID = OSP.SPID_PK AND ROWNUM = 1)
WHERE OSP.STWPROPERTYNUMBER IS NULL
AND EXISTS (SELECT 1 FROM SAPTRAN.LU_OWC_TE_METERS WHERE OWC_SPID = OSP.SPID_PK);

COMMIT;
show errors;
exit;