------------------------------------------------------------------------------
-- TASK				: 	MOSL DELIVERY CREATION 
--
-- AUTHOR         		: 	Kevin Burton
--
-- FILENAME       		: 	01_DROP_SAP_DEL_TABLES.sql
--
-- CREATED        		: 	23/04/2016
--	
-- Subversion $Revision: 5830 $
--
-- DESCRIPTION 		   	: 	Drops all database tables for SAP upload
--
-- NOTES  			:	
--
-- ASSOCIATED FILES		:	
-- ASSOCIATED SCRIPTS 	 	:	
--
---------------------------- Modification History ----------------------------------------------------------
--
-- Version     		Date        	 	Author         	Description
-- --------------------------------------------------------------------------------------------------------
-- V0.01	       	23/04/2016   	 	K.Burton	Initial version
-- V0.02          03/06/2016      D.Cheung  Added Device Characteristics (DEVCHAR) and Device Location Change (DVLCHG) tables.
-- V0.03          03/06/2016      D.Cheung  New Device Structure following standup (legacy key meeting)
--                                              SAP_DEL_DEV (both Create and MOSL Update)
--                                              SAP_DEL_DEVCHAR (Characteristics)
--                                              SAP_DEL_DVL (both device location create and update)
-- V0.04          06/06/2016      D.Cheung  Rename characteristics - SAP_DEL_DEC
-- V0.05          08/06/2016      K.Burton  Added DEV, COM and METER READ tables
-- V0.06          14/06/2016      K.Burton  Added METER INSTALL, DP and REG tables
-- V0.07          15/09/2016      K.Burton  CR_017 - Added lookup LU_SAP_SENSITIVITY_CODES
-- V0.08          13/10/2016      S.Badhan  Remove non-existant constraints.
-- --------------------------------------------------------------------------------------------------------
-- DISABLE FOREIGN KEYS
ALTER TABLE SAP_DEL_REG DISABLE CONSTRAINT FK04_DEV_LEGACYRECNUM;

ALTER TABLE SAP_DEL_PODSRV DISABLE CONSTRAINT FK01_PODSRV_SPID;
ALTER TABLE SAP_DEL_PODMO DISABLE CONSTRAINT FK01_PODMO_LEGACYRECNUM;
ALTER TABLE SAP_DEL_PODMO DISABLE CONSTRAINT FK01_PODMO_SPID;

ALTER TABLE SAP_DEL_COBMO DISABLE CONSTRAINT FK01_COBMO_LEGACYRECNUM;
ALTER TABLE SAP_DEL_PREM DISABLE CONSTRAINT FK01_PREM_LEGACYRECNUM;

ALTER TABLE SAP_DEL_DEVMO DISABLE CONSTRAINT FK01_DMO_LEGACYRECNUM;
ALTER TABLE SAP_DEL_DEVCHAR DISABLE CONSTRAINT FK01_DEC_LEGACYRECNUM;
ALTER TABLE SAP_DEL_DVLCRT DISABLE CONSTRAINT FK01_DLC_LEGACYRECNUM;
ALTER TABLE SAP_DEL_DVLCRT DISABLE CONSTRAINT FK02_DLC_LEGACYRECNUM;
ALTER TABLE SAP_DEL_DVLUPDATE DISABLE CONSTRAINT FK01_DLU_LEGACYRECNUM;

ALTER TABLE SAP_DEL_METER_READ DISABLE CONSTRAINT FK02_DEV_LEGACYRECNUM;

--ALTER TABLE SAP_DEL_SCMMO DISABLE CONSTRAINT FK01_SCMMO_LEGACYKEY;
--ALTER TABLE SAP_DEL_SCMTE DISABLE CONSTRAINT FK01_SCMTE_LEGACYKEY;
--ALTER TABLE SAP_DEL_SCMTEMO DISABLE CONSTRAINT FK01_SCMTED_LEGACYKEY;

ALTER TABLE SAP_DEL_METER_INSTALL DISABLE CONSTRAINT FK03_DEV_LEGACYRECNUM;
--ALTER TABLE SAP_DEL_METER_INSTALL DISABLE CONSTRAINT FK01_COM_LEGACYRECNUM;


-- TRUNCATE TABLES
--TRUNCATE TABLE SAP_DEL_OUTPUT;
--
--TRUNCATE TABLE SAP_DEL_REG;
--TRUNCATE TABLE SAP_DEL_BP;
--
--TRUNCATE TABLE SAP_DEL_PODSRV;
--TRUNCATE TABLE SAP_DEL_PODMO;
--TRUNCATE TABLE SAP_DEL_POD;
--
--TRUNCATE TABLE SAP_DEL_METER_INSTALL;
--TRUNCATE TABLE SAP_DEL_METER_READ;
--
--TRUNCATE TABLE SAP_DEL_DVLUPDATE;
--TRUNCATE TABLE SAP_DEL_DVLCRT;
--TRUNCATE TABLE SAP_DEL_DEVCHAR;
--TRUNCATE TABLE SAP_DEL_DEVMO;
--TRUNCATE TABLE SAP_DEL_DEV;
--
--TRUNCATE TABLE SAP_DEL_SCMTEMO;
--TRUNCATE TABLE SAP_DEL_SCMTE;
--TRUNCATE TABLE SAP_DEL_SCMMO;
--TRUNCATE TABLE SAP_DEL_SCM;
--
--TRUNCATE TABLE SAP_DEL_PREM;
--TRUNCATE TABLE SAP_DEL_COBMO;
--TRUNCATE TABLE SAP_DEL_COB;

-- DROP TABLES
DROP TABLE SAP_DEL_OUTPUT;

DROP TABLE SAP_DEL_REG;
DROP TABLE SAP_DEL_BP;

DROP TABLE SAP_DEL_PODSRV;
DROP TABLE SAP_DEL_PODMO;
DROP TABLE SAP_DEL_POD;

DROP TABLE SAP_DEL_METER_INSTALL;
DROP TABLE SAP_DEL_METER_READ;

DROP TABLE SAP_DEL_DVLUPDATE;
DROP TABLE SAP_DEL_DVLCRT;
DROP TABLE SAP_DEL_DEVCHAR;
DROP TABLE SAP_DEL_DEVMO;
DROP TABLE SAP_DEL_DEV;

DROP TABLE SAP_DEL_SCMTEMO;
DROP TABLE SAP_DEL_SCMTE;
DROP TABLE SAP_DEL_SCMMO;
DROP TABLE SAP_DEL_SCM;

DROP TABLE SAP_DEL_PREM;
DROP TABLE SAP_DEL_COBMO;
DROP TABLE SAP_DEL_COB;

DROP TABLE LU_SAP_SENSITIVITY_CODES;

-- DROP ARCHIVE TABLES
DROP TABLE SAP_DEL_REG_ARC;
DROP TABLE SAP_DEL_BP_ARC;

DROP TABLE SAP_DEL_PODSRV_ARC;
DROP TABLE SAP_DEL_PODMO_ARC;
DROP TABLE SAP_DEL_POD_ARC;

DROP TABLE SAP_DEL_METER_INSTALL_ARC;
DROP TABLE SAP_DEL_METER_READ_ARC;

DROP TABLE SAP_DEL_DVLUPDATE_ARC;
DROP TABLE SAP_DEL_DVLCRT_ARC;
DROP TABLE SAP_DEL_DEVCHAR_ARC;
DROP TABLE SAP_DEL_DEVMO_ARC;
DROP TABLE SAP_DEL_DEV_ARC;

DROP TABLE SAP_DEL_SCMTEMO_ARC;
DROP TABLE SAP_DEL_SCMTE_ARC;
DROP TABLE SAP_DEL_SCMMO_ARC;
DROP TABLE SAP_DEL_SCM_ARC;

DROP TABLE SAP_DEL_PREM_ARC;
DROP TABLE SAP_DEL_COBMO_ARC;
DROP TABLE SAP_DEL_COB_ARC;

-- ENABLE FOREIGN KEYS
--ALTER TABLE SAP_DEL_REG ENABLE CONSTRAINT FK04_DEV_LEGACYRECNUM;
--
--ALTER TABLE SAP_DEL_PODSRV ENABLE CONSTRAINT FK01_PODSRV_SPID;
--ALTER TABLE SAP_DEL_PODMO ENABLE CONSTRAINT FK01_PODMO_LEGACYRECNUM;
--ALTER TABLE SAP_DEL_PODMO ENABLE CONSTRAINT FK01_PODMO_SPID;
--
--ALTER TABLE SAP_DEL_COBMO ENABLE CONSTRAINT FK01_COBMO_LEGACYRECNUM;
--ALTER TABLE SAP_DEL_PREM ENABLE CONSTRAINT FK01_PREM_LEGACYRECNUM;
--
--ALTER TABLE SAP_DEL_DEVMO ENABLE CONSTRAINT FK01_DMO_LEGACYRECNUM;
--ALTER TABLE SAP_DEL_DEVCHAR ENABLE CONSTRAINT FK01_DEC_LEGACYRECNUM;
--ALTER TABLE SAP_DEL_DVLCRT ENABLE CONSTRAINT FK01_DLC_LEGACYRECNUM;
--ALTER TABLE SAP_DEL_DVLCRT ENABLE CONSTRAINT FK02_DLC_LEGACYRECNUM;
--ALTER TABLE SAP_DEL_DVLUPDATE ENABLE CONSTRAINT FK01_DLU_LEGACYRECNUM;
--
--ALTER TABLE SAP_DEL_METER_READ ENABLE CONSTRAINT FK02_DEV_LEGACYRECNUM;
--
--ALTER TABLE SAP_DEL_SCMMO ENABLE CONSTRAINT FK01_SCMMO_LEGACYKEY;
--ALTER TABLE SAP_DEL_SCMTE ENABLE CONSTRAINT FK01_SCMTE_LEGACYKEY;
--ALTER TABLE SAP_DEL_SCMTEMO ENABLE CONSTRAINT FK01_SCMTED_LEGACYKEY;
--
--ALTER TABLE SAP_DEL_METER_INSTALL ENABLE CONSTRAINT FK03_DEV_LEGACYRECNUM;
--ALTER TABLE SAP_DEL_METER_INSTALL ENABLE CONSTRAINT FK01_COM_LEGACYRECNUM;
--Drop Procedures
Drop PROCEDURE P_SAP_DEL_UTIL_WRITE_FILE;
Drop PROCEDURE P_SAP_DEL_COB;
Drop PROCEDURE P_SAP_DEL_UTIL_ARCHIVE_TABLE;
Drop PROCEDURE P_SAP_DEL_DEV;
Drop PROCEDURE P_SAP_DEL_POD;
Drop PROCEDURE P_MIG_BATCH;
Drop PROCEDURE P_MIG_BATCH;
Drop PROCEDURE FN_VALIDATE_POSTCODE;
Drop PROCEDURE P_SAP_DEL_METER_READ;
Drop PROCEDURE P_SAP_DEL_POD_MO;
Drop PROCEDURE P_SAP_DEL_POD_SRV;
Drop PROCEDURE P_SAP_DEL_DEVMO;
Drop PROCEDURE P_SAP_DEL_DEVCHAR;
Drop PROCEDURE P_SAP_DEL_DVLUPDATE;
Drop PROCEDURE P_SAP_DEL_DVLCRT;
Drop PROCEDURE P_SAP_DEL_COB_MO;
Drop PROCEDURE P_SAP_DEL_PREM;
Drop PROCEDURE P_SAP_DEL_METER_INSTALL;
Drop PROCEDURE P_SAP_DEL_SCM_MO;
Drop PROCEDURE P_SAP_DEL_SCM;
Drop PROCEDURE P_SAP_DEL_SCM_TE;
Drop PROCEDURE P_SAP_DEL_SCM_TE_MO;
Drop PROCEDURE P_MOU_DEL_TARIFF_EXPORT;
Drop PROCEDURE P_SAP_DEL_REG;
Drop PROCEDURE P_SAP_DEL_BP;
DROP PROCEDURE P_SAP_DEL_UTIL_REF_DATA;
COMMIT;

--DROP FUNCTIONS
DROP FUNCTION FN_VALIDATE_POSTCODE;

--DROP PACKAGES
DROP PACKAGE P_MIG_BATCH;
COMMIT;

exit;
