-- Subversion $Revision: 4023 $
--
--Truncate DEL tables
TRUNCATE TABLE DEL_SERVICE_COMPONENT;
TRUNCATE TABLE DEL_METER;
TRUNCATE TABLE DEL_METER_SUPPLY_POINT;
TRUNCATE TABLE DEL_METER_NETWORK;
TRUNCATE TABLE DEL_METER_READING;
TRUNCATE TABLE DEL_DISCHARGE_POINT;
TRUNCATE TABLE DEL_METER_DISCHARGE_POINT;
TRUNCATE TABLE DEL_CALCULATED_DISCHARGE;
TRUNCATE TABLE DEL_SUPPLY_POINT;
--TRUNCATE TABLE DEL_SUPPLY_POINT_ARC;
--TRUNCATE TABLE DEL_SERVICE_COMPONENT_ARC;
--TRUNCATE TABLE DEL_METER_ARC;
--TRUNCATE TABLE DEL_METER_SUPPLY_POINT_ARC;
--TRUNCATE TABLE DEL_METER_NETWORK_ARC;
--TRUNCATE TABLE DEL_METER_READING_ARC;
--TRUNCATE TABLE DEL_DISCHARGE_POINT_ARC;
--TRUNCATE TABLE DEL_METER_DISCHARGE_POINT_ARC;
--TRUNCATE TABLE DEL_CALCULATED_DISCHARGE_ARC;


-- Execute the main batch
set serveroutput on;
exec  P_MIG_BATCH.P_STARTBATCH();
set serveroutput off;
exit;
