-- Author	N.Henderson
-- Version	0.1
-- Subversion $Revision: 4023 $
-- Notes	Initial build


--DROP AUTONUNUMBER SEQUENCES

--MO_TARIFF_VERSION
DROP SEQUENCE TARIFF_VERSION_PK_SEQ;
--MO_SERVICE_COMPONENT_TYPE
DROP SEQUENCE SERVICECOMPONENT_PK_SEQ ;
--MO_SERVICE_COMPONENT_VOL_ADJ
DROP SEQUENCE ADJVOLADJUNIQREF_PK_SEQ ;
--MO_CALCULATED_DISCHARGE
DROP SEQUENCE CALCDISCHARGEID_PK_SEQ ;
--MO_DISCHARGED_VOLUME
DROP SEQUENCE DISCHARGEVOLUME_PK_SEQ ;
--MO_DISCHARGE_POINT_VOLMET_ADJ
DROP SEQUENCE DISCHARGEPOINTVOLMETADJ_PK_SEQ ;
--MO_METER_READING
DROP SEQUENCE METER_READING_PK_SEQ ;
--MO_METER_DPIDXREF
DROP SEQUENCE METERDPIDXREF_PK_SEQ ;
--MO_CUST_ADDRESS
DROP SEQUENCE ADDRCUSTPROPERTY_PK_SEQ ;
--MO_PROPERTY_ADDRESS
DROP SEQUENCE ADDRESSPROPERTY_PK_SEQ ;
--MO_METER_ADDRESS
DROP SEQUENCE ADDRMETERROPERTY_PK_SEQ ;
--MO_ADDRESS
DROP SEQUENCE ADDRESS_PK_SEQ ;
--MO_TARIFF_TYPE_MPW
DROP SEQUENCE MPW_TARIFF_TYPE_PK_SEQ ;
--MO_MPW_METER_MWMFC
DROP SEQUENCE MPW_TARIFF_MWMFC_PK_SEQ ;
--MO_MPW_BLOCK_MWBT
DROP SEQUENCE MPW_TARIFF_MWBT_PK_SEQ ;
--MO_MPW_STANDBY_MWCAPCHG
DROP SEQUENCE MPW_TARIFF_MWCAPCHG_PK_SEQ ;
--MO_TARIFF_TYPE_MNPW
DROP SEQUENCE MNPW_TARIFF_TYPE_PK_SEQ ;
--MO_MNPW_METER_MWMFC
DROP SEQUENCE MNPW_TARIFF_MWMFC_PK_SEQ ;
--MO_MNPW_BLOCK_MWBT
DROP SEQUENCE MNPW_TARIFF_MWBT_PK_SEQ ;
--MO_MNPW_STANDBY_MWCAPCHG
DROP SEQUENCE MNPW_TARIFF_MWCAPCHG_PK_SEQ ;
--MO_TARIFF_TYPE_AW
DROP SEQUENCE AW_TARIFF_TYPE_PK_SEQ ;
--MO_AW_METER_AWMFC
DROP SEQUENCE AW_TARIFF_AWMFC_PK_SEQ ;
--MO_AW_BAND_CHARGE
DROP SEQUENCE AW_TARIFF_BAND_CHARGE_PK_SEQ ;
--MO_TARIFF_TYPE_UW
DROP SEQUENCE UW_TARIFF_TYPE_PK_SEQ ;
--MO_UW_METER_UWPFC
DROP SEQUENCE UW_TARIFF_UWPFC_PK_SEQ ;
--MO_TARIFF_TYPE_MS
DROP SEQUENCE MS_TARIFF_TYPE_PK_SEQ ;
--MO_MS_BLOCK_MSBT
DROP SEQUENCE MS_TARIFF_MWBT_PK_SEQ ;
--MO_MS_METER_MSMFC
DROP SEQUENCE MS_TARIFF_MSMFC_PK_SEQ ;
--MO_TARIFF_TYPE_AS
DROP SEQUENCE AS_TARIFF_TYPE_PK_SEQ ;
--MO_AS_METER_ASMFC
DROP SEQUENCE AS_TARIFF_ASMFC_PK_SEQ ;
--MO_AS_BAND_CHARGE
DROP SEQUENCE AS_TARIFF_BAND_CHARGE_PK_SEQ ;
--MO_TARIFF_TYPE_US
DROP SEQUENCE US_TARIFF_TYPE_PK_SEQ ;
--MO_US_METER_USPFC
DROP SEQUENCE US_TARIFF_USPFC_PK_SEQ ;
--MO_TARIFF_TYPE_SW
DROP SEQUENCE SW_TARIFF_TYPE_PK_SEQ ;
--MO_SW_AREA_BAND
DROP SEQUENCE SW_TARIFF_AREA_BAND_PK_SEQ ;
--MO_SW_BAND_CHARGE
DROP SEQUENCE SW_TARIFF_BAND_CHARGE_PK_SEQ ;
--MO_SW_BLOCK_SWBT
DROP SEQUENCE SW_TARIFF_SWBT_PK_SEQ ;
--MO_SW_METER_SWMFC
DROP SEQUENCE SW_TARIFF_SWMFC_PK_SEQ ;
--MO_TARIFF_TYPE_HD
DROP SEQUENCE HD_TARIFF_TYPE_PK_SEQ ;
--MO_HD_AREA_BAND
DROP SEQUENCE HD_TARIFF_AREA_BAND_PK_SEQ ;
--MO_HD_BAND_CHARGE
DROP SEQUENCE HD_TARIFF_BAND_CHARGE_PK_SEQ ;
--MO_HD_BLOCK_HDBT
DROP SEQUENCE HD_TARIFF_HDBT_PK_SEQ ;
--MO_HD_METER_HDMFC
DROP SEQUENCE HD_TARIFF_HDMFC_PK_SEQ ;
--MO_TARIFF_TYPE_TE
DROP SEQUENCE TE_TARIFF_TYPE_PK_SEQ ;
--MO_TE_BAND_CHARGE
DROP SEQUENCE TE_TARIFF_BAND_CHARGE_PK_SEQ ;
--MO_TE_BLOCK_ROBT
DROP SEQUENCE TE_TARIFF_ROBT_PK_SEQ ;
--MO_TE_BLOCK_BOBT
DROP SEQUENCE TE_TARIFF_BOBT_PK_SEQ ;
commit;
exit;
