--N.Henderson
--19/04/2016
--Subversion $Revision: 4023 $
--Drop new TARIFF tables

DROP TABLE MO_TARIFF_TYPE_SCA;
DROP TABLE MO_TARIFF_TYPE_WCA;
DROP TABLE MO_TARIFF_STANDING_DATA;
DROP TABLE HD_STG;
DROP TABLE MPW_STG;
DROP TABLE UW_STG;
DROP TABLE TE_STG;
DROP TABLE SW_STG;
DROP TABLE AS_STG;
DROP TABLE US_STG;
DROP TABLE AW_STG;
DROP TABLE MS_STG;
commit;
exit;