------------------------------------------------------------------------------
-- TASK					: 	MOSL RDBMS CREATION 
--
-- AUTHOR         		: 	Nigel Henderson
--
-- FILENAME       		: 	01_DDL_MOSL_TABLES_ALL.sql
--
-- CREATED        		: 	22/02/2016
--	
-- Subversion $Revision: 4813 $
--
-- DESCRIPTION 		   	: 	Creates all core and tariff tables for the MOSL database
--
-- NOTES  				:	Used in conjunction with the following scripts to re-initialise the
-- 							database.  When re-creating the database run the scripts in order
-- 							as detailed below (.sql).
--
-- ASSOCIATED FILES		:	MOSL_PDM_CORE.xlsm
-- ASSOCIATED SCRIPTS  	:	02_DDL_MOSL_PK_ALL.sql
--							03_DDL_MOSL_FK_ALL.sql
--							04_DDL_MOSL_STATIC_DATA_ALL.sql
--							05_COMMENTS_TABLES_FIELDS_ALL
--
--
--
--
--
---------------------------- Modification History ----------------------------------------------------------
--
-- Version     		Date          Author         		Description
-- ---------      	---------------     -------            	 ------------------------------------------------
-- V0.01       	15/02/2016    	N.Henderson     	Initial version after generation from Excel
-- V0.02		25/02/2016		N.Henderson		Had to replace all comments symbols with --
--									Doing something wierd when running query from
--									command line.
-- V0.03 		15/03/2016		N.Henderson 		Updates to check constraints, human readable names for constraints
-- V0.04 		12/07/2016		M.Marron        I-290 updated Tariffstatus
--
--
--
--
-- 
------------------------------------------------------------------------------------------------------------
--MO_CUSTOMER

--CREATE_TABLE_DDL--
--MO_CUSTOMER--
CREATE TABLE MO_CUSTOMER
(
CUSTOMERNUMBER_PK NUMBER(9) ,
STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CH01_STWPROPERTYNUMBER NOT NULL,
COMPANIESHOUSEREFNUM VARCHAR(20) ,
CUSTOMERCLASSIFICATION VARCHAR(5) CONSTRAINT CH01_CUSTOMERCLASSIFICATION NOT NULL,
CUSTOMERNAME VARCHAR(255) CONSTRAINT CH01_CUSTOMERNAME NOT NULL,
CUSTOMERBANNERNAME VARCHAR(255) ,
STDINDUSTRYCLASSCODE VARCHAR(12) ,
STDINDUSTRYCLASSCODETYPE VARCHAR(4) 
);
--MO_ELIGIBLE_PREMISES--
CREATE TABLE MO_ELIGIBLE_PREMISES
(
STWPROPERTYNUMBER_PK NUMBER(9) ,
CORESPID_PK VARCHAR(10) ,
CUSTOMERID_PK NUMBER(9) CONSTRAINT CH01_CUSTOMERID NOT NULL,
SAPFLOCNUMBER NUMBER(30) CONSTRAINT CH01_SAPFLOCNUMBER NOT NULL,
RATEABLEVALUE NUMBER(10,2) ,
PROPERTYUSECODE VARCHAR(1) CONSTRAINT CH01_PROPERTYUSECODE NOT NULL,
OCCUPENCYSTATUS VARCHAR(12) CONSTRAINT CH01_OCCUPENCYSTATUS NOT NULL,
VOABAREFERENCE VARCHAR(32) ,
VOABAREFRSNCODE VARCHAR(2) ,
BUILDINGWATERSTATUS NUMBER(1) CONSTRAINT CH01_BUILDINGWATERSTATUS NOT NULL,
NONPUBHEALTHRELSITE  NUMBER(1) CONSTRAINT CH01_NONPUBHEALTHRELSITE  NOT NULL,
NONPUBHEALTHRELSITEDSC VARCHAR(255) ,
PUBHEALTHRELSITEARR NUMBER(1) CONSTRAINT CH01_PUBHEALTHRELSITEARR NOT NULL,
SECTION154 NUMBER(4) ,
UPRN NUMBER(13) ,
UPRNREASONCODE VARCHAR(2) 
);
--MO_SUPPLY_POINT--
CREATE TABLE MO_SUPPLY_POINT
(
SPID_PK VARCHAR(13) ,
STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CH02_STWPROPERTYNUMBER NOT NULL,
CORESPID_PK VARCHAR(10) CONSTRAINT CH01_CORESPID NOT NULL,
RETAILERID_PK VARCHAR(12) CONSTRAINT CH01_RETAILERID NOT NULL,
WHOLESALERID_PK VARCHAR(12) CONSTRAINT CH01_WHOLESALERID NOT NULL,
CUSTOMERNUMBER_PK NUMBER(9) ,
SAPFLOCNUMBER NUMBER(30) ,
SERVICECATEGORY VARCHAR(1) CONSTRAINT CH01_SERVICECATEGORY NOT NULL,
SUPPLYPOINTEFFECTIVEFROMDATE DATE ,
REGISTRATIONSTARTDATE DATE ,
DISCONRECONDEREGSTATUS VARCHAR(5) ,
OTHERSERVICECATPROVIDED NUMBER(1) ,
OTHERSERVICECATPROVIDEDREASON VARCHAR(2) ,
MULTIPLEWHOLESALERFLAG NUMBER(1) CONSTRAINT CH01_MULTIPLEWHOLESALERFLAG NOT NULL,
LANDLORDSPID VARCHAR(32) ,
SPIDSTATUS VARCHAR(9) CONSTRAINT CH06_SPIDSTATUS NOT NULL,
NEWCONNECTIONTYPE VARCHAR(3) ,
ACCREDITEDENTITYFLAG NUMBER(1) CONSTRAINT CH01_ACCREDITEDENTITYFLAG NOT NULL,
GAPSITEALLOCATIONMETHOD VARCHAR(4) ,
OTHERSPID VARCHAR(12) ,
OTHERWHOLESALERID VARCHAR(12) ,
PAIRINGREFREASONCODE VARCHAR(12) ,
LATEREGAPPLICATION NUMBER(1) CONSTRAINT CH01_LATEREGAPPLICATION NOT NULL,
VOLTRANSFERFLAG NUMBER(1) CONSTRAINT CH01_VOLTRANSFERFLAG NOT NULL,
SUPPLYPOINTREFERENCE VARCHAR(32) CONSTRAINT CH01_SUPPLYPOINTREFERENCE NOT NULL
);
--MO_ORG--
CREATE TABLE MO_ORG
(
ORGID_PK VARCHAR(12) ,
ORGNAME VARCHAR(128) CONSTRAINT CH01_ORGNAME NOT NULL,
ORGTYPE VARCHAR(128) CONSTRAINT CH01_ORGTYPE NOT NULL,
RETAILERTYPE VARCHAR(10) ,
INTERIMSUPPLIERALLOCSTATUS VARCHAR(8) ,
TRADINGPARTYSERVICECAT VARCHAR(32) ,
GAPSITEALLOCSTATUS VARCHAR(8) ,
DEFAULTRETURNTOSEWER NUMBER(2,2) ,
VACANCYCHARGINGMETHODWATER VARCHAR(3) ,
VACANCYCHARGINGMETHODSEWERAGE VARCHAR(3) ,
TMPDISCONCHRGMETHODWATER VARCHAR(3) ,
TMPDISCONCHRGMETHODSEWERAGE VARCHAR(3) ,
ALTERNATIVETARIFYEAR DATE, 
ORGDESCRIPTION VARCHAR2(255)
);
--MO_RETAILER_REGISTRATION--
CREATE TABLE MO_RETAILER_REGISTRATION
(
RETAILERID_PK VARCHAR(12) ,
SPID_PK VARCHAR(13) CONSTRAINT CH01_SPID NOT NULL,
REGISTRATIONSTARTDATE DATE CONSTRAINT CH01_REGISTRATIONSTARTDATE NOT NULL,
TRANSFERSTATUS VARCHAR(18) CONSTRAINT CH01_TRANSFERSTATUS NOT NULL,
REGISTRATIONTYPE VARCHAR(40) CONSTRAINT CH01_REGISTRATIONTYPE NOT NULL,
TRANFERREQUESTTIMESTAMP DATE CONSTRAINT CH01_TRANFERREQUESTTIMESTAMP NOT NULL,
TRANSFERREADREQUIREDBYDATE DATE CONSTRAINT CH01_TRANSFERREADREQUIREDDATE NOT NULL,
CANCELLATIONCODE VARCHAR(13) ,
TRANSFERCANCELREASON VARCHAR(12) ,
DATEOFINVOICEINDISPUTE DATE ,
TOTALAMOUNTOUTSTANDING NUMBER(5,2) ,
ORIGINALDUEDATEOFINVOICE DATE ,
DATEREMINDERSENT DATE ,
NEWDUEDATESETINREMINDER DATE ,
TRANSFERAPPLICATIONREASON VARCHAR(256) ,
TRANSFERVALIDFLAG NUMBER(1) ,
TRANSFERREJECTIONREASON VARCHAR(128) 
);
--MO_SERVICE_COMPONENT--
CREATE TABLE MO_SERVICE_COMPONENT
(
SERVICECOMPONENTREF_PK NUMBER(9) ,
TARIFFCODE_PK VARCHAR(32) CONSTRAINT CH01_TARIFFCODE NOT NULL,
SPID_PK VARCHAR(13) CONSTRAINT CH02_SPID NOT NULL,
DPID_PK VARCHAR(13) ,
STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CH03_STWPROPERTYNUMBER NOT NULL,
STWSERVICETYPE VARCHAR(5) CONSTRAINT CH01_STWSERVICETYPE NOT NULL,
SERVICECOMPONENTTYPE VARCHAR(4) CONSTRAINT CH01_SERVICECOMPONENTTYPE NOT NULL,
SERVICECOMPONENTENABLED NUMBER(1) ,
EFFECTIVEFROMDATE DATE ,
SPECIALAGREEMENTFACTOR NUMBER(2,2) ,
SPECIALAGREEMENTFLAG NUMBER(1) ,
SPECIALAGREEMENTREF VARCHAR(12) ,
METEREDFSMAXDAILYDEMAND VARCHAR(32) ,
METEREDPWMAXDAILYDEMAND NUMBER(12) ,
METEREDNPWMAXDAILYDEMAND NUMBER(12) ,
METEREDFSDAILYRESVDCAPACITY NUMBER(12) ,
METEREDNPWDAILYRESVDCAPACITY NUMBER(12) ,
METEREDFSTARIFFCODE VARCHAR(32) ,
METEREDNPWTARIFFCODE VARCHAR(32) ,
DAILYRESERVEDCAPACITY NUMBER(12) ,
METEREDPWTARIFFCODE VARCHAR(32) ,
HWAYSURFACEAREA NUMBER(12) ,
HWAYDRAINAGETARIFFCODE VARCHAR(32) ,
HWAYCOMMUNITYCONFLAG NUMBER(1) ,
ASSESSEDDVOLUMETRICRATE NUMBER(12) ,
ASSESSEDCHARGEMETERSIZE NUMBER(4) ,
ASSESSEDTARIFFCODE VARCHAR(32) ,
ASSESSEDTARIFBAND NUMBER(2) ,
SRFCWATERAREADRAINED NUMBER(12) ,
SRFCWATERTARRIFCODE VARCHAR(32) ,
SRFCWATERCOMMUNITYCONFLAG NUMBER(1) ,
UNMEASUREDTYPEACOUNT NUMBER(3) ,
UNMEASUREDTYPEBCOUNT NUMBER(3) ,
UNMEASUREDTYPECCOUNT NUMBER(3) ,
UNMEASUREDTYPEDCOUNT NUMBER(3) ,
UNMEASUREDTYPEECOUNT NUMBER(3) ,
UNMEASUREDTYPEFCOUNT NUMBER(3) ,
UNMEASUREDTYPEGCOUNT NUMBER(3) ,
UNMEASUREDTYPEHCOUNT NUMBER(3) ,
UNMEASUREDTYPEADESCRIPTION VARCHAR(255) ,
UNMEASUREDTYPEBDESCRIPTION VARCHAR(255) ,
UNMEASUREDTYPECDESCRIPTION VARCHAR(255) ,
UNMEASUREDTYPEDDESCRIPTION VARCHAR(255) ,
UNMEASUREDTYPEEDESCRIPTION VARCHAR(255) ,
UNMEASUREDTYPEFDESCRIPTION VARCHAR(255) ,
UNMEASUREDTYPEGDESCRIPTION VARCHAR(255) ,
UNMEASUREDTYPEHDESCRIPTION VARCHAR(255) ,
UNMEASUREDTARIFFCODE VARCHAR(32) 
);
--MO_SERVICE_COMPONENT_TYPE--
CREATE TABLE MO_SERVICE_COMPONENT_TYPE
(
SERVICECOMPONENT_PK NUMBER(9)  ,
SERVICECOMPONENTTYPE VARCHAR(4) CONSTRAINT CH02_SERVICECOMPONENTTYPE NOT NULL,
SERVICECOMPXREF VARCHAR(255) CONSTRAINT CH01_SERVICECOMPXREF NOT NULL,
VACANCYTEMPDISCONNPARAM VARCHAR(12) ,
CHARGINGELEMENT VARCHAR(16) ,
TARIFF VARCHAR(12) 
);
--MO_SERVICE_COMPONENT_VOL_ADJ--
CREATE TABLE MO_SERVICE_COMPONENT_VOL_ADJ
(
ADJUSTMENTSVOLADJUNIQREF_PK VARCHAR(16) ,
SERVICECOMPONENTREF_PK NUMBER(9) ,
ADJUSTMENTSVOLADJTYPE VARCHAR(16) ,
ADJUSTMENTSVOLUME NUMBER(12) ,
ADJUSTMENTSGOVTCONTRIB NUMBER(12) ,
ADJUSTMENTSCHARGEADJTARIFFCODE VARCHAR(32) 
);
--MO_DISCHARGE_POINT--
CREATE TABLE MO_DISCHARGE_POINT
(
DPID_PK VARCHAR(13)  ,
SPID_PK VARCHAR(13) CONSTRAINT CH03_SPID NOT NULL,
SERVICECOMPTYPE VARCHAR(12) CONSTRAINT CH01_SERVICECOMPTYPE NOT NULL,
SCEFFECTIVEFROMDATE DATE CONSTRAINT CH01_SCEFFECTIVEFROMDATE NOT NULL,
DPEFFECTFROMDATE DATE CONSTRAINT CH01_DPEFFECTFROMDATE NOT NULL,
DPEFFECTTODATE DATE ,
DISCHARGEPOINTERASEFLAG NUMBER(1) CONSTRAINT CH01_DISCHARGEPOINTERASEFLAG NOT NULL,
EFFECTFROMDATE DATE CONSTRAINT CH01_EFFECTFROMDATE NOT NULL,
EFFECTTODATE DATE ,
WHOLESALERID VARCHAR(12) CONSTRAINT CH02_WHOLESALERID NOT NULL,
TARRIFCODE VARCHAR(32) CONSTRAINT CH01_TARRIFCODE NOT NULL,
CHARGEABLEDAILYVOL NUMBER(12) ,
AMMONIANITROCAL NUMBER(12) ,
CHEMICALOXYGENDEMAND NUMBER(12) ,
SUSPENDEDSOLIDSLOAD NUMBER(12) ,
DOMMESTICALLOWANCE NUMBER(12) ,
SEASONALFACTOR NUMBER(2,2) ,
PERCENTAGEALLOWANCE NUMBER(2,2) CONSTRAINT CH01_PERCENTAGEALLOWANCE NOT NULL,
FIXEDALLOWANCE VARCHAR(12) CONSTRAINT CH01_FIXEDALLOWANCE NOT NULL,
RECEPTIONTREATMENTINDICATOR NUMBER(1) CONSTRAINT CH01_RECEPTIONTREATMENTIND NOT NULL,
PRIMARYTREATMENTINDICATOR NUMBER(1) CONSTRAINT CH01_PRIMARYTREATMENTINDICATOR NOT NULL,
MARINETREATMENTINDICATOR NUMBER(1) CONSTRAINT CH01_MARINETREATMENTINDICATOR NOT NULL,
BIOLOGICALTREATMENTINDICATOR NUMBER(1) CONSTRAINT CH01_BIOLOGICALTREATMENTIND NOT NULL,
SLUDGETREATMENTINDICATOR NUMBER(1) CONSTRAINT CH01_SLUDGETREATMENTINDICATOR NOT NULL,
AMMONIATREATMENTINDICATOR NUMBER(1) CONSTRAINT CH01_AMMONIATREATMENTINDICATOR NOT NULL,
TEFXTREATMENTINDICATOR NUMBER(1) CONSTRAINT CH01_TEFXTREATMENTINDICATOR NOT NULL,
TEFYTREATMENTINDICATOR NUMBER(1) CONSTRAINT CH01_TEFYTREATMENTINDICATOR NOT NULL,
TEFZTREATMENTINDICATOR NUMBER(1) CONSTRAINT CH01_TEFZTREATMENTINDICATOR NOT NULL,
TEFAVAILABILITYDATAX NUMBER(9) ,
TEFAVAILABILITYDATAY NUMBER(9) ,
TEFAVAILABILITYDATAZ NUMBER(9) ,
TARRIFBAND NUMBER(2) ,
SEWERAGEVOLUMEADJMENTHOD VARCHAR(8) CONSTRAINT CH01_SEWERAGEVOLUMEADJMENTHOD NOT NULL,
SECONDADDRESSABLEOBJ VARCHAR(100) ,
PRIMARYADDRESSABLEOBJ VARCHAR(100) ,
TREFODCHEMOXYGENDEMAND NUMBER(9) CONSTRAINT CH01_TREFODCHEMOXYGENDEMAND NOT NULL,
TREFODCHEMSUSPSOLDEMAND NUMBER(9) CONSTRAINT CH01_TREFODCHEMSUSPSOLDEMAND NOT NULL,
TREFODCHEMAMONIANITROGENDEMAND NUMBER(9) ,
TREFODCHEMCOMPXDEMAND NUMBER(9) ,
TREFODCHEMCOMPYDEMAND NUMBER(9) ,
TREFODCHEMCOMPZDEMAND NUMBER(9) ,
DPIDSPECIALAGREEMENTINPLACE NUMBER(1) CONSTRAINT CH01_DPIDSPECIALAGREEMENT NOT NULL,
DPIDSPECIALAGREEMENTFACTOR NUMBER(2,2) ,
DPIDSPECIALAGREEMENTREFERENCE VARCHAR(12) 
);
--MO_CALCULATED_DISCHARGE--
CREATE TABLE MO_CALCULATED_DISCHARGE
(
CALCDISCHARGEID_PK VARCHAR(12)  ,
DPID_PK VARCHAR(13) CONSTRAINT CH01_DPID NOT NULL,
DPEFFECTFROMDATE DATE CONSTRAINT CH02_DPEFFECTFROMDATE NOT NULL,
EFFECTFROMDATE DATE CONSTRAINT CH02_EFFECTFROMDATE NOT NULL,
EFFECTTODATE DATE ,
DISCHARGETYPE VARCHAR(12) CONSTRAINT CH01_DISCHARGETYPE NOT NULL,
SUBMISSIONFREQ VARCHAR(1) CONSTRAINT CH01_SUBMISSIONFREQ NOT NULL,
TEYEARLYVOLESTIMATE NUMBER(13) CONSTRAINT CH01_TEYEARLYVOLESTIMATE NOT NULL
);
--MO_DISCHARGED_VOLUME--
CREATE TABLE MO_DISCHARGED_VOLUME
(
DISCHARGEVOLUME_PK NUMBER(12)  ,
DPID_PK VARCHAR(13) CONSTRAINT CH02_DPID NOT NULL,
DPEFFECTFROMDATE DATE CONSTRAINT CH03_DPEFFECTFROMDATE NOT NULL,
EFFECTFROMDATE DATE CONSTRAINT CH03_EFFECTFROMDATE NOT NULL,
EFFECTTODATE DATE CONSTRAINT CH01_EFFECTTODATE NOT NULL,
NOTIFIEDVOLUME NUMBER(12) CONSTRAINT CH01_NOTIFIEDVOLUME NOT NULL
);
--MO_DISCHARGE_POINT_VOLMET_ADJ--
CREATE TABLE MO_DISCHARGE_POINT_VOLMET_ADJ
(
DISCHARGEPOINTVOLMETADJ_PK NUMBER(12)  ,
DPID_PK VARCHAR(13) CONSTRAINT CH03_DPID NOT NULL,
DPEFFECTFROMDATE DATE CONSTRAINT CH04_DPEFFECTFROMDATE NOT NULL,
EFFECTFROMDATE DATE CONSTRAINT CH04_EFFECTFROMDATE NOT NULL,
EFFECTTODATE DATE CONSTRAINT CH02_EFFECTTODATE NOT NULL,
ADJUSTMENTSVOLADJTYPE VARCHAR(16) ,
ADJUSTMENTSVOLADJUNIQREF VARCHAR(16) ,
ADJUSTMENTSVOLUME NUMBER(12) 
);
--MO_METER--
CREATE TABLE MO_METER
(
MANUFACTURER_PK VARCHAR(32)  ,
MANUFACTURERSERIALNUM_PK VARCHAR(32) ,
SPID_PK VARCHAR(13) CONSTRAINT CH04_SPID NOT NULL,
INITIALMETERREADDATE DATE ,
METERERASEDFLAG NUMBER(1) CONSTRAINT CH01_METERERASEDFLAG NOT NULL,
NONMARKETMETERFLAG NUMBER(1) CONSTRAINT CH01_NONMARKETMETERFLAG NOT NULL,
WHOLESALERID VARCHAR(12) CONSTRAINT CH03_WHOLESALERID NOT NULL,
INSTALLEDBYACCREDITEDENTITY NUMBER(1) CONSTRAINT CH01_INSTALLEDBYACCREDITEDENT NOT NULL,
NUMBEROFDIGITS NUMBER(1) CONSTRAINT CH01_NUMBEROFDIGITS NOT NULL,
METERTREATMENT VARCHAR(32) CONSTRAINT CH01_METERTREATMENT NOT NULL,
MEASUREUNITFREEDESCRIPTOR VARCHAR(255) ,
MEASUREUNITFREEATMETER VARCHAR(122) CONSTRAINT CH01_MEASUREUNITFREEATMETER NOT NULL,
METERADDITIONREASON VARCHAR(8) CONSTRAINT CH01_METERADDITIONREASON NOT NULL,
METERREMOVALREASON VARCHAR(8) ,
EFFECTIVEFROMDATE DATE CONSTRAINT CH01_EFFECTIVEFROMDATE NOT NULL,
EFFECTIVETODATE DATE ,
METERREADMINFREQUENCY VARCHAR(1) CONSTRAINT CH01_METERREADMINFREQUENCY NOT NULL,
PHYSICALMETERSIZE NUMBER(4) ,
DATALOGGERWHOLESALER NUMBER(1) CONSTRAINT CH01_DATALOGGERWHOLESALER NOT NULL,
DATALOGGERNONWHOLESALER NUMBER(1) CONSTRAINT CH01_DATALOGGERNONWHOLESALER NOT NULL,
GPSX NUMBER(6,1) ,
GPSY NUMBER(6,1) ,
METERLOCATIONCODE VARCHAR(1) CONSTRAINT CH01_METERLOCATIONCODE NOT NULL,
METEROUTREADERGPSX NUMBER(6,1) ,
METEROUTREADERGPSY NUMBER(7,1) ,
METEROUTREADERLOCCODE VARCHAR(1) ,
COMBIMETERFLAG NUMBER(1) CONSTRAINT CH01_COMBIMETERFLAG NOT NULL,
REMOTEREADFLAG NUMBER(1) CONSTRAINT CH01_REMOTEREADFLAG NOT NULL,
REMOTEREADTYPE VARCHAR(12) ,
OUTREADERID VARCHAR(32) ,
OUTREADERPROTOCOL VARCHAR(255) ,
FREEDESCRIPTION VARCHAR(255) ,
SECADDRESSABLEOBJ VARCHAR(100) ,
PRIMADDRESSABLEOBJ VARCHAR(100) ,
ADDRESSLINE01 VARCHAR(60) CONSTRAINT CH01_ADDRESSLINE01 NOT NULL,
ADDRESSLINE02 VARCHAR(60) ,
ADDRESSLINE03 VARCHAR(60) ,
ADDRESSLINE04 VARCHAR(60) ,
ADDRESSLINE05 VARCHAR(60) ,
POSTCODE VARCHAR(8) CONSTRAINT CH01_POSTCODE NOT NULL,
COUNTRY VARCHAR(32) ,
PAFADDRESSKEY NUMBER(9) ,
WATERCHARGEMETERSIZE NUMBER(4) CONSTRAINT CH01_WATERCHARGEMETERSIZE NOT NULL,
RETURNTOSEWER NUMBER(2,2) ,
SEWCHARGEABLEMETERSIZE NUMBER(4) ,
METERLOCFREEDESCRIPTOR VARCHAR(255) ,
METEROUTREADLOCFREEDESCRIPTOR VARCHAR(255) ,
MAINMETERMANUFACTURER VARCHAR(32) CONSTRAINT CH01_MAINMETERMANUFACTURER NOT NULL,
MAINMETERMANUFACTURERSERIALNUM VARCHAR(32) CONSTRAINT CH01_MAINMETERMANUFACSERIAL NOT NULL,
MAINMETERINITIALMETERREADDATE DATE ,
YEARLYVOLESTIMATE NUMBER(13) 
);
--MO_METER_READING--
CREATE TABLE MO_METER_READING
(
METER_READING_PK NUMBER(12)  ,
MANUFACTURER_PK VARCHAR(32) CONSTRAINT CH01_MANUFACTURER NOT NULL,
MANUFACTURERSERIALNUM_PK VARCHAR(32) CONSTRAINT CH01_MANUFACTURERSERIALNUM NOT NULL,
INITIALMETERREADDATE DATE ,
METERREADDATE DATE CONSTRAINT CH01_METERREADDATE NOT NULL,
METERREAD NUMBER(12) ,
METERREADTYPE VARCHAR(1) ,
METERREADMETHOD VARCHAR(9) ,
REREADFLAG NUMBER(1) ,
ROLLOVERINDICATOR NUMBER(1) CONSTRAINT CH01_ROLLOVERINDICATOR NOT NULL,
ROLLOVERFLAG NUMBER(1) ,
RDAOUTCOME VARCHAR(32) ,
ESTIMATEDREADREASONCODE VARCHAR(2) ,
ESTIMATEDREADREMEDIALWORKIND NUMBER(1) ,
METERREADSTATUS VARCHAR(32) ,
METERREADERASEDFLAG NUMBER(1) ,
METERREADREASONTYPE VARCHAR(20) ,
METERREADSETTLEMENTFLAG NUMBER(1) ,
PREVVALCDVCANDIDATEDAILYVOLUME NUMBER(9) 
);
--MO_METER_DPIDXREF--
CREATE TABLE MO_METER_DPIDXREF
(
METERDPIDXREF_PK NUMBER(12)  ,
MANUFACTURER_PK VARCHAR(32) CONSTRAINT CH02_MANUFACTURER NOT NULL,
MANUFACTURERSERIALNUM_PK VARCHAR(32) CONSTRAINT CH02_MANUFACTURERSERIALNUM NOT NULL,
DPID_PK VARCHAR(13) CONSTRAINT CH04_DPID NOT NULL,
INITIALMETERREADDATE DATE ,
SPID VARCHAR(13) CONSTRAINT CH05_SPID NOT NULL,
DPEFFECTFROMDATE DATE ,
EFFECTIVEFROMDATE DATE ,
EFFECTIVETODATE DATE ,
PERCENTAGEDISCHARGE NUMBER(2,2) 
);
--MO_CUST_ADDRESS--
CREATE TABLE MO_CUST_ADDRESS
(
ADDRESSPROPERTY_PK NUMBER(9)  ,
ADDRESS_PK NUMBER(9) CONSTRAINT CH01_ADDRESS NOT NULL,
CUSTOMERNUMBER_PK NUMBER(9) CONSTRAINT CH01_CUSTOMERNUMBER NOT NULL,
ADDRESSUSAGEPROPERTY VARCHAR(1) ,
EFFECTIVEFROMDATE DATE ,
EFFECTIVETODATE DATE,
STWPROPERTYNUMBER_PK NUMBER(9) 
);
--MO_PROPERTY_ADDRESS--
CREATE TABLE MO_PROPERTY_ADDRESS
(
ADDRESSPROPERTY_PK NUMBER(9)  ,
ADDRESS_PK NUMBER(9) CONSTRAINT CH02_ADDRESS NOT NULL,
STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CH04_STWPROPERTYNUMBER NOT NULL,
ADDRESSUSAGEPROPERTY VARCHAR(1) ,
EFFECTIVEFROMDATE DATE ,
EFFECTIVETODATE DATE 
);
--MO_METER_ADDRESS--
CREATE TABLE MO_METER_ADDRESS
(
ADDRESSPROPERTY_PK NUMBER(9)  ,
METERSERIALNUMBER_PK VARCHAR(32) CONSTRAINT CH01_METERSERIALNUMBER NOT NULL,
ADDRESS_PK NUMBER(9) CONSTRAINT CH03_ADDRESS NOT NULL,
ADDRESSUSAGEPROPERTY VARCHAR(1) ,
EFFECTIVEFROMDATE DATE ,
EFFECTIVETODATE DATE 
);
--MO_ADDRESS--
CREATE TABLE MO_ADDRESS
(
ADDRESS_PK NUMBER(9)  ,
UPRN NUMBER(13) ,
PAFADDRESSKEY NUMBER(9) ,
PROPERTYNUMBERPROPERTY NUMBER(9) ,
CUSTOMERNUMBERPROPERTY NUMBER(9) ,
UPRNREASONCODE VARCHAR(2) ,
SECONDADDRESABLEOBJECT VARCHAR(255) ,
PRIMARYADDRESSABLEOBJECT VARCHAR(100) ,
ADDRESSLINE01 VARCHAR(60) CONSTRAINT CH02_ADDRESSLINE01 NOT NULL,
ADDRESSLINE02 VARCHAR(60) ,
ADDRESSLINE03 VARCHAR(60) ,
ADDRESSLINE04 VARCHAR(60) ,
ADDRESSLINE05 VARCHAR(60) ,
POSTCODE VARCHAR(8) CONSTRAINT CH02_POSTCODE NOT NULL,
COUNTRY VARCHAR(32) ,
LOCATIONFREETEXTDESCRIPTOR VARCHAR(255) 
);

--CREATE_TABLE_DDL--
--MO_TARIFF--
CREATE TABLE MO_TARIFF
(
TARIFFCODE_PK VARCHAR(32)  ,
SERVICECOMPONENTREF_PK NUMBER(9) ,
TARIFFEFFECTIVEFROMDATE DATE ,
TARIFFNAME VARCHAR(40) ,
TARIFFSTATUS VARCHAR(8) CONSTRAINT CH01_TARIFFSTATUS NOT NULL,
TARIFFLEGACYEFFECTIVEFROMDATE DATE ,
APPLICABLESERVICECOMPONENT VARCHAR(5) ,
TARIFFAUTHCODE VARCHAR(12) ,
VACANCYCHARGINGMETHODWATER VARCHAR(128) ,
VACANCYCHARGINGMETHODSEWERAGE VARCHAR(128) ,
TEMPDISCONCHARGINGMETHODWAT VARCHAR(128) ,
TEMPDISCONCHARGINGMETHODSEW VARCHAR(128)  
);
--MO_TARIFF_VERSION--
CREATE TABLE MO_TARIFF_VERSION
(
TARIFF_VERSION_PK NUMBER(12)  ,
TARIFFCODE_PK VARCHAR(32) ,
TARIFFVERSION VARCHAR(32) CONSTRAINT CH03_TARIFFVERSION NOT NULL,
TARIFFVEREFFECTIVEFROMDATE DATE CONSTRAINT CH03_TARIFFVEREFFECFROMDATE NOT NULL,
TARIFFSTATUS VARCHAR(8) CONSTRAINT CH03_TARIFFSTATUS NOT NULL,
APPLICABLESERVICECOMPONENT VARCHAR(5) CONSTRAINT CH03_APPLICABLESERVICECOMP NOT NULL,
DEFAULTRETURNTOSEWER NUMBER(2,2) ,
TARIFFCOMPONENTTYPE VARCHAR(12) ,
SECTION154PAYMENTVALUE NUMBER(6,2) 
);
--MO_TARIFF_TYPE_MPW--
CREATE TABLE MO_TARIFF_TYPE_MPW
(
TARIFF_TYPE_PK NUMBER(12)  ,
TARIFF_VERSION_PK NUMBER(12) ,
MPWSUPPLYPOINTFIXEDCHARGES NUMBER(6,2) ,
MPWPREMIUMTOLFACTOR NUMBER(2,2) ,
MPWDAILYSTANDBYUSAGEVOLCHARGE NUMBER(6,2) ,
MPWDAILYPREMIUMUSAGEVOLCHARGE NUMBER(6,2) ,
MPWMAXIMUMDEMANDTARIFF NUMBER(6,2) 
);
--MO_MPW_METER_MWMFC--
CREATE TABLE MO_MPW_METER_MWMFC
(
TARIFF_MWMFC_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
LOWERMETERSIZE NUMBER(6) ,
UPPERMETERSIZE NUMBER(6) ,
CHARGE NUMBER(6,2) 
);
--MO_MPW_BLOCK_MWBT--
CREATE TABLE MO_MPW_BLOCK_MWBT
(
TARIFF_MWBT_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
UPPERANNUALVOL NUMBER(12) ,
CHARGE NUMBER(6,2) 
);
--MO_MPW_STANDBY_MWCAPCHG--
CREATE TABLE MO_MPW_STANDBY_MWCAPCHG
(
TARIFF_MWCAPCHG_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
RESERVATIONVOLUME NUMBER(12) ,
CHARGE NUMBER(6,2) 
);
--MO_TARIFF_TYPE_MNPW--
CREATE TABLE MO_TARIFF_TYPE_MNPW
(
TARIFF_TYPE_PK NUMBER(12)  ,
TARIFF_VERSION_PK NUMBER(12) ,
MNPWSUPPLYPOINTFIXEDCHARGE NUMBER(6,2) ,
MNPWPREMIUMTOLFACTOR NUMBER(2,2) ,
MNPWDAILYSTANDBYUSAGEVOLCHARGE NUMBER(6,2) ,
MNPWDAILYPREMIUMUSAGEVOLCHARGE NUMBER(6,2) ,
MNPWMAXIMUMDEMANDTARIFF NUMBER(6,2) 
);
--MO_MNPW_METER_MWMFC--
CREATE TABLE MO_MNPW_METER_MWMFC
(
TARIFF_MWMFC_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
LOWERMETERSIZE NUMBER(6) ,
UPPERMETERSIZE NUMBER(6) ,
CHARGE NUMBER(6,2) 
);
--MO_MNPW_BLOCK_MWBT--
CREATE TABLE MO_MNPW_BLOCK_MWBT
(
TARIFF_MWBT_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
UPPERANNUALVOL NUMBER(12) ,
CHARGE NUMBER(6,2) 
);
--MO_MNPW_STANDBY_MWCAPCHG--
CREATE TABLE MO_MNPW_STANDBY_MWCAPCHG
(
TARIFF_MWCAPCHG_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
RESERVATIONVOLUME NUMBER(12) ,
CHARGE NUMBER(6,2) 
);
--MO_TARIFF_TYPE_AW--
CREATE TABLE MO_TARIFF_TYPE_AW
(
TARIFF_TYPE_PK NUMBER(12)  ,
TARIFF_VERSION_PK NUMBER(12) ,
AWFIXEDCHARGE NUMBER(6,2) ,
AWVOLUMETRICCHARGE NUMBER(6,2) 
);
--MO_AW_METER_AWMFC--
CREATE TABLE MO_AW_METER_AWMFC
(
TARIFF_AWMFC_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
LOWERMETERSIZE NUMBER(6) ,
UPPERMETERSIZE NUMBER(6) ,
CHARGE NUMBER(6,2) 
);
--MO_AW_BAND_CHARGE--
CREATE TABLE MO_AW_BAND_CHARGE
(
TARIFF_BAND_CHARGE_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
BAND NUMBER(3) ,
CHARGE NUMBER(6,2) 
);
--MO_TARIFF_TYPE_UW--
CREATE TABLE MO_TARIFF_TYPE_UW
(
TARIFF_TYPE_PK NUMBER(12)  ,
TARIFF_VERSION_PK NUMBER(12) ,
UWFIXEDCHARGE NUMBER(6,2) ,
UWRVPOUNDAGE NUMBER(6,2) ,
UWRVTHRESHOLD NUMBER(6,2) ,
UWRVMAXCHARGE NUMBER(6,2) ,
UWRVMINCHARGE NUMBER(6,2) ,
UWMISCTYPEACHARGE NUMBER(6,2) ,
UWMISCTYPEBCHARGE NUMBER(6,2) ,
UWMISCTYPECCHARGE NUMBER(6,2) ,
UWMISCTYPEDCHARGE NUMBER(6,2) ,
UWMISCTYPEECHARGE NUMBER(6,2) ,
UWMISCTYPEFCHARGE NUMBER(6,2) ,
UWMISCTYPEGCHARGE NUMBER(6,2) ,
UWMISCTYPEHCHARGE NUMBER(6,2) 
);
--MO_UW_METER_UWPFC--
CREATE TABLE MO_UW_METER_UWPFC
(
TARIFF_UWPFC_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
LOWERMETERSIZE NUMBER(6) ,
UPPERMETERSIZE NUMBER(6) ,
CHARGE NUMBER(6,2) 
);
--MO_TARIFF_TYPE_MS--
CREATE TABLE MO_TARIFF_TYPE_MS
(
TARIFF_TYPE_PK NUMBER(12)  ,
TARIFF_VERSION_PK NUMBER(12) ,
MSSUPPLYPOINTFIXEDCHARGES NUMBER(6,2) ,
MSEFFECTIVEFROMDATE DATE 
);
--MO_MS_BLOCK_MSBT--
CREATE TABLE MO_MS_BLOCK_MSBT
(
TARIFF_MWBT_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
UPPERANNUALVOL NUMBER(12) ,
CHARGE NUMBER(6,2) 
);
--MO_MS_METER_MSMFC--
CREATE TABLE MO_MS_METER_MSMFC
(
TARIFF_MSMFC_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
LOWERMETERSIZE NUMBER(6) ,
UPPERMETERSIZE NUMBER(6) ,
CHARGE NUMBER(6,2) 
);
--MO_TARIFF_TYPE_AS--
CREATE TABLE MO_TARIFF_TYPE_AS
(
TARIFF_TYPE_PK NUMBER(12)  ,
TARIFF_VERSION_PK NUMBER(12) ,
ASFIXEDCHARGE NUMBER(6,2) ,
ASVOLMETCHARGE NUMBER(6,2) ,
ASEFFECTIVEDATE DATE 
);
--MO_AS_METER_ASMFC--
CREATE TABLE MO_AS_METER_ASMFC
(
TARIFF_ASMFC_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
LOWERMETERSIZE NUMBER(6) ,
UPPERMETERSIZE NUMBER(6) ,
CHARGE NUMBER(6,2) 
);
--MO_AS_BAND_CHARGE--
CREATE TABLE MO_AS_BAND_CHARGE
(
TARIFF_BAND_CHARGE_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
BAND NUMBER(3) ,
CHARGE NUMBER(6,2) 
);
--MO_TARIFF_TYPE_US--
CREATE TABLE MO_TARIFF_TYPE_US
(
TARIFF_TYPE_PK NUMBER(12)  ,
TARIFF_VERSION_PK NUMBER(12)  ,
USFIXEDCHARGE NUMBER(6,2) ,
USRVPOUNDAGE NUMBER(6,2) ,
USRVTHRESHOLD NUMBER(6,2) ,
USRVMAXIMUMCHARGE NUMBER(6,2) ,
USRVMINIMUMCHARGE NUMBER(6,2) ,
USMISCTYPEACHARGE NUMBER(6,2) ,
USMISCTYPEBCHARGE NUMBER(6,2) ,
USMISCTYPECCHARGE NUMBER(6,2) ,
USMISCTYPEDCHARGE NUMBER(6,2) ,
USMISCTYPEECHARGE NUMBER(6,2) ,
USMISCTYPEFCHARGE NUMBER(6,2) ,
USMISCTYPEGCHARGE NUMBER(6,2) ,
USMISCTYPEHCHARGE NUMBER(6,2) 
);
--MO_US_METER_USPFC--
CREATE TABLE MO_US_METER_USPFC
(
TARIFF_USPFC_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
LOWERMETERSIZE NUMBER(6) ,
UPPERMETERSIZE NUMBER(6) ,
CHARGE NUMBER(6,2) 
);
--MO_TARIFF_TYPE_SW--
CREATE TABLE MO_TARIFF_TYPE_SW
(
TARIFF_TYPE_PK NUMBER(12)  ,
TARIFF_VERSION_PK NUMBER(12) ,
SWCOMBAND VARCHAR(16) ,
SWFIXEDCHARGE NUMBER(6,2) ,
SWRVPOUNDAGE NUMBER(6,2) ,
SWRVTHRESHOLD NUMBER(6,2) ,
SWRVMAXIMUMCHARGE NUMBER(6,2) ,
SWRVMINIMUMCHARGE NUMBER(6,2) ,
SWMETERFIXEDCHARGES NUMBER(6,2) 
);
--MO_SW_AREA_BAND--
CREATE TABLE MO_SW_AREA_BAND
(
TARIFF_AREA_BAND_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
LOWERAREA NUMBER(6) ,
UPPERAREA NUMBER(6) ,
BAND NUMBER(3) 
);
--MO_SW_BAND_CHARGE--
CREATE TABLE MO_SW_BAND_CHARGE
(
TARIFF_BAND_CHARGE_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
BAND NUMBER(3) ,
CHARGE NUMBER(6,2) 
);
--MO_SW_BLOCK_SWBT--
CREATE TABLE MO_SW_BLOCK_SWBT
(
TARIFF_SWBT_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
UPPERANNUALVOL NUMBER(12) ,
CHARGE NUMBER(6,2) 
);
--MO_SW_METER_SWMFC--
CREATE TABLE MO_SW_METER_SWMFC
(
TARIFF_SWMFC_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
LOWERMETERSIZE NUMBER(6) ,
UPPERMETERSIZE NUMBER(6) ,
CHARGE NUMBER(6,2) 
);
--MO_TARIFF_TYPE_HD--
CREATE TABLE MO_TARIFF_TYPE_HD
(
TARIFF_TYPE_PK NUMBER(12)  ,
TARIFF_VERSION_PK NUMBER(12) ,
HDCOMBAND VARCHAR(16) ,
HDFIXEDCHARGE NUMBER(6,2) ,
HDRVPOUNDAGE NUMBER(6,2) ,
HDRVTHRESHOLD NUMBER(6,2) ,
HDRVMAXCHARGE NUMBER(6,2) ,
HDRVMINCHARGE NUMBER(6,2) 
);
--MO_HD_AREA_BAND--
CREATE TABLE MO_HD_AREA_BAND
(
TARIFF_AREA_BAND_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
LOWERAREA NUMBER(6) ,
UPPERAREA NUMBER(6) ,
BAND NUMBER(3) 
);
--MO_HD_BAND_CHARGE--
CREATE TABLE MO_HD_BAND_CHARGE
(
TARIFF_BAND_CHARGE_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
BAND NUMBER(3) ,
CHARGE NUMBER(6,2) 
);
--MO_HD_BLOCK_HDBT--
CREATE TABLE MO_HD_BLOCK_HDBT
(
TARIFF_HDBT_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
UPPERANNUALVOL NUMBER(12) ,
CHARGE NUMBER(6,2) 
);
--MO_HD_METER_HDMFC--
CREATE TABLE MO_HD_METER_HDMFC
(
TARIFF_HDMFC_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
LOWERMETERSIZE NUMBER(6) ,
UPPERMETERSIZE NUMBER(6) ,
CHARGE NUMBER(6,2) 
);
--MO_TARIFF_TYPE_TE--
CREATE TABLE MO_TARIFF_TYPE_TE
(
TARIFF_TYPE_PK NUMBER(12)  ,
TARIFF_VERSION_PK NUMBER(12) ,
TEFIXEDCHARGE NUMBER(6,2) ,
TECHARGECOMPRA NUMBER(6,2) ,
TECHARGECOMPVA NUMBER(6,2) ,
TECHARGECOMPBVA NUMBER(6,2) ,
TECHARGECOMPMA NUMBER(6,2) ,
TECHARGECOMPBA NUMBER(6,2) ,
TECHARGECOMPSA NUMBER(6,2) ,
TECHARGECOMPAA NUMBER(6,2) ,
TECHARGECOMPVO NUMBER(6,2) ,
TECHARGECOMPBVO NUMBER(6,2) ,
TECHARGECOMPMO NUMBER(6,2) ,
TECHARGECOMPSO NUMBER(6,2) ,
TECHARGECOMPAO NUMBER(6,2) ,
TECHARGECOMPOS NUMBER(9) ,
TECHARGECOMPSS NUMBER(9) ,
TECHARGECOMPAS NUMBER(9) ,
TECHARGECOMPAM NUMBER(9) ,
TEMINCHARGE NUMBER(6,2) ,
TECHARGECOMPXA NUMBER(6,2) ,
TECHARGECOMPYA NUMBER(6,2) ,
TECHARGECOMPZA NUMBER(6,2) ,
TECHARGECOMPXO NUMBER(6,2) ,
TECHARGECOMPYO NUMBER(6,2) ,
TECHARGECOMPZO NUMBER(6,2) ,
TECHARGECOMPXS NUMBER(9) ,
TECHARGECOMPYS NUMBER(9) ,
TECHARGECOMPZS NUMBER(9) ,
TECHARGECOMPXM NUMBER(9) ,
TECHARGECOMPYM NUMBER(9) ,
TECHARGECOMPZM NUMBER(9) 
);
--MO_TE_BAND_CHARGE--
CREATE TABLE MO_TE_BAND_CHARGE
(
TARIFF_BAND_CHARGE_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
BAND NUMBER(3) ,
CHARGE NUMBER(6,2) 
);
--MO_TE_BLOCK_ROBT--
CREATE TABLE MO_TE_BLOCK_ROBT
(
TARIFF_ROBT_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
UPPERANNUALVOL NUMBER(12) ,
CHARGE NUMBER(6,2) 
);
--MO_TE_BLOCK_BOBT--
CREATE TABLE MO_TE_BLOCK_BOBT
(
TARIFF_BOBT_PK NUMBER(12)  ,
TARIFF_TYPE_PK NUMBER(12) ,
UPPERANNUALVOL NUMBER(12) ,
CHARGE NUMBER(6,2) 
);

commit;
exit;

