------------------------------------------------------------------------------
-- TASK		    		    : 	MOSL DEL RDBMS PATCHES 
--
-- AUTHOR         		: 	D.Cheung
--
-- FILENAME       		: 	DEL_P0008.sql
--
--
-- Subversion $Revision: 5905 $	
--
-- CREATED        		: 	31/05/2016
--	
-- DESCRIPTION 		   	: 	This file contains all ongoing patches that are made to the MOSL DEL database
--
-- NOTES  			      :	Place a summary at the top of the file with more detailed information 
--					where the patch is applied in this script (if needed)
--
-- ASSOCIATED FILES		:	
-- ASSOCIATED SCRIPTS :	
---------------------------- Modification History ----------------------------------------------------------
--
-- Version     	  Date            Author          Description
-- ---------      ----------      -------         ----------------------------------------------------------
-- V0.04          19/10/2016      S.Badhan        Remove slashes causing statements to run twice.
-- V0.03          15/08/2016      S.Badhan        I-320. Remove schema name from view.
-- V0.02          01/05/2016      D.Cheung        Add Foreign Key constraints to DEL_METER_DISCHARGE_POINT
--                                                Add Foreign Key constraints to DEL_DISCHARGE_POINT
--                                                Add Foreign Key constraints to DEL_CALCULATED_DISCHARGE
--                                                FIX SEWERAGE RELATED CONSTRAINTS ON DEL_METER
-- V0.01	        31/05/2016	    D.Cheung        Update aggregate functions for TECHARGECOMP## values change from COUNT to MAX
------------------------------------------------------------------------------------------------------------
-- CHANGES

CREATE OR REPLACE FORCE VIEW DEL_DISCHARGE_POINT_TARIFF_V 
(TARIFFCODE_PK, VALIDTETARIFFCODE, TARIFFBANDCOUNT, AMMONIACALNITROGEN, XCOMP, YCOMP, ZCOMP)
AS
  (SELECT T.TARIFFCODE_PK,
    COUNT(T.TARIFFCODE_PK) VALIDTETARIFFCODE,
    COUNT(TB.BAND) TARIFFBANDCOUNT,
    MAX(TE.TECHARGECOMPAO) AMMONIACALNITROGEN,
    MAX(TE.TECHARGECOMPXO) XCOMP,
    MAX(TE.TECHARGECOMPYO) YCOMP,
    MAX(TE.TECHARGECOMPZO) ZCOMP
  FROM MOUTRAN.MO_TARIFF T,
    MOUTRAN.MO_TARIFF_VERSION TV,
    MOUTRAN.MO_TARIFF_TYPE_TE TE,
    MOUTRAN.MO_TE_BAND_CHARGE TB
  WHERE T.SERVICECOMPONENTTYPE = 'TE'
  AND TV.TARIFFCODE_PK         = T.TARIFFCODE_PK
  AND TV.TARIFF_VERSION_PK     = TE.TARIFF_VERSION_PK
  AND TE.TARIFF_TYPE_PK        = TB.TARIFF_TYPE_PK(+)
  AND TV.TARIFFVERSION         =
    (SELECT MAX(TARIFFVERSION)
    FROM MOUTRAN.MO_TARIFF_VERSION
    WHERE TARIFFCODE_PK = T.TARIFFCODE_PK
    )
  GROUP BY T.TARIFFCODE_PK
  );

-- ADD FOREIGN KEY CONSTRAINTS TO DEL DISCHARGE TABLES
ALTER TABLE DEL_METER_DISCHARGE_POINT ADD CONSTRAINT FK02_METER_MAN_SERIAL_COMP FOREIGN KEY (MANUFACTURER_PK, MANUFACTURERSERIALNUM_PK) REFERENCES DEL_METER(MANUFACTURER_PK, MANUFACTURERSERIALNUM_PK);
ALTER TABLE DEL_DISCHARGE_POINT DROP CONSTRAINT CH01_UNIQUESPDPID;
--ALTER TABLE DEL_DISCHARGE_POINT ADD CONSTRAINT CH01_UNIQUESPID UNIQUE (SPID_PK);
ALTER TABLE DEL_DISCHARGE_POINT ADD CONSTRAINT CH01_UNIQUEDPID UNIQUE (DPID_PK);
ALTER TABLE DEL_DISCHARGE_POINT ADD CONSTRAINT FK01_SPID_PK FOREIGN KEY (SPID_PK) REFERENCES DEL_SUPPLY_POINT(SPID_PK);
ALTER TABLE DEL_METER_DISCHARGE_POINT ADD CONSTRAINT FK01_DPID_PK FOREIGN KEY (DPID_PK) REFERENCES DEL_DISCHARGE_POINT(DPID_PK);
ALTER TABLE DEL_CALCULATED_DISCHARGE ADD CONSTRAINT FK02_DPID_PK FOREIGN KEY (DPID_PK) REFERENCES DEL_DISCHARGE_POINT(DPID_PK);

--FIX SEWERAGE RELATED CONSTRAINTS ON DEL_METER
ALTER TABLE DEL_METER DROP CONSTRAINT CH01_YEARLYVOLESTIMATE;
ALTER TABLE DEL_METER DROP CONSTRAINT CH01_RETURNTOSEWER;
ALTER TABLE DEL_METER DROP CONSTRAINT CH01_SEWCHARGEABLEMETERSIZE;
ALTER TABLE DEL_METER ADD CONSTRAINT CH01_YEARLYVOLESTIMATE CHECK (((METERTREATMENT IN ('SEWERAGE', 'PRIVATETE', 'PRIVATEWATER', 'CROSSBORDER')) AND YEARLYVOLESTIMATE IS NOT NULL) OR ((METERTREATMENT NOT IN ('SEWERAGE', 'PRIVATETE', 'PRIVATEWATER'))));
ALTER TABLE DEL_METER ADD CONSTRAINT CH01_RETURNTOSEWER CHECK (((METERTREATMENT IN ('SEWERAGE', 'PRIVATETE', 'PRIVATEWATER', 'CROSSBORDER')) AND RETURNTOSEWER IS NOT NULL) OR ((METERTREATMENT NOT IN ('SEWERAGE', 'PRIVATETE', 'PRIVATEWATER'))));
ALTER TABLE DEL_METER ADD CONSTRAINT CH01_SEWCHARGEABLEMETERSIZE CHECK (((METERTREATMENT IN ('SEWERAGE', 'PRIVATETE', 'PRIVATEWATER', 'CROSSBORDER')) AND SEWCHARGEABLEMETERSIZE IS NOT NULL) OR ((METERTREATMENT NOT IN ('SEWERAGE', 'PRIVATETE', 'PRIVATEWATER'))));

commit;

show errors;
exit;