------------------------------------------------------------------------------
-- TASK					: 	MOSL RDBMS CREATION 
--
-- AUTHOR         		: 	Nigel Henderson
--
-- FILENAME       		: 	04_DDL_MOSL_STATIC_DATA_ALL.sql
--
-- CREATED        		: 	22/02/2016
--	
-- Subversion $Revision: 4023 $
----	
-- DESCRIPTION 		   	: 	Inserts static (mandatory) data. 
--
-- NOTES  				:	Used in conjunction with the following scripts to re-initialise the
-- 							database.  When re-creating the database run the scripts in order.
--
-- ASSOCIATED FILES		:	MOSL_PDM_CORE.xlsm
-- ASSOCIATED SCRIPTS  	:	01_DDL_MOSL_TABLES_ALL.sql
--							02_DDL_MOSL_PK_ALL.sql
--							03_DDL_MOSL_FK_ALL.sql
--							05_COMMENTS_TABLES_FIELDS_ALL
--
--
--
--
--
---------------------------- Modification History ------------------------------------------------------------------------------------------
--
-- Version     	Date                Author         		Description
-- ---------    ---------------     -------             ------------------------------------------------
-- V0.01       	15/02/2016    		N.Henderson         Initial version after generation from Excel
-- V0.02		15/02/2016			N.Henderson			Updates to fields where the constraint name is too large or already used.
--														CHK01_ESTIMATEDREADREMEDIALWORKIND, shortened to CHK01_ESTIMATEDREADREMEDIAL	
--														CHK01_INSTALLEDBYACCREDITEDENTITY, shortened to CHK01_INSTALLEDBYACCREDITED
--														CHK01_DPIDSPECIALAGREEMENTINPLACE, shortened to CHK01_DPIDSPECIALAGREEMENT 
--														CHK01_AMMONIATREATMENTINDICATOR, shortened to CHK01_AMMONIATREATMENTIND 
--														CHK01_PRIMARYTREATMENTINDICATOR, shortened to CHK01_PRIMARYTREATMENTIND 
--														CHK01_RECEPTIONTREATMENTINDICATOR, shortened to CHK01_RECEPTIONTREATMENTIND
-- 														CHK01_ADJUSTMENTSVOLADJTYPE, changed to CHK02_ADJUSTMENTSVOLADJTYPE
--														CHK01_SRFCWATERCOMMUNITYCONFLAG, changed to CHK01_SRFCWATERCOMMCONFLAG
--														CHK01_SPECIALAGREEMENTFLAG, changed to CHK02_SPECIALAGREEMENTFLAG
--														CHK01_HWAYCOMMUNITYCONFLAG, changed to CHK02_HWAYCOMMUNITYCONFLAG
--														CHK01_TMPDISCONCHRGMETHODSEWERAGE, shortened to CHK01_TMPDISCONCHRGMETHSEW
--														CHK01_VACANCYCHARGINGMETHODSEWERAGE, shortened to CHK01_VACANCYCHARGINGMETHSEW
--														CHK01_VACANCYCHARGINGMETODWATER, shortened to CHK01_VACANCYCHARGINGMETWATER
--														CHK01_INTERIMSUPPLIERALLOCSTATUS, shortened to CHK01_INTERIMSUPPALLOCSTAT
--														CHK01_OTHERSERVICECATPROVIDEDREASON, shortened to CHK01_OTHERSRVREASON
--														CHK01_UPRNREASONCODE, changed to CHK02_UPRNREASONCODE
--
--
--
-- V0.03 		15/03/2016 			N.Henderson			Added readable constraint names
--
--------------------------------------------------------------------------------------------------------------------------------------------

--ADD CONSTRAINTS reference data--
--MO_CUSTOMER--
ALTER TABLE MO_CUSTOMER ADD CONSTRAINT RF01_CUSTOMERCLASSIFICATION CHECK (CUSTOMERCLASSIFICATION IN ('SEMDV', 'NA'));
ALTER TABLE MO_CUSTOMER ADD CONSTRAINT RF01_STDINDUSTRYCLASSCODETYPE CHECK (STDINDUSTRYCLASSCODETYPE IN ('1980', '1992', '2003', '2007'));
--MO_ELIGIBLE_PREMISES--
ALTER TABLE MO_ELIGIBLE_PREMISES ADD CONSTRAINT RF01_OCCUPENCYSTATUS CHECK (OCCUPENCYSTATUS IN ('OCCUPIED', 'VACANT'));
ALTER TABLE MO_ELIGIBLE_PREMISES ADD CONSTRAINT RF01_VOABAREFRSNCODE CHECK (VOABAREFRSNCODE IN ('NR','ME','AG','SR','MT','IP','SP','OT'));
ALTER TABLE MO_ELIGIBLE_PREMISES ADD CONSTRAINT RF01_BUILDINGWATERSTATUS CHECK (BUILDINGWATERSTATUS IN (0,1));
ALTER TABLE MO_ELIGIBLE_PREMISES ADD CONSTRAINT RF01_NONPUBHEALTHRELSITE  CHECK (NONPUBHEALTHRELSITE  IN (0,1));
ALTER TABLE MO_ELIGIBLE_PREMISES ADD CONSTRAINT RF01_PUBHEALTHRELSITEARR CHECK (PUBHEALTHRELSITEARR IN (0,1));
ALTER TABLE MO_ELIGIBLE_PREMISES ADD CONSTRAINT RF01_UPRNREASONCODE CHECK (UPRNREASONCODE IN ('ME','SR','MT','IP','PL','BW','SP','OT'));
--MO_SUPPLY_POINT--
ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT RF01_SERVICECATEGORY CHECK (SERVICECATEGORY IN ('W','S'));
ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT RF01_DISCONRECONDEREGSTATUS CHECK (DISCONRECONDEREGSTATUS IN ('TDISC'));
ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT RF01_OTHERSERVICECATPROVIDED CHECK (OTHERSERVICECATPROVIDED IN (0,1));
ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT RF01_OTHERSERVICEPROVIDEDREA CHECK (OTHERSERVICECATPROVIDEDREASON IN ('NS', 'NA', 'NR'));
ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT RF01_MULTIPLEWHOLESALERFLAG CHECK (MULTIPLEWHOLESALERFLAG IN (0,1));
ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT RF01_SPIDSTATUS CHECK (SPIDSTATUS IN ('NEW', 'PARTIAL', 'TRADEABLE', 'REJECTED', 'DEREG'));
ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT RF01_NEWCONNECTIONTYPE CHECK (NEWCONNECTIONTYPE IN ('NEW', 'GS', 'CU'));
ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT RF01_ACCREDITEDENTITYFLAG CHECK (ACCREDITEDENTITYFLAG IN (0,1));
ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT RF01_GAPSITEALLOCATIONMETHOD CHECK (GAPSITEALLOCATIONMETHOD IN ('SEQ', 'SPID'));
ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT RF01_PAIRINGREFREASONCODE CHECK (PAIRINGREFREASONCODE IN ('NOSPID', 'NOTELIGIBLE'));
ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT RF01_LATEREGAPPLICATION CHECK (LATEREGAPPLICATION IN (0,1));
ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT RF01_VOLTRANSFERFLAG CHECK (VOLTRANSFERFLAG IN (0,1));
--MO_ORG--
ALTER TABLE MO_ORG ADD CONSTRAINT RF01_RETAILERTYPE CHECK (RETAILERTYPE IN ('FULL', 'SELFSUPPLY', 'TERMINATED'));
ALTER TABLE MO_ORG ADD CONSTRAINT RF01_INTERIMSUPPLIERALLOCSTAT CHECK (INTERIMSUPPLIERALLOCSTATUS IN ('OPTIN', 'OPTOUT', 'INSOLSUS', 'VOLSUS'));
ALTER TABLE MO_ORG ADD CONSTRAINT RF01_TRADINGPARTYSERVICECAT CHECK (TRADINGPARTYSERVICECAT IN ('W', 'S', 'WS'));
ALTER TABLE MO_ORG ADD CONSTRAINT RF01_GAPSITEALLOCSTATUS CHECK (GAPSITEALLOCSTATUS IN ('OPTIN', 'OPTOUT', 'INSOLSUS', 'MOSUS'));
ALTER TABLE MO_ORG ADD CONSTRAINT RF01_VACANCYCHARGINGMETHWATER CHECK (VACANCYCHARGINGMETHODWATER IN ('VWA', 'VWB', 'VWC'));
ALTER TABLE MO_ORG ADD CONSTRAINT RF01_VACANCYCHARGINGMETHSEWER CHECK (VACANCYCHARGINGMETHODSEWERAGE IN ('VSA', 'VSB', 'VSC', 'VSD', 'VSE'));
ALTER TABLE MO_ORG ADD CONSTRAINT RF01_TMPDISCONCHRGMETHODWATER CHECK (TMPDISCONCHRGMETHODWATER IN ('TWA', 'TWB', 'TWC'));
ALTER TABLE MO_ORG ADD CONSTRAINT RF01_TMPDISCONCHRGMETHSEWER CHECK (TMPDISCONCHRGMETHODSEWERAGE IN ('TSA', 'TSB', 'TSC', 'TSD', 'TSE'));
--MO_RETAILER_REGISTRATION--
ALTER TABLE MO_RETAILER_REGISTRATION ADD CONSTRAINT RF01_CANCELLATIONCODE CHECK (CANCELLATIONCODE IN ('SPERR', 'NOCON', 'DEBT', 'CON', 'SELF', 'NOTUNDERTAKER'));
ALTER TABLE MO_RETAILER_REGISTRATION ADD CONSTRAINT RF01_TRANSFERVALIDFLAG CHECK (TRANSFERVALIDFLAG IN (0,1));
--MO_SERVICE_COMPONENT--
ALTER TABLE MO_SERVICE_COMPONENT ADD CONSTRAINT RF01_STWSERVICETYPE CHECK (STWSERVICETYPE IN (0));
ALTER TABLE MO_SERVICE_COMPONENT ADD CONSTRAINT RF01_SERVICECOMPONENTTYPE CHECK (SERVICECOMPONENTTYPE IN ('MPW','MNPW','AW','UW','MS','AS','US','SW','HD','TE','WCA','SCA'));
ALTER TABLE MO_SERVICE_COMPONENT ADD CONSTRAINT RF01_SERVICECOMPONENTENABLED CHECK (SERVICECOMPONENTENABLED IN (0,1));
ALTER TABLE MO_SERVICE_COMPONENT ADD CONSTRAINT RF01_SPECIALAGREEMENTFLAG CHECK (SPECIALAGREEMENTFLAG IN (0,1));
ALTER TABLE MO_SERVICE_COMPONENT ADD CONSTRAINT RF01_HWAYCOMMUNITYCONFLAG CHECK (HWAYCOMMUNITYCONFLAG IN (0,1));
ALTER TABLE MO_SERVICE_COMPONENT ADD CONSTRAINT RF01_SRFCWATERCOMMUNITYCONFLAG CHECK (SRFCWATERCOMMUNITYCONFLAG IN (0,1));
--MO_SERVICE_COMPONENT_VOL_ADJ--
ALTER TABLE MO_SERVICE_COMPONENT_VOL_ADJ ADD CONSTRAINT RF01_ADJUSTMENTSVOLADJTYPE CHECK (ADJUSTMENTSVOLADJTYPE IN ('BURST', 'FIRE', 'METER'));
--MO_DISCHARGE_POINT--
ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT RF01_SERVICECOMPTYPE CHECK (SERVICECOMPTYPE = ('TE'));
ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT RF01_DISCHARGEPOINTERASEFLAG CHECK (DISCHARGEPOINTERASEFLAG IN (0,1));
ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT RF01_RECEPTIONTREATMENTIND CHECK (RECEPTIONTREATMENTINDICATOR IN (0,1));
ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT RF01_PRIMARYTREATMENTINDICATOR CHECK (PRIMARYTREATMENTINDICATOR IN (0,1));
ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT RF01_MARINETREATMENTINDICATOR CHECK (MARINETREATMENTINDICATOR IN (0,1));
ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT RF01_BIOLOGICALTREATMENTIND CHECK (BIOLOGICALTREATMENTINDICATOR IN (0,1));
ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT RF01_SLUDGETREATMENTINDICATOR CHECK (SLUDGETREATMENTINDICATOR IN (0,1));
ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT RF01_AMMONIATREATMENTINDICATOR CHECK (AMMONIATREATMENTINDICATOR IN (0,1));
ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT RF01_TEFXTREATMENTINDICATOR CHECK (TEFXTREATMENTINDICATOR IN (0,1));
ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT RF01_TEFYTREATMENTINDICATOR CHECK (TEFYTREATMENTINDICATOR IN (0,1));
ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT RF01_TEFZTREATMENTINDICATOR CHECK (TEFZTREATMENTINDICATOR IN (0,1));
ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT RF01_SEWERAGEVOLUMEADJMENTHOD CHECK (SEWERAGEVOLUMEADJMENTHOD IN ('NONE', 'DA', 'SUBTRACT'));
ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT RF01_DPIDSPECIALAGREEMENT CHECK (DPIDSPECIALAGREEMENTINPLACE IN (0,1));
--MO_CALCULATED_DISCHARGE--
ALTER TABLE MO_CALCULATED_DISCHARGE ADD CONSTRAINT RF01_DISCHARGETYPE CHECK (DISCHARGETYPE IN ('CONTAMINATED', 'DELAYED', 'ESTIMATED', 'TANKERED', 'GENERIC'));
ALTER TABLE MO_CALCULATED_DISCHARGE ADD CONSTRAINT RF01_SUBMISSIONFREQ CHECK (SUBMISSIONFREQ IN ('B', 'M'));
--MO_DISCHARGED_VOLUME--
--MO_DISCHARGE_POINT_VOLMET_ADJ--
ALTER TABLE MO_DISCHARGE_POINT_VOLMET_ADJ ADD CONSTRAINT RF02_ADJUSTMENTSVOLADJTYPE CHECK (ADJUSTMENTSVOLADJTYPE IN ('BURST', 'FIRE', 'METER'));
--MO_METER--
ALTER TABLE MO_METER ADD CONSTRAINT RF01_METERERASEDFLAG CHECK (METERERASEDFLAG IN (0,1));
ALTER TABLE MO_METER ADD CONSTRAINT RF01_NONMARKETMETERFLAG CHECK (NONMARKETMETERFLAG IN (0,1));
ALTER TABLE MO_METER ADD CONSTRAINT RF01_INSTALLEDBYACCREDITED CHECK (INSTALLEDBYACCREDITEDENTITY IN (0,1));
ALTER TABLE MO_METER ADD CONSTRAINT RF01_METERTREATMENT CHECK (METERTREATMENT IN ('POTABLE', 'NONPOTABLE', 'PRIVATEWATER', 'PRIVATETE', 'SEWERAGE', 'CROSSBORDER'));
ALTER TABLE MO_METER ADD CONSTRAINT RF01_MEASUREUNITFREEATMETER CHECK (MEASUREUNITFREEATMETER IN ('METRICm3', 'METRICNONm3'));
ALTER TABLE MO_METER ADD CONSTRAINT RF01_METERADDITIONREASON CHECK (METERADDITIONREASON IN ('ADD', 'EXCHANGE'));
ALTER TABLE MO_METER ADD CONSTRAINT RF01_METERREMOVALREASON CHECK (METERREMOVALREASON IN ('REMOVE', 'EXCHANGE'));
ALTER TABLE MO_METER ADD CONSTRAINT RF01_METERREADMINFREQUENCY CHECK (METERREADMINFREQUENCY IN ('B','M'));
ALTER TABLE MO_METER ADD CONSTRAINT RF01_DATALOGGERWHOLESALER CHECK (DATALOGGERWHOLESALER IN (0,1));
ALTER TABLE MO_METER ADD CONSTRAINT RF01_METERLOCATIONCODE CHECK (METERLOCATIONCODE IN ('I', 'O'));
ALTER TABLE MO_METER ADD CONSTRAINT RF01_METEROUTREADERLOCCODE CHECK (METEROUTREADERLOCCODE IN ('I', 'O'));
ALTER TABLE MO_METER ADD CONSTRAINT RF01_COMBIMETERFLAG CHECK (COMBIMETERFLAG IN (1,0));
ALTER TABLE MO_METER ADD CONSTRAINT RF01_REMOTEREADFLAG CHECK (REMOTEREADFLAG IN (1,0));
ALTER TABLE MO_METER ADD CONSTRAINT RF01_REMOTEREADTYPE CHECK (REMOTEREADTYPE IN ('TOUCH', '1WRAD', '2WRAD', 'GPRS', 'OTHER'));
--MO_METER_READING--
ALTER TABLE MO_METER_READING ADD CONSTRAINT RF01_METERREADTYPE CHECK (METERREADTYPE IN ('I', 'P'));
ALTER TABLE MO_METER_READING ADD CONSTRAINT RF01_METERREADMETHOD CHECK (METERREADMETHOD IN ('VISUAL', 'CUSTOMER', 'REMOTE', 'ESTIMATED'));
ALTER TABLE MO_METER_READING ADD CONSTRAINT RF01_REREADFLAG CHECK (REREADFLAG IN (0,1));
ALTER TABLE MO_METER_READING ADD CONSTRAINT RF01_ROLLOVERINDICATOR CHECK (ROLLOVERINDICATOR IN (0,1));
ALTER TABLE MO_METER_READING ADD CONSTRAINT RF01_ROLLOVERFLAG CHECK (ROLLOVERFLAG IN (0,1));
ALTER TABLE MO_METER_READING ADD CONSTRAINT RF01_RDAOUTCOME CHECK (RDAOUTCOME IN ('NOT A ROLLOVER'));
ALTER TABLE MO_METER_READING ADD CONSTRAINT RF01_ESTIMATEDREADREASONCODE CHECK (ESTIMATEDREADREASONCODE IN ('DM', 'MI', 'NM', 'NA'));
ALTER TABLE MO_METER_READING ADD CONSTRAINT RF01_ESTIMATEDREADREMEDIALWORK CHECK (ESTIMATEDREADREMEDIALWORKIND IN (0,1));
ALTER TABLE MO_METER_READING ADD CONSTRAINT RF01_METERREADERASEDFLAG CHECK (METERREADERASEDFLAG IN (0,1));
ALTER TABLE MO_METER_READING ADD CONSTRAINT RF01_METERREADSETTLEMENTFLAG CHECK (METERREADSETTLEMENTFLAG IN (0,1));
--MO_ADDRESS--
ALTER TABLE MO_ADDRESS ADD CONSTRAINT RF02_UPRNREASONCODE CHECK (UPRNREASONCODE IN ('ME','SR','MT','IP','PL','BW','SP','OT'));



-------------------All statements below this point are from a previous version, naming convention changed to make redability easier--

--ALTER TABLE MO_CUSTOMER ADD CONSTRAINT CHK01_CUSTOMERCLASSIFICATION CHECK (CUSTOMERCLASSIFICATION IN ('SEMDV', 'NA'));
--ALTER TABLE MO_CUSTOMER ADD CONSTRAINT CHK01_STDINDUSTRYCLASSCODETYPE CHECK (STDINDUSTRYCLASSCODETYPE IN ('1980', '1992', '2003', '2007'));
--ALTER TABLE MO_ELIGIBLE_PREMISES ADD CONSTRAINT CHK01_OCCUPENCYSTATUS CHECK (OCCUPENCYSTATUS IN ('OCCUPIED', 'VACANT'));
--ALTER TABLE MO_ELIGIBLE_PREMISES ADD CONSTRAINT CHK01_VOABAREFRSNCODE CHECK (VOABAREFRSNCODE IN ('NR','ME','AG','SR','MT','IP','SP','OT'));
--ALTER TABLE MO_ELIGIBLE_PREMISES ADD CONSTRAINT CHK01_BUILDINGWATERSTATUS CHECK (BUILDINGWATERSTATUS IN (0,1));
--ALTER TABLE MO_ELIGIBLE_PREMISES ADD CONSTRAINT CHK01_NONPUBHEALTHRELSITE  CHECK (NONPUBHEALTHRELSITE  IN (0,1));
--ALTER TABLE MO_ELIGIBLE_PREMISES ADD CONSTRAINT CHK01_PUBHEALTHRELSITEARR CHECK (PUBHEALTHRELSITEARR IN (0,1));
--ALTER TABLE MO_ELIGIBLE_PREMISES ADD CONSTRAINT CHK02_UPRNREASONCODE CHECK (UPRNREASONCODE IN ('ME','SR','MT','IP','PL','BW','SP','OT'));
--ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT CHK01_SERVICECATEGORY CHECK (SERVICECATEGORY IN ('W','S'));
--ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT CHK01_DISCONRECONDEREGSTATUS CHECK (DISCONRECONDEREGSTATUS IN ('TDISC'));
--ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT CHK01_OTHERSERVICECATPROVIDED CHECK (OTHERSERVICECATPROVIDED IN (0,1));
--ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT CHK01_OTHERSRVREASON CHECK (OTHERSERVICECATPROVIDEDREASON IN ('NS', 'NA', 'NR'));
--ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT CHK01_MULTIPLEWHOLESALERFLAG CHECK (MULTIPLEWHOLESALERFLAG IN (0,1));
--ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT CHK01_SPIDSTATUS CHECK (SPIDSTATUS IN ('NEW', 'PARTIAL', 'TRADEABLE', 'REJECTED', 'DEREG'));
--ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT CHK01_NEWCONNECTIONTYPE CHECK (NEWCONNECTIONTYPE IN ('NEW', 'GS', 'CU'));
--ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT CHK01_ACCREDITEDENTITYFLAG CHECK (ACCREDITEDENTITYFLAG IN (0,1));
--ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT CHK01_GAPSITEALLOCATIONMETHOD CHECK (GAPSITEALLOCATIONMETHOD IN ('SEQ', 'SPID'));
--ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT CHK01_PAIRINGREFREASONCODE CHECK (PAIRINGREFREASONCODE IN ('NOSPID', 'NOTELIGIBLE'));
--ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT CHK01_LATEREGAPPLICATION CHECK (LATEREGAPPLICATION IN (0,1));
--ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT CHK01_VOLTRANSFERFLAG CHECK (VOLTRANSFERFLAG IN (0,1));
--ALTER TABLE MO_ORG ADD CONSTRAINT CHK01_RETAILERTYPE CHECK (RETAILERTYPE IN ('FULL', 'SELFSUPPLY', 'TERMINATED'));
--ALTER TABLE MO_ORG ADD CONSTRAINT CHK01_INTERIMSUPPALLOCSTAT CHECK (INTERIMSUPPLIERALLOCSTATUS IN ('OPTIN', 'OPTOUT', 'INSOLSUS', 'VOLSUS'));
--ALTER TABLE MO_ORG ADD CONSTRAINT CHK01_TRADINGPARTYSERVICECAT CHECK (TRADINGPARTYSERVICECAT IN ('W', 'S', 'WS'));
--ALTER TABLE MO_ORG ADD CONSTRAINT CHK01_GAPSITEALLOCSTATUS CHECK (GAPSITEALLOCSTATUS IN ('OPTIN', 'OPTOUT', 'INSOLSUS', 'MOSUS'));
--ALTER TABLE MO_ORG ADD CONSTRAINT CHK01_VACANCYCHARGINGMETWATER CHECK (VACANCYCHARGINGMETHODWATER IN ('VWA', 'VWB', 'VWC'));
--ALTER TABLE MO_ORG ADD CONSTRAINT CHK01_VACANCYCHARGINGMETHSEW CHECK (VACANCYCHARGINGMETHODSEWERAGE IN ('VSA', 'VSB', 'VSC', 'VSD', 'VSE'));
--ALTER TABLE MO_ORG ADD CONSTRAINT CHK01_TMPDISCONCHRGMETHODWATER CHECK (TMPDISCONCHRGMETHODWATER IN ('TWA', 'TWB', 'TWC'));
--ALTER TABLE MO_ORG ADD CONSTRAINT CHK01_TMPDISCONCHRGMETHSEW CHECK (TMPDISCONCHRGMETHODSEWERAGE IN ('TSA', 'TSB', 'TSC', 'TSD', 'TSE'));
--ALTER TABLE MO_RETAILER_REGISTRATION ADD CONSTRAINT CHK01_CANCELLATIONCODE CHECK (CANCELLATIONCODE IN ('SPERR', 'NOCON', 'DEBT', 'CON', 'SELF', 'NOTUNDERTAKER'));
--ALTER TABLE MO_RETAILER_REGISTRATION ADD CONSTRAINT CHK01_TRANSFERVALIDFLAG CHECK (TRANSFERVALIDFLAG IN (0,1));
--ALTER TABLE MO_SERVICE_COMPONENT ADD CONSTRAINT CHK01_STWSERVICETYPE CHECK (STWSERVICETYPE = (0));
--ALTER TABLE MO_SERVICE_COMPONENT ADD CONSTRAINT CHK01_SERVICECOMPONENTTYPE CHECK (SERVICECOMPONENTTYPE IN ('MPW','MNPW','AW','UW','MS','AS','US','SW','HD','TE','WCA','SCA'));
--ALTER TABLE MO_SERVICE_COMPONENT ADD CONSTRAINT CHK01_SERVICECOMPONENTENABLED CHECK (SERVICECOMPONENTENABLED IN (0,1));
--ALTER TABLE MO_SERVICE_COMPONENT ADD CONSTRAINT CHK02_SPECIALAGREEMENTFLAG CHECK (SPECIALAGREEMENTFLAG IN (0,1));
--ALTER TABLE MO_SERVICE_COMPONENT ADD CONSTRAINT CHK02_HWAYCOMMUNITYCONFLAG CHECK (HWAYCOMMUNITYCONFLAG IN (0,1));
--ALTER TABLE MO_SERVICE_COMPONENT ADD CONSTRAINT CHK01_SRFCWATERCOMMCONFLAG CHECK (SRFCWATERCOMMUNITYCONFLAG IN (0,1));
--ALTER TABLE MO_SERVICE_COMPONENT_VOL_ADJ ADD CONSTRAINT CHK02_ADJUSTMENTSVOLADJTYPE CHECK (ADJUSTMENTSVOLADJTYPE IN ('BURST', 'FIRE', 'METER'));
--ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT CHK01_SERVICECOMPTYPE CHECK (SERVICECOMPTYPE = ('TE'));
--ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT CHK01_DISCHARGEPOINTERASEFLAG CHECK (DISCHARGEPOINTERASEFLAG IN (0,1));
--ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT CHK01_RECEPTIONTREATMENTIND CHECK (RECEPTIONTREATMENTINDICATOR IN (0,1));
--ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT CHK01_PRIMARYTREATMENTIND CHECK (PRIMARYTREATMENTINDICATOR IN (0,1));
--ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT CHK01_MARINETREATMENTINDICATOR CHECK (MARINETREATMENTINDICATOR IN (0,1));
--ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT CHK01_BIOLOGICALTREATMENTIND CHECK (BIOLOGICALTREATMENTINDICATOR IN (0,1));
--ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT CHK01_SLUDGETREATMENTINDICATOR CHECK (SLUDGETREATMENTINDICATOR IN (0,1));
--ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT CHK01_AMMONIATREATMENTIND CHECK (AMMONIATREATMENTINDICATOR IN (0,1));
--ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT CHK01_TEFXTREATMENTINDICATOR CHECK (TEFXTREATMENTINDICATOR IN (0,1));
--ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT CHK01_TEFYTREATMENTINDICATOR CHECK (TEFYTREATMENTINDICATOR IN (0,1));
--ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT CHK01_TEFZTREATMENTINDICATOR CHECK (TEFZTREATMENTINDICATOR IN (0,1));
--ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT CHK01_SEWERAGEVOLUMEADJMENTHOD CHECK (SEWERAGEVOLUMEADJMENTHOD IN ('NONE', 'DA', 'SUBTRACT'));
--ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT CHK01_DPIDSPECIALAGREEMENT CHECK (DPIDSPECIALAGREEMENTINPLACE IN (0,1));
--ALTER TABLE MO_CALCULATED_DISCHARGE ADD CONSTRAINT CHK01_DISCHARGETYPE CHECK (DISCHARGETYPE IN ('CONTAMINATED', 'DELAYED', 'ESTIMATED', 'TANKERED', 'GENERIC'));
--ALTER TABLE MO_CALCULATED_DISCHARGE ADD CONSTRAINT CHK01_SUBMISSIONFREQ CHECK (SUBMISSIONFREQ IN ('B', 'M'));
--ALTER TABLE MO_DISCHARGE_POINT_VOLMET_ADJ ADD CONSTRAINT CHK01_ADJUSTMENTSVOLADJTYPE CHECK (ADJUSTMENTSVOLADJTYPE IN ('BURST', 'FIRE', 'METER'));
--ALTER TABLE MO_METER ADD CONSTRAINT CHK01_METERERASEDFLAG CHECK (METERERASEDFLAG IN (0,1));
--ALTER TABLE MO_METER ADD CONSTRAINT CHK01_NONMARKETMETERFLAG CHECK (NONMARKETMETERFLAG IN (0,1));
--ALTER TABLE MO_METER ADD CONSTRAINT CHK01_INSTALLEDBYACCREDITED CHECK (INSTALLEDBYACCREDITEDENTITY IN (0,1));
--ALTER TABLE MO_METER ADD CONSTRAINT CHK01_METERTREATMENT CHECK (METERTREATMENT IN ('POTABLE', 'NONPOTABLE', 'PRIVATEWATER', 'PRIVATETE', 'SEWERAGE', 'CROSSBORDER'));
--ALTER TABLE MO_METER ADD CONSTRAINT CHK01_MEASUREUNITFREEATMETER CHECK (MEASUREUNITFREEATMETER IN ('METRICm3', 'METRICNONm3'));
--ALTER TABLE MO_METER ADD CONSTRAINT CHK01_METERADDITIONREASON CHECK (METERADDITIONREASON IN ('ADD', 'EXCHANGE'));
--ALTER TABLE MO_METER ADD CONSTRAINT CHK01_METERREMOVALREASON CHECK (METERREMOVALREASON IN ('REMOVE', 'EXCHANGE'));
--ALTER TABLE MO_METER ADD CONSTRAINT CHK01_METERREADMINFREQUENCY CHECK (METERREADMINFREQUENCY IN ('B','M'));
--ALTER TABLE MO_METER ADD CONSTRAINT CHK01_DATALOGGERWHOLESALER CHECK (DATALOGGERWHOLESALER IN (0,1));
--ALTER TABLE MO_METER ADD CONSTRAINT CHK01_METERLOCATIONCODE CHECK (METERLOCATIONCODE IN ('I', 'O'));
--ALTER TABLE MO_METER ADD CONSTRAINT CHK01_METEROUTREADERLOCCODE CHECK (METEROUTREADERLOCCODE IN ('I', 'O'));
--ALTER TABLE MO_METER ADD CONSTRAINT CHK01_COMBIMETERFLAG CHECK (COMBIMETERFLAG IN (1,0));
--ALTER TABLE MO_METER ADD CONSTRAINT CHK01_REMOTEREADFLAG CHECK (REMOTEREADFLAG IN (1,0));
--ALTER TABLE MO_METER ADD CONSTRAINT CHK01_REMOTEREADTYPE CHECK (REMOTEREADTYPE IN ('TOUCH', '1WRAD', '2WRAD', 'GPRS', 'OTHER'));
--ALTER TABLE MO_METER_READING ADD CONSTRAINT CHK01_METERREADTYPE CHECK (METERREADTYPE IN ('I', 'P'));
--ALTER TABLE MO_METER_READING ADD CONSTRAINT CHK01_METERREADMETHOD CHECK (METERREADMETHOD IN ('VISUAL', 'CUSTOMER', 'REMOTE', 'ESTIMATED'));
--ALTER TABLE MO_METER_READING ADD CONSTRAINT CHK01_REREADFLAG CHECK (REREADFLAG IN (0,1));
--ALTER TABLE MO_METER_READING ADD CONSTRAINT CHK01_ROLLOVERINDICATOR CHECK (ROLLOVERINDICATOR IN (0,1));
--ALTER TABLE MO_METER_READING ADD CONSTRAINT CHK01_ROLLOVERFLAG CHECK (ROLLOVERFLAG IN (0,1));
--ALTER TABLE MO_METER_READING ADD CONSTRAINT CHK01_RDAOUTCOME CHECK (RDAOUTCOME IN ('NOT A ROLLOVER'));
--ALTER TABLE MO_METER_READING ADD CONSTRAINT CHK01_ESTIMATEDREADREASONCODE CHECK (ESTIMATEDREADREASONCODE IN ('DM', 'MI', 'NM', 'NA'));
--ALTER TABLE MO_METER_READING ADD CONSTRAINT CHK01_ESTIMATEDREADREMEDIAL CHECK (ESTIMATEDREADREMEDIALWORKIND IN (0,1));
--ALTER TABLE MO_METER_READING ADD CONSTRAINT CHK01_METERREADERASEDFLAG CHECK (METERREADERASEDFLAG IN (0,1));
--ALTER TABLE MO_METER_READING ADD CONSTRAINT CHK01_METERREADSETTLEMENTFLAG CHECK (METERREADSETTLEMENTFLAG IN (0,1));
--ALTER TABLE MO_ADDRESS ADD CONSTRAINT CHK01_UPRNREASONCODE CHECK (UPRNREASONCODE IN ('ME','SR','MT','IP','PL','BW','SP','OT'));
--
----TARIFF
--ALTER TABLE MO_TARIFF ADD CONSTRAINT CHK01_TARIFFSTATUS CHECK (TARIFFSTATUS IN ('ACTIVE', 'LEGACY', 'RETIRED'));
commit;
exit;
