------------------------------------------------------------------------------
-- TASK					: 	MOSL RDBMS DROP 
--
-- AUTHOR         		: 	Nigel Henderson
--
-- FILENAME       		: 	02_DDL_MOSL_FK_DROP_ALL.sql
--
-- CREATED        		: 	22/02/2016
--	
-- Subversion $Revision: 4023 $
--
-- DESCRIPTION 		   	: 	Drops all foreign keys
--
-- NOTES  				:	Used in conjunction with the following scripts to re-initialise the
-- 							database.  When re-creating the database run the scripts in order
-- 							as detailed below (.sql).
--
-- ASSOCIATED SCRIPTS  	:	01_DDL_MOSL_DROP_STATIC_DATA_ALL.sql
--					03_DDL_MOSL_TABLES_DROP_ALL.sql
--					04_DDL_MOSL_DROP_SEQUENCES_ALL
--
--
--
---------------------------- Modification History ----------------------------------------------------------
--
-- Version     		Date          Author         		Description
-- ---------      	---------------     -------            	 ------------------------------------------------
-- V0.01       	15/02/2016    	N.Henderson     	Initial version after generation from Excel
-- V0.02		04/03/2016		N.Henderson		Drop of FK FK_SERVICECOMPONENTREF_PK03 commented out
-- 									as it is being dropped in PATCH 01 (MO_P0001.sql)
--
--
--
--
-- 
------------------------------------------------------------------------------------------------------------

--DROP FK
--CORE
ALTER TABLE MO_CUSTOMER DROP CONSTRAINT FK_STWPROPERTYNUMBER_PK01 ;
ALTER TABLE MO_ELIGIBLE_PREMISES DROP CONSTRAINT FK_CUSTOMERID_PK;
ALTER TABLE MO_SUPPLY_POINT DROP CONSTRAINT FK_STWPROPERTYNUMBER_PK02 ;
ALTER TABLE MO_SUPPLY_POINT DROP CONSTRAINT FK_CORESPID_PK;
ALTER TABLE MO_SUPPLY_POINT DROP CONSTRAINT FK_RETAILERID_PK01 ;
ALTER TABLE MO_SUPPLY_POINT DROP CONSTRAINT FK_WHOLESALERID_PK ;
ALTER TABLE MO_RETAILER_REGISTRATION DROP CONSTRAINT FK_RETAILERID_PK02 ;
ALTER TABLE MO_RETAILER_REGISTRATION DROP CONSTRAINT FK_SPID_PK01 ;
ALTER TABLE MO_SERVICE_COMPONENT DROP CONSTRAINT FK_SERVICECOMPONENTREF_PK01 ;
ALTER TABLE MO_SERVICE_COMPONENT DROP CONSTRAINT FK_TARIFFCODE_PK ;
ALTER TABLE MO_SERVICE_COMPONENT DROP CONSTRAINT FK_SPID_PK02 ;
ALTER TABLE MO_SERVICE_COMPONENT DROP CONSTRAINT FK_DPID_PK01;
ALTER TABLE MO_SERVICE_COMPONENT_VOL_ADJ DROP CONSTRAINT FK_SERVICECOMPONENTREF_PK02 ;
ALTER TABLE MO_DISCHARGE_POINT DROP CONSTRAINT FK_SPID_PK ;
ALTER TABLE MO_CALCULATED_DISCHARGE DROP CONSTRAINT FK_DPID_PK02 ;
ALTER TABLE MO_DISCHARGED_VOLUME DROP CONSTRAINT FK_DPID_PK03 ;
ALTER TABLE MO_DISCHARGE_POINT_VOLMET_ADJ DROP CONSTRAINT FK_DPID_PK04 ;
ALTER TABLE MO_METER DROP CONSTRAINT FK_SPID_PK03;
ALTER TABLE MO_METER_READING DROP CONSTRAINT FK_MANUFACTURER_PK01 ;
ALTER TABLE MO_METER_READING DROP CONSTRAINT FK_MANUFACTURERSERIALNUM_PK01 ;
ALTER TABLE MO_METER_DPIDXREF DROP CONSTRAINT FK_MANUFACTURER_PK02 ;
ALTER TABLE MO_METER_DPIDXREF DROP CONSTRAINT FK_MANUFACTURERSERIALNUM_PK02;
ALTER TABLE MO_METER_DPIDXREF DROP CONSTRAINT FK_DPID_PK05 ;
ALTER TABLE MO_CUST_ADDRESS DROP CONSTRAINT FK_ADDRESS_PK01 ;
ALTER TABLE MO_CUST_ADDRESS DROP CONSTRAINT FK_CUSTOMERNUMBER_PK ;
ALTER TABLE MO_PROPERTY_ADDRESS DROP CONSTRAINT FK_ADDRESS_PK02 ;
ALTER TABLE MO_PROPERTY_ADDRESS DROP CONSTRAINT FK_STWPROPERTYNUMBER_PK03 ;
ALTER TABLE MO_METER_ADDRESS DROP CONSTRAINT FK_METERSERIALNUMBER_PK ;
ALTER TABLE MO_METER_ADDRESS DROP CONSTRAINT FK_ADDRESS_PK03;
--DROP FK
--TARIFF

--See above
--ALTER TABLE MO_TARIFF DROP CONSTRAINT FK_SERVICECOMPONENTREF_PK03;

ALTER TABLE MO_TARIFF_VERSION DROP CONSTRAINT FK_MO_TARIFF_CODE ;
ALTER TABLE MO_TARIFF_TYPE_MPW DROP CONSTRAINT FK_TARIFF_VERSION_PK_MPW ;
ALTER TABLE MO_MPW_METER_MWMFC DROP CONSTRAINT FK_TARIFF_TYPE_PK01 ;
ALTER TABLE MO_MPW_BLOCK_MWBT DROP CONSTRAINT FK_TARIFF_TYPE_PK02;
ALTER TABLE MO_MPW_STANDBY_MWCAPCHG DROP CONSTRAINT FK_TARIFF_TYPE_PK03 ;
ALTER TABLE MO_TARIFF_TYPE_MNPW DROP CONSTRAINT FK_TARIFF_VERSION_PK_MNPW ;
ALTER TABLE MO_MNPW_METER_MWMFC DROP CONSTRAINT FK_TARIFF_TYPE_PK04 ;
ALTER TABLE MO_MNPW_BLOCK_MWBT DROP CONSTRAINT FK_TARIFF_TYPE_PK05;
ALTER TABLE MO_MNPW_STANDBY_MWCAPCHG DROP CONSTRAINT FK_TARIFF_TYPE_PK06 ;
ALTER TABLE MO_TARIFF_TYPE_AW DROP CONSTRAINT FK_TARIFF_VERSION_PK_AW ;
ALTER TABLE MO_AW_METER_AWMFC DROP CONSTRAINT FK_TARIFF_TYPE_PK07 ;
ALTER TABLE MO_AW_BAND_CHARGE DROP CONSTRAINT FK_TARIFF_TYPE_PK08;
ALTER TABLE MO_TARIFF_TYPE_UW DROP CONSTRAINT FK_TARIFF_VERSION_PK_UW ;
ALTER TABLE MO_UW_METER_UWPFC DROP CONSTRAINT FK_TARIFF_TYPE_PK09 ;
ALTER TABLE MO_TARIFF_TYPE_MS DROP CONSTRAINT FK_TARIFF_VERSION_PK_MS ;
ALTER TABLE MO_MS_BLOCK_MSBT DROP CONSTRAINT FK_TARIFF_TYPE_PK10 ;
ALTER TABLE MO_MS_METER_MSMFC DROP CONSTRAINT FK_TARIFF_TYPE_PK11 ;
ALTER TABLE MO_TARIFF_TYPE_AS DROP CONSTRAINT FK_TARIFF_VERSION_PK_AS ;
ALTER TABLE MO_AS_METER_ASMFC DROP CONSTRAINT FK_TARIFF_TYPE_PK12;
ALTER TABLE MO_AS_BAND_CHARGE DROP CONSTRAINT FK_TARIFF_TYPE_PK13 ;
ALTER TABLE MO_TARIFF_TYPE_US DROP CONSTRAINT FK_TARIFF_VERSION_PK_US;
ALTER TABLE MO_US_METER_USPFC DROP CONSTRAINT FK_TARIFF_TYPE_PK14;
ALTER TABLE MO_TARIFF_TYPE_SW DROP CONSTRAINT FK_TARIFF_VERSION_PK_SW ;
ALTER TABLE MO_SW_AREA_BAND DROP CONSTRAINT FK_TARIFF_TYPE_PK15 ;
ALTER TABLE MO_SW_BAND_CHARGE DROP CONSTRAINT FK_TARIFF_TYPE_PK16 ;
ALTER TABLE MO_SW_BLOCK_SWBT DROP CONSTRAINT FK_TARIFF_TYPE_PK17;
ALTER TABLE MO_SW_METER_SWMFC DROP CONSTRAINT FK_TARIFF_TYPE_PK18 ;
ALTER TABLE MO_TARIFF_TYPE_HD DROP CONSTRAINT FK_TARIFF_VERSION_PK_HD ;
ALTER TABLE MO_HD_AREA_BAND DROP CONSTRAINT FK_TARIFF_TYPE_PK19 ;
ALTER TABLE MO_HD_BAND_CHARGE DROP CONSTRAINT FK_TARIFF_TYPE_PK20;
ALTER TABLE MO_HD_BLOCK_HDBT DROP CONSTRAINT FK_TARIFF_TYPE_PK21;
ALTER TABLE MO_HD_METER_HDMFC DROP CONSTRAINT FK_TARIFF_TYPE_PK22 ;
ALTER TABLE MO_TARIFF_TYPE_TE DROP CONSTRAINT FK_TARIFF_VERSION_PK_TE ;
ALTER TABLE MO_TE_BAND_CHARGE DROP CONSTRAINT FK_TARIFF_TYPE_PK23;
ALTER TABLE MO_TE_BLOCK_ROBT DROP CONSTRAINT FK_TARIFF_TYPE_PK24 ;
ALTER TABLE MO_TE_BLOCK_BOBT DROP CONSTRAINT FK_TARIFF_TYPE_PK25 ;
commit;
exit;

