--Associated Address tables for SAP
-- O.Badmus
--02/06/2016
--10/06/2016 updated 

--MO_CUST_ADDRESS
DROP TABLE MO_CUST_ADDRESS CASCADE CONSTRAINTS;
--MO_PROPERTY_ADDRESS
DROP TABLE MO_PROPERTY_ADDRESS CASCADE CONSTRAINTS;
--MO_METER_ADDRESS
DROP TABLE MO_METER_ADDRESS CASCADE CONSTRAINTS;
--MO_ADDRESS
DROP TABLE MO_ADDRESS CASCADE CONSTRAINTS;
commit;
exit;