--
-- CREATED        		: 	23/08/2016
--	
-- DESCRIPTION 		   	: 	Update columns to be nullable
--
--
--
-- Subversion $Revision: 5298 $	
--							
--
-- ASSOCIATED FILES		:	
-- ASSOCIATED SCRIPTS  	:	
--
--
---------------------------- Modification History ----------------------------------------------------------
--
-- Version   Date        Author    Description
-- --------  ----------  --------  --------------------------------------------------------------
-- V0.01		 23/08/2016  S.Badhan  Make columns nullable and add constraints.
------------------------------------------------------------------------------------------------------------

ALTER TABLE MO_ELIGIBLE_PREMISES  MODIFY PROPERTYUSECODE NULL;

ALTER TABLE MO_SERVICE_COMPONENT ADD CONSTRAINT FK_SC_PROPERTY_PK03 FOREIGN KEY (STWPROPERTYNUMBER_PK) REFERENCES MO_ELIGIBLE_PREMISES(STWPROPERTYNUMBER_PK);
ALTER TABLE MO_SERVICE_COMPONENT  MODIFY STWSERVICETYPE NULL;

ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT FK_DP_PROPERTY FOREIGN KEY (STWPROPERTYNUMBER_PK) REFERENCES MO_ELIGIBLE_PREMISES(STWPROPERTYNUMBER_PK);
ALTER TABLE MO_DISCHARGE_POINT  MODIFY DISCHARGEPOINTERASEFLAG NULL;

ALTER TABLE MO_METER ADD CONSTRAINT FK_MT_PROPERTY FOREIGN KEY (INSTALLEDPROPERTYNUMBER) REFERENCES MO_ELIGIBLE_PREMISES(STWPROPERTYNUMBER_PK);

ALTER TABLE MO_METER_READING ADD CONSTRAINT FK_MR_PROPERTY FOREIGN KEY (INSTALLEDPROPERTYNUMBER) REFERENCES MO_ELIGIBLE_PREMISES(STWPROPERTYNUMBER_PK);

ALTER TABLE MO_METER_SPID_ASSOC ADD CONSTRAINT FK_MS_PROPERTY FOREIGN KEY (STWPROPERTYNUMBER_PK) REFERENCES MO_ELIGIBLE_PREMISES(STWPROPERTYNUMBER_PK);

ALTER TABLE MO_METER_NETWORK ADD CONSTRAINT FK_MN_MAINPROPERTY FOREIGN KEY (MAIN_STWPROPERTYNUMBER_PK) REFERENCES MO_ELIGIBLE_PREMISES(STWPROPERTYNUMBER_PK);
ALTER TABLE MO_METER_NETWORK ADD CONSTRAINT FK_MN_SUBPROPERTY FOREIGN KEY (SUB_STWPROPERTYNUMBER_PK) REFERENCES MO_ELIGIBLE_PREMISES(STWPROPERTYNUMBER_PK);

ALTER TABLE MO_METER_DPIDXREF ADD CONSTRAINT FK_MD_PROPERTY FOREIGN KEY (INSTALLEDPROPERTYNUMBER) REFERENCES MO_ELIGIBLE_PREMISES(STWPROPERTYNUMBER_PK);

ALTER TABLE MO_CALCULATED_DISCHARGE  MODIFY STWACCOUNTNUMBER NULL;

ALTER TABLE MO_CALCULATED_DISCHARGE  MODIFY REFDESC NULL;

commit;
/
show errors;

exit;