load data
--
-- Subversion $Revision: 4023 $	
--
into table LU_DATALOGGERS
fields terminated by "|"
(
MANUFACTURERSERIALNUM_PK,
STWPROPERTYNUMBER_PK,
STWMETERREF_PK,
MANUFACTURER_PK,
DATALOGGERSERIALNUM,
DATALOGGERWHOLESALER,
DATALOGGERNONWHOLESALER
)
