--
-- Subversion $Revision: 4023 $	
--
load data
into table LU_DATALOGGERS_NON_WHOLESALE
fields terminated by "|"
(
NO_UTL_EQUIP,
NO_PROPERTY,
STWMETERREF_PK,
MANUFACTURER_PK,
DATALOGGERSERIALNUM,
DATALOGGERWHOLESALER,
DATALOGGERNONWHOLESALER
)

