--Statements to drop all objects associated with delivery tables
--N Henderson
--14/04/2016
--	
-- Subversion $Revision: 5675 $
--
--DROP MIG TABLES IN DELIVERY AREA
DROP TABLE MIG_BATCHSTATUS;
DROP TABLE MIG_CPLOG;
DROP TABLE MIG_CPREF;
DROP TABLE MIG_ERRORLOG;
DROP TABLE MIG_ERRREF;
DROP TABLE MIG_JOBREF;
DROP TABLE MIG_JOBSTATUS;
DROP TABLE MIG_PHASE_KEYGEN;
commit;
exit;




