-- Subversion $Revision: 5193 $
--
--DISABLE FOREIGN CONSTRAINTS
ALTER TABLE DEL_METER_DISCHARGE_POINT DISABLE constraint FK02_METER_MAN_SERIAL_COMP;
ALTER TABLE DEL_DISCHARGE_POINT DISABLE CONSTRAINT FK01_SPID_PK;
ALTER TABLE DEL_METER_DISCHARGE_POINT DISABLE CONSTRAINT FK01_DPID_PK;
ALTER TABLE DEL_CALCULATED_DISCHARGE DISABLE CONSTRAINT FK02_DPID_PK;

--Truncate DEL tables
TRUNCATE TABLE DEL_SERVICE_COMPONENT;
TRUNCATE TABLE DEL_METER;
TRUNCATE TABLE DEL_METER_SUPPLY_POINT;
TRUNCATE TABLE DEL_METER_NETWORK;
TRUNCATE TABLE DEL_METER_READING;
TRUNCATE TABLE DEL_DISCHARGE_POINT;
TRUNCATE TABLE DEL_METER_DISCHARGE_POINT;
TRUNCATE TABLE DEL_CALCULATED_DISCHARGE;
TRUNCATE TABLE DEL_SUPPLY_POINT;
--TRUNCATE TABLE DEL_SUPPLY_POINT_ARC;
--TRUNCATE TABLE DEL_SERVICE_COMPONENT_ARC;
--TRUNCATE TABLE DEL_METER_ARC;
--TRUNCATE TABLE DEL_METER_SUPPLY_POINT_ARC;
--TRUNCATE TABLE DEL_METER_NETWORK_ARC;
--TRUNCATE TABLE DEL_METER_READING_ARC;
--TRUNCATE TABLE DEL_DISCHARGE_POINT_ARC;
--TRUNCATE TABLE DEL_METER_DISCHARGE_POINT_ARC;
--TRUNCATE TABLE DEL_CALCULATED_DISCHARGE_ARC;

--RE-ENABLE FOREIGN CONSTRAINTS
ALTER TABLE DEL_METER_DISCHARGE_POINT ENABLE constraint FK02_METER_MAN_SERIAL_COMP;
ALTER TABLE DEL_DISCHARGE_POINT ENABLE CONSTRAINT FK01_SPID_PK;
ALTER TABLE DEL_METER_DISCHARGE_POINT ENABLE CONSTRAINT FK01_DPID_PK;
ALTER TABLE DEL_CALCULATED_DISCHARGE ENABLE CONSTRAINT FK02_DPID_PK;

-- Execute the main batch
set serveroutput on;
exec  P_MIG_BATCH.P_STARTBATCH();
set serveroutput off;
exit;
