--
-- 
-- Author	N.Henderson
-- Version	0.6
-- Subversion $Revision: 4475 $
-- Notes	Initial build
-- 		Added scripts to drop and re-create all of the BT tables (12/04/2016), NJH
--  		Added the drop and create scripts for the delivery tables (14/04/2016), NJH
-- 0.3		N.Henderson. -- Reordered the run oder.  Added some more logging features
-- 0.4		N.Henderson  -- Copy of original file and added MIG related tables and views
-- 0.5		M.Marron  -- Updated the SQLLDR commands to enable the data loads to work in all enviroments
-- 0.6		M.Marron  -- Converted Script for SAP Migration
-- 0.7    K.Burton  -- added constraint disable, truncate table and constraint enable commands

-- DISABLE FOREIGN KEYS
ALTER TABLE SAP_DEL_REG DISABLE CONSTRAINT FK04_DEV_LEGACYRECNUM;

ALTER TABLE SAP_DEL_PODSRV DISABLE CONSTRAINT FK01_PODSRV_SPID;
ALTER TABLE SAP_DEL_PODMO DISABLE CONSTRAINT FK01_PODMO_LEGACYRECNUM;
ALTER TABLE SAP_DEL_PODMO DISABLE CONSTRAINT FK01_PODMO_SPID;

ALTER TABLE SAP_DEL_COBMO DISABLE CONSTRAINT FK01_COBMO_LEGACYRECNUM;
ALTER TABLE SAP_DEL_PREM DISABLE CONSTRAINT FK01_PREM_LEGACYRECNUM;

ALTER TABLE SAP_DEL_DEVMO DISABLE CONSTRAINT FK01_DMO_LEGACYRECNUM;
ALTER TABLE SAP_DEL_DEVCHAR DISABLE CONSTRAINT FK01_DEC_LEGACYRECNUM;
ALTER TABLE SAP_DEL_DVLCRT DISABLE CONSTRAINT FK01_DLC_LEGACYRECNUM;
ALTER TABLE SAP_DEL_DVLCRT DISABLE CONSTRAINT FK02_DLC_LEGACYRECNUM;
ALTER TABLE SAP_DEL_DVLUPDATE DISABLE CONSTRAINT FK01_DLU_LEGACYRECNUM;

ALTER TABLE SAP_DEL_METER_READ DISABLE CONSTRAINT FK02_DEV_LEGACYRECNUM;

ALTER TABLE SAP_DEL_SCMMO DISABLE CONSTRAINT FK01_SCMMO_LEGACYRECNUM;
ALTER TABLE SAP_DEL_SCMTE DISABLE CONSTRAINT FK01_SCMTE_LEGACYRECNUM;
ALTER TABLE SAP_DEL_SCMTEMO DISABLE CONSTRAINT FK01_TEMO_LEGACYRECNUM;

ALTER TABLE SAP_DEL_METER_INSTALL DISABLE CONSTRAINT FK03_DEV_LEGACYRECNUM;
--ALTER TABLE SAP_DEL_METER_INSTALL DISABLE CONSTRAINT FK01_COM_LEGACYRECNUM;

--Truncate DEL tables
TRUNCATE TABLE SAP_DEL_OUTPUT;

TRUNCATE TABLE SAP_DEL_REG;
TRUNCATE TABLE SAP_DEL_BP;

TRUNCATE TABLE SAP_DEL_PODSRV;
TRUNCATE TABLE SAP_DEL_PODMO;
TRUNCATE TABLE SAP_DEL_POD;

TRUNCATE TABLE SAP_DEL_METER_INSTALL;
TRUNCATE TABLE SAP_DEL_METER_READ;

TRUNCATE TABLE SAP_DEL_DVLUPDATE;
TRUNCATE TABLE SAP_DEL_DVLCRT;
TRUNCATE TABLE SAP_DEL_DEVCHAR;
TRUNCATE TABLE SAP_DEL_DEVMO;
TRUNCATE TABLE SAP_DEL_DEV;

TRUNCATE TABLE SAP_DEL_SCMTEMO;
TRUNCATE TABLE SAP_DEL_SCMTE;
TRUNCATE TABLE SAP_DEL_SCMMO;
TRUNCATE TABLE SAP_DEL_SCM;

TRUNCATE TABLE SAP_DEL_PREM;
TRUNCATE TABLE SAP_DEL_COBMO;
TRUNCATE TABLE SAP_DEL_COB;

-- ENABLE FOREIGN KEYS
ALTER TABLE SAP_DEL_REG ENABLE CONSTRAINT FK04_DEV_LEGACYRECNUM;

ALTER TABLE SAP_DEL_PODSRV ENABLE CONSTRAINT FK01_PODSRV_SPID;
ALTER TABLE SAP_DEL_PODMO ENABLE CONSTRAINT FK01_PODMO_LEGACYRECNUM;
ALTER TABLE SAP_DEL_PODMO ENABLE CONSTRAINT FK01_PODMO_SPID;

ALTER TABLE SAP_DEL_COBMO ENABLE CONSTRAINT FK01_COBMO_LEGACYRECNUM;
ALTER TABLE SAP_DEL_PREM ENABLE CONSTRAINT FK01_PREM_LEGACYRECNUM;

ALTER TABLE SAP_DEL_DEVMO ENABLE CONSTRAINT FK01_DMO_LEGACYRECNUM;
ALTER TABLE SAP_DEL_DEVCHAR ENABLE CONSTRAINT FK01_DEC_LEGACYRECNUM;
ALTER TABLE SAP_DEL_DVLCRT ENABLE CONSTRAINT FK01_DLC_LEGACYRECNUM;
ALTER TABLE SAP_DEL_DVLCRT ENABLE CONSTRAINT FK02_DLC_LEGACYRECNUM;
ALTER TABLE SAP_DEL_DVLUPDATE ENABLE CONSTRAINT FK01_DLU_LEGACYRECNUM;

ALTER TABLE SAP_DEL_METER_READ ENABLE CONSTRAINT FK02_DEV_LEGACYRECNUM;

ALTER TABLE SAP_DEL_SCMMO ENABLE CONSTRAINT FK01_SCMMO_LEGACYRECNUM;
ALTER TABLE SAP_DEL_SCMTE ENABLE CONSTRAINT FK01_SCMTE_LEGACYRECNUM;
ALTER TABLE SAP_DEL_SCMTEMO ENABLE CONSTRAINT FK01_TEMO_LEGACYRECNUM;

ALTER TABLE SAP_DEL_METER_INSTALL ENABLE CONSTRAINT FK03_DEV_LEGACYRECNUM;
--ALTER TABLE SAP_DEL_METER_INSTALL ENABLE CONSTRAINT FK01_COM_LEGACYRECNUM;

-- Execute the main batch
set serveroutput on;
exec  P_MIG_BATCH.P_STARTBATCH();
set serveroutput off;
exit;
