--*** SCRIPT TO GENERATE TABLE STAT SCRIPTS
--SELECT 'EXEC DBMS_STATS.EXPORT_TABLE_STATS(''SAPDEL'',''' || table_name || ''',NULL,''DELSTATSTABLE''); '
--from dba_tables where owner = 'SAPDEL' and table_name NOT LIKE '%$%' AND status = 'VALID'
--AND table_name <> 'DELSTATSTABLE'
--ORDER BY 1;

--1. **** DROP PREVIOUS STATS TABLE
DROP TABLE SAPDEL.DELSTATSTABLE PURGE;

--2. **** CREATE STATS TABLE
EXEC DBMS_STATS.CREATE_STAT_TABLE('SAPDEL','DELSTATSTABLE');

--3. **** EXPORT STATS
EXEC DBMS_STATS.EXPORT_SCHEMA_STATS('SAPDEL','DELSTATSTABLE');

EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','MIG_BATCHSTATUS',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','MIG_CPLOG',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','MIG_CPREF',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','MIG_ERRORLOG',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','MIG_ERRREF',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','MIG_JOBREF',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','MIG_JOBSTATUS',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_BP',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_COB',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_COBMO',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_DEV',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_DEVCHAR',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_DEVMO',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_DVLCRT',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_DVLUPDATE',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_METER_INSTALL',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_METER_READ',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_OUTPUT',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_POD',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_PODMO',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_PODSRV',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_PREM',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_REG',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_SCM',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_SCMMO',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_SCMTE',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_DEL_SCMTEMO',NULL,'DELSTATSTABLE'); 
EXEC DBMS_STATS.EXPORT_TABLE_STATS('SAPDEL','SAP_TMP',NULL,'DELSTATSTABLE'); 

commit;
exit;