--*** SCRIPT TO GENERATE TABLE STAT SCRIPTS
--SELECT 'EXEC DBMS_STATS.IMPORT_TABLE_STATS(''RECEPTION'',''' || table_name || ''',NULL,''RECSTATSTABLE''); '
--from dba_tables where owner = 'RECEPTION' and table_name NOT LIKE '%$%' AND status = 'VALID'
--AND table_name <> 'RECSTATSTABLE'
--ORDER BY 1;

--4. **** IMPORT PREVIOUS STATS
EXEC DBMS_STATS.IMPORT_TABLE_STATS('RECEPTION','SAP_CALCULATED_DISCHARGE',NULL,'RECSTATSTABLE'); 
EXEC DBMS_STATS.IMPORT_TABLE_STATS('RECEPTION','SAP_DISCHARGE_POINT',NULL,'RECSTATSTABLE'); 
EXEC DBMS_STATS.IMPORT_TABLE_STATS('RECEPTION','SAP_METER',NULL,'RECSTATSTABLE'); 
EXEC DBMS_STATS.IMPORT_TABLE_STATS('RECEPTION','SAP_METER_DISCHARGE_POINT',NULL,'RECSTATSTABLE'); 
EXEC DBMS_STATS.IMPORT_TABLE_STATS('RECEPTION','SAP_METER_NETWORK',NULL,'RECSTATSTABLE'); 
EXEC DBMS_STATS.IMPORT_TABLE_STATS('RECEPTION','SAP_METER_READING',NULL,'RECSTATSTABLE'); 
EXEC DBMS_STATS.IMPORT_TABLE_STATS('RECEPTION','SAP_METER_SUPPLY_POINT',NULL,'RECSTATSTABLE'); 
EXEC DBMS_STATS.IMPORT_TABLE_STATS('RECEPTION','SAP_SERVICE_COMPONENT',NULL,'RECSTATSTABLE'); 
EXEC DBMS_STATS.IMPORT_TABLE_STATS('RECEPTION','SAP_SUPPLY_POINT',NULL,'RECSTATSTABLE'); 
EXEC DBMS_STATS.IMPORT_TABLE_STATS('RECEPTION','SAP_SUPPLY_POINT_DWRCYMRU',NULL,'RECSTATSTABLE'); 
EXEC DBMS_STATS.IMPORT_TABLE_STATS('RECEPTION','TVMNHHDTL',NULL,'RECSTATSTABLE'); 

commit;
exit;