--*** SCRIPT TO INSERT MIG_PHASE_KEYGEN FOR SELECTING WHICH KEYGEN DATASET TO RUN
-- FOR ALL PHASE NUMBERS

-- v 1.01    22/11//2016  D.Cheung  Separate phases for SAP

---**** Run scripts for all phases to insert MIG_PHASE_KEYGEN records

INSERT INTO MIG_PHASE_KEYGEN (PHASE, TS_BATCH, FG_INLC_BATCH, FG_KEYGEN_PRC, TS_KEYGEN, NO_BATCH) VALUES (1, NULL, 'Y', 'N', NULL, NULL);
INSERT INTO MIG_PHASE_KEYGEN (PHASE, TS_BATCH, FG_INLC_BATCH, FG_KEYGEN_PRC, TS_KEYGEN, NO_BATCH) VALUES (2, NULL, 'Y', 'N', NULL, NULL);
INSERT INTO MIG_PHASE_KEYGEN (PHASE, TS_BATCH, FG_INLC_BATCH, FG_KEYGEN_PRC, TS_KEYGEN, NO_BATCH) VALUES (3, NULL, 'Y', 'N', NULL, NULL);
INSERT INTO MIG_PHASE_KEYGEN (PHASE, TS_BATCH, FG_INLC_BATCH, FG_KEYGEN_PRC, TS_KEYGEN, NO_BATCH) VALUES (4, NULL, 'Y', 'N', NULL, NULL);
INSERT INTO MIG_PHASE_KEYGEN (PHASE, TS_BATCH, FG_INLC_BATCH, FG_KEYGEN_PRC, TS_KEYGEN, NO_BATCH) VALUES (5, NULL, 'Y', 'N', NULL, NULL);
INSERT INTO MIG_PHASE_KEYGEN (PHASE, TS_BATCH, FG_INLC_BATCH, FG_KEYGEN_PRC, TS_KEYGEN, NO_BATCH) VALUES (6, NULL, 'Y', 'N', NULL, NULL);
INSERT INTO MIG_PHASE_KEYGEN (PHASE, TS_BATCH, FG_INLC_BATCH, FG_KEYGEN_PRC, TS_KEYGEN, NO_BATCH) VALUES (7, NULL, 'Y', 'N', NULL, NULL);
INSERT INTO MIG_PHASE_KEYGEN (PHASE, TS_BATCH, FG_INLC_BATCH, FG_KEYGEN_PRC, TS_KEYGEN, NO_BATCH) VALUES (8, NULL, 'Y', 'N', NULL, NULL);
INSERT INTO MIG_PHASE_KEYGEN (PHASE, TS_BATCH, FG_INLC_BATCH, FG_KEYGEN_PRC, TS_KEYGEN, NO_BATCH) VALUES (9, NULL, 'Y', 'N', NULL, NULL);

commit;
exit;