--*** SCRIPT TO INSERT MIG_PHASE_KEYGEN FOR SELECTING WHICH KEYGEN DATASET TO RUN
-- FOR SINGLE INPUTTED PHASE NUMBER


---**** Run script based on input number to insert MIG_PHASE_KEYGEN records (setting flags for MO or SAP appropriately)
--INSERT INTO MOUTRAN.MIG_PHASE_KEYGEN (MO_PHASE, TS_MO, FG_MO, FG_KEYGEN_PRC, TS_KEYGEN, SAP_PHASE, TS_SAP, FG_SAP, NO_BATCH) VALUES (&1,NULL,'Y','N',NULL,'N',NULL,'N',NULL);
INSERT INTO MIG_PHASE_KEYGEN (PHASE, TS_BATCH, FG_INLC_BATCH, FG_KEYGEN_PRC, TS_KEYGEN, NO_BATCH) VALUES (&1, NULL, 'Y', 'N', NULL, NULL);
commit;
exit;