--
-- CREATED        		: 	06/05/2016
--	
-- DESCRIPTION 		   	: 	Add Tariff Constraints
--
--
-- Subversion $Revision: 4023 $	
--							
--
-- ASSOCIATED FILES		:	
-- ASSOCIATED SCRIPTS  	:	
--
--
---------------------------- Modification History ----------------------------------------------------------
--
-- Version     	Date            Author     Description
-- ---------    ----------      -------    ------------------------------------------------
-- V0.02		20/05/2016      S.Badhan	Change name of constrainst for effective date check (too long)
--                                         Add constrainst CHK02_SERVICECOMPONENTTYPE already set up in 
-- V0.01		06/05/2016      K.Burton	Add constraints to MOUTRAN tariff tables
------------------------------------------------------------------------------------------------------------
-- CHANGES
------------------------------------------------------------------------------------------------------------
ALTER TABLE MO_TARIFF ADD CONSTRAINT CH01_APPLICABLESERVICECOMP CHECK (APPLICABLESERVICECOMPONENT IN ('MPW','MNPW','AW','UW','MS','AS','US','SW','HD','TE','WCA','SCA'));
ALTER TABLE MO_TARIFF ADD CONSTRAINT CHK02_SERVICECOMPONENTTYPE CHECK (SERVICECOMPONENTTYPE IN ('MPW','MNPW','AW','UW','MS','AS','US','SW','HD','TE','WCA','SCA'));

ALTER TABLE MO_TARIFF ADD CONSTRAINT CH02_TARIFFSTATUS CHECK (TARIFFSTATUS IN ('ACTIVE','LEGACY'));
ALTER TABLE MO_TARIFF ADD CONSTRAINT CH03_TARIFFLEGACYEFFROMDATE CHECK ((TARIFFLEGACYEFFECTIVEFROMDATE IS NULL AND TARIFFSTATUS = 'ACTIVE') OR (TARIFFLEGACYEFFECTIVEFROMDATE IS NOT NULL AND TARIFFSTATUS = 'LEGACY'));


ALTER TABLE MO_TARIFF_TYPE_UW ADD CONSTRAINT CH01_UWRVTHRESHOLD CHECK ((UWRVPOUNDAGE IS NULL AND UWRVTHRESHOLD IS NULL) OR (UWRVPOUNDAGE IS NOT NULL AND UWRVTHRESHOLD IS NOT NULL));
ALTER TABLE MO_TARIFF_TYPE_US ADD CONSTRAINT CH01_USRVTHRESHOLD CHECK ((USRVPOUNDAGE IS NULL AND USRVTHRESHOLD IS NULL) OR (USRVPOUNDAGE IS NOT NULL AND USRVTHRESHOLD IS NOT NULL));
ALTER TABLE MO_TARIFF_TYPE_SW ADD CONSTRAINT CH01_SWRVTHRESHOLD CHECK ((SWRVPOUNDAGE IS NULL AND SWRVTHRESHOLD IS NULL) OR (SWRVPOUNDAGE IS NOT NULL AND SWRVTHRESHOLD IS NOT NULL));
ALTER TABLE MO_TARIFF_TYPE_HD ADD CONSTRAINT CH01_HDRVTHRESHOLD CHECK ((HDRVPOUNDAGE IS NULL AND HDRVTHRESHOLD IS NULL) OR (HDRVPOUNDAGE IS NOT NULL AND HDRVTHRESHOLD IS NOT NULL));

commit;
exit;