--Create table BT_SPR_METER 
--N.Henderson - 12/04/2016
-- Subversion $Revision: 4023 $
--Attempt to drop the table first. Will generate warnings if does not
--exist but can be ignored.

--DROP TABLE BT_SPR_METER PURGE;


  CREATE TABLE BT_SPR_METER 
   (CD_COMPANY_SYSTEM CHAR(4 BYTE) NOT NULL ENABLE, 
	NO_ACCOUNT NUMBER(9,0), 
	NO_PROPERTY NUMBER(9,0), 
	CD_SERVICE_PROV VARCHAR2(5 BYTE), 
	NO_COMBINE_054 NUMBER(9,0), 
	NO_SERV_PROV NUMBER(3,0), 
	DT_START_054 DATE, 
	DT_END_054 DATE, 
	NM_LOCAL_SERVICE VARCHAR2(25 BYTE), 
	NO_COMBINE_034 NUMBER(9,0) NOT NULL ENABLE, 
	DT_START_034 DATE NOT NULL ENABLE, 
	DT_START_LR_034 DATE NOT NULL ENABLE, 
	DT_END_034 DATE, 
	FG_ADD_SUBTRACT CHAR(1 BYTE) NOT NULL ENABLE, 
	NO_UTL_EQUIP CHAR(12 BYTE) NOT NULL ENABLE, 
	NO_EQUIPMENT NUMBER(9,0) NOT NULL ENABLE, 
	NO_COMBINE_043 NUMBER(9,0) NOT NULL ENABLE, 
	NO_REGISTER NUMBER(2,0) NOT NULL ENABLE, 
	TP_EQUIPMENT CHAR(2 BYTE) NOT NULL ENABLE, 
	CD_TARIFF CHAR(10 BYTE) NOT NULL ENABLE, 
	NO_TARIFF_GROUP NUMBER(3,0) NOT NULL ENABLE, 
	NO_TARIFF_SET NUMBER(3,0) NOT NULL ENABLE, 
	PC_USAGE_SPLIT NUMBER(5,2) NOT NULL ENABLE, 
	AM_BILL_MULTIPLIER NUMBER(10,5) NOT NULL ENABLE, 
	ST_METER_REG_115 CHAR(5 BYTE) NOT NULL ENABLE, 
	NO_COMBINE_163_INST NUMBER(9,0) NOT NULL ENABLE, 
	NO_PROPERTY_INST NUMBER(9,0) NOT NULL ENABLE, 
	TVP202_NO_SERV_PROV_INST NUMBER(3,0) NOT NULL ENABLE, 
	IND_MARKET_PROP_INST VARCHAR2(1 BYTE), 
	FG_TOO_HARD CHAR(1 BYTE)
   ) ;

  commit;
  exit;


