--Create table BT_SPR_TARIFF_ALGITEM 
--N.Henderson - 12/04/2016
-- Subversion $Revision: 4023 $
--Attempt to drop the table first. Will generate warnings if does not
--exist but can be ignored.

--DROP TABLE BT_SPR_TARIFF_ALGITEM PURGE;

  CREATE TABLE BT_SPR_TARIFF_ALGITEM 
   (	CD_COMPANY_SYSTEM CHAR(4 BYTE) NOT NULL ENABLE, 
	NO_PROPERTY NUMBER(9,0) NOT NULL ENABLE, 
	NO_SERV_PROV NUMBER(3,0) NOT NULL ENABLE, 
	NO_COMBINE_054 NUMBER(9,0) NOT NULL ENABLE, 
	CD_SERV_PROV CHAR(5 BYTE) NOT NULL ENABLE, 
	CD_TARIFF CHAR(10 BYTE) NOT NULL ENABLE, 
	NO_TARIFF_GROUP NUMBER(3,0) NOT NULL ENABLE, 
	NO_TARIFF_SET NUMBER(3,0) NOT NULL ENABLE, 
	CD_BILL_ALG_ITEM CHAR(5 BYTE) NOT NULL ENABLE, 
	DT_START DATE NOT NULL ENABLE, 
	DT_END DATE, 
	DS_VALUE CHAR(20 BYTE), 
	DT_VALUE DATE, 
	NO_VALUE NUMBER(12,0), 
	TP_REF_TAB NUMBER(3,0), 
	CD_REF_TAB CHAR(5 BYTE)
   )  ;

  COMMENT ON TABLE BT_SPR_TARIFF_ALGITEM  IS 'BT_SPR_TARIFF_ALGITEM';

  CREATE INDEX BT_SPR_TARIFF_ALGITEM_IDX1 ON BT_SPR_TARIFF_ALGITEM (NO_COMBINE_054);
  CREATE INDEX BT_SPR_TARIFF_ALGITEM_IDX2 ON BT_SPR_TARIFF_ALGITEM (NO_PROPERTY, NO_SERV_PROV, CD_BILL_ALG_ITEM);

  commit;
  exit;


