--Drop all BT tables.
--N.Henderson
-- $Revision: 4023 $
--12/04/2016
--19/05/2016 M.Marron addd BT_TE tables


DROP TABLE BT_CLOCKOVER;
DROP TABLE BT_METER_READ_FREQ;
DROP TABLE BT_METER_SPID;
DROP TABLE BT_SC_MPW;
DROP TABLE BT_SC_UW;
DROP TABLE BT_SPR_METER;
DROP TABLE BT_SPR_TARIFF;
DROP TABLE BT_SPR_TARIFF_ALGITEM;
DROP TABLE BT_SPR_TARIFF_EXTREF;
DROP TABLE BT_SP_TARIFF;
DROP TABLE BT_SP_TARIFF_ALG;
DROP TABLE BT_SP_TARIFF_EXTREF;
DROP TABLE BT_SP_TARIFF_REFTAB;
DROP TABLE BT_SP_TARIFF_SPLIT;
DROP TABLE BT_TVP054;
DROP TABLE BT_TVP163;
DROP TABLE BT_SP_TARIFF_ALGITEM;
DROP TABLE BT_TE_SUMMARY;
DROP TABLE BT_TE_WORKING;
commit;
exit;


