--
-- Subversion $Revision: 4023 $	
--
load data
into table LU_TARIFF
fields terminated by "|"
(
TARIFFCODE_PK,
TARIFFEFFECTIVEFROMDATE,
TARIFF_EFFECTIVE_TO_DATE,
TARIFFNAME,
TARIFFSTATUS,
TARIFFLEGACYEFFECTIVEFROMDATE,
TARIFFAUTHCODE,
SERVICECOMPONENTTYPE
)