load data
--
-- Subversion $Revision: 6271 $	
--
into table LU_TE_METER_PAIRING
fields terminated by "|" TRAILING NULLCOLS
(
DPID_PK,
NO_IWCS_WORKING,
MET_REF_WORKING,
MANUFACTURER_PK,
SERIAL_NO,
MANUFACTURERSERIALNUM_PK,
PERIOD_WORKING,
TAGGED_BY,
TAGGED_WITH,
TE_PAIRING_OVERRIDE_YN,
OWC
)
