--
-- Subversion $Revision: 4023 $	
--
load data
into table MO_ORG
fields terminated by "|"
(
ORGID_PK,
ORGNAME,
ORGTYPE,
RETAILERTYPE,
INTERIMSUPPLIERALLOCSTATUS,
TRADINGPARTYSERVICECAT,
GAPSITEALLOCSTATUS,
DEFAULTRETURNTOSEWER,
VACANCYCHARGINGMETHODWATER,
VACANCYCHARGINGMETHODSEWERAGE,
TMPDISCONCHRGMETHODWATER,
TMPDISCONCHRGMETHODSEWERAGE,
ALTERNATIVETARIFYEAR,
ORGDESCRIPTION
)
