--
-- Subversion $Revision: 5802 $	
--
LOAD data append into table OWC_METER_NETWORK_W
fields terminated by "|" TRAILING NULLCOLS
(
SPID_PK,
MAINMANUFACTURERSERIALNUM,
MAINMANUFACTURER,
SUBMANUFACTURERSERIALNUM,
SUBMANUFACTURER,
MAINSAPEQUIPMENT,
SUBSAPEQUIPMENT,
OWC                  CONSTANT 'UNITED-W'
)
