--
-- Subversion $Revision: 5594 $	
--
LOAD data append into table OWC_METER_NETWORK
fields terminated by "|" TRAILING NULLCOLS
(
SPID_PK,
MAINMANUFACTURERSERIALNUM,
MAINMANUFACTURER,
SUBMANUFACTURERSERIALNUM,
SUBMANUFACTURER,
MAINSAPEQUIPMENT,
SUBSAPEQUIPMENT,
OWC                  CONSTANT 'DWRCYMRU-W'
)
