--
-- Subversion $Revision: 5201 $	
--
LOAD data into table SAP_METER_DISCHARGE_POINT
fields terminated by "|" TRAILING NULLCOLS
(
MANUFACTURERSERIALNUM_PK,
MANUFACTURER_PK,
DPID_PK,
PERCENTAGEDISCHARGE,
SAPEQUIPMENT,
OWC                  CONSTANT 'SEVERN'
)
