--
-- Subversion $Revision: 5201 $	
--
LOAD data into table SAP_METER_NETWORK
fields terminated by "|" TRAILING NULLCOLS
(
SPID_PK,
MAINMANUFACTURERSERIALNUM,
MAINMANUFACTURER,
MAINMETERTREATMENT,
SUBMANUFACTURERSERIALNUM,
SUBMANUFACTURER,
SUBMETERTREATMENT,
MAINNONMARKETFLAG,
MAINSAPEQUIPMENT,
SUBSAPEQUIPMENT,
OWC                  CONSTANT 'SEVERN'
)
