--Create table BT_SPR_TARIFF 
--N.Henderson - 12/04/2016
-- Subversion $Revision: 4023 $
--Attempt to drop the table first. Will generate warnings if does not
--exist but can be ignored.

--DROP TABLE BT_SPR_TARIFF PURGE;


  CREATE TABLE BT_SPR_TARIFF 
   (CD_COMPANY_SYSTEM CHAR(4 BYTE) NOT NULL ENABLE, 
	NO_PROPERTY NUMBER(9,0) NOT NULL ENABLE, 
	NO_SERV_PROV NUMBER(3,0) NOT NULL ENABLE, 
	NO_ACCOUNT NUMBER(9,0), 
	NO_COMBINE_054 NUMBER(9,0) NOT NULL ENABLE, 
	CD_SERV_PROV CHAR(5 BYTE) NOT NULL ENABLE, 
	CD_TARIFF CHAR(10 BYTE) NOT NULL ENABLE, 
	NO_TARIFF_GROUP NUMBER(3,0) NOT NULL ENABLE, 
	NO_TARIFF_SET NUMBER(3,0) NOT NULL ENABLE, 
	DT_START DATE NOT NULL ENABLE, 
	DT_END DATE
   ) ;

  COMMENT ON TABLE BT_SPR_TARIFF  IS 'List of Tariffs for Property';

  CREATE INDEX BT_SPR_TARIFF_IDX1 ON BT_SPR_TARIFF (NO_COMBINE_054)  ;
  CREATE INDEX BT_SPR_TARIFF_IDX2 ON BT_SPR_TARIFF (NO_PROPERTY, NO_SERV_PROV, NO_ACCOUNT)  ;
  CREATE INDEX BT_SPR_TARIFF_IDX3 ON BT_SPR_TARIFF (CD_COMPANY_SYSTEM, NO_PROPERTY)  ;


  commit;
  exit;
