--Create table BT_SPR_TARIFF_EXTREF 
--N.Henderson - 12/04/2016
-- Subversion $Revision: 4023 $
--Attempt to drop the table first. Will generate warnings if does not
--exist but can be ignored.

--DROP TABLE BT_SPR_TARIFF_EXTREF PURGE;


  CREATE TABLE BT_SPR_TARIFF_EXTREF 
   (CD_COMPANY_SYSTEM CHAR(4 BYTE) NOT NULL ENABLE, 
	NO_PROPERTY NUMBER(9,0) NOT NULL ENABLE, 
	NO_SERV_PROV NUMBER(3,0), 
	NO_COMBINE_054 NUMBER(9,0) NOT NULL ENABLE, 
	CD_SERV_PROV CHAR(5 BYTE) NOT NULL ENABLE, 
	CD_TARIFF CHAR(10 BYTE) NOT NULL ENABLE, 
	NO_TARIFF_GROUP NUMBER(3,0) NOT NULL ENABLE, 
	NO_TARIFF_SET NUMBER(3,0) NOT NULL ENABLE, 
	TP_ENTITY_332 CHAR(5 BYTE) NOT NULL ENABLE, 
	DS_EXT_REF_GROUP VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	NO_EXT_REFERENCE NUMBER(3,0) NOT NULL ENABLE, 
	DS_EXT_REFERENCE VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	NO_EXT_REF_DEBT NUMBER(9,0) NOT NULL ENABLE, 
	CD_EXT_REF VARCHAR2(60 BYTE), 
	CD_WORK_ORDER NUMBER(9,0), 
	DT_EXT_REF DATE, 
	FG_EXT_REF CHAR(1 BYTE), 
	NO_EXT_REF NUMBER(12,0), 
	CD_REF_TAB CHAR(5 BYTE), 
	TP_REF_TAB NUMBER(3,0)
   )  ;

  COMMENT ON TABLE BT_SPR_TARIFF_EXTREF  IS 'BT_SPR_TARIFF_EXTREF';

  CREATE INDEX BT_SPR_TARIFF_EXTREF ON BT_SPR_TARIFF_EXTREF (NO_PROPERTY, NO_SERV_PROV, TP_ENTITY_332, DS_EXT_REFERENCE)  ;
  
  commit;
  exit;
