------------------------------------------------------------------------------
-- TASK					: 	MOSL RDBMS CREATION 
--
-- AUTHOR         		: 	Nigel Henderson
--
-- FILENAME       		: 	02_DDL_MOSL_PK_ALL.sql
--
-- CREATED        		: 	22/02/2016
--	
-- Subversion $Revision: 4023 $
--
-- DESCRIPTION 		   	: 	Adds primary keys
--
-- NOTES  				:	Used in conjunction with the following scripts to re-initialise the
-- 							database.  When re-creating the database run the scripts in order.
--
-- ASSOCIATED FILES		:	MOSL_PDM_CORE.xlsm
-- ASSOCIATED SCRIPTS  	:	01_DDL_MOSL_TABLES_ALL.sql
--							03_DDL_MOSL_FK_ALL.sql
--							04_DDL_MOSL_STATIC_DATA_ALL.sql
--							05_COMMENTS_TABLES_FIELDS_ALL
--
--
--
--
--
---------------------------- Modification History ----------------------------------------------------------
--
-- Version     		Date         	Author         		Description
-- ---------      	---------------     	-------             ------------------------------------------------
-- V0.01       	15/02/2016    	N.Henderson         Initial version after generation from Excel
-- V0.02		25/02/2016		N.Henderson		Had to replace all comments symbols with --
--									Doing something wierd when running query from
--									command line.
-- V0.03		08/03/2016		N.Henderson		Added composite primary key to MO_CUSTOMER table
-- V0.04		15/03/2016		N.Henderson 	Added readable constraint names to primary keys								
--
--
-- 
------------------------------------------------------------------------------------------------------------
-- 

--ADD PK--
--MO_CUSTOMER--
ALTER TABLE MO_CUSTOMER ADD CONSTRAINT PK_01_CUSTOMERNUMBER PRIMARY KEY (CUSTOMERNUMBER_PK);
--MO_ELIGIBLE_PREMISES--
ALTER TABLE MO_ELIGIBLE_PREMISES ADD CONSTRAINT PK_STWPROPERTYNUMBER PRIMARY KEY (STWPROPERTYNUMBER_PK);
ALTER TABLE MO_ELIGIBLE_PREMISES ADD CONSTRAINT PK_CORESPID UNIQUE (CORESPID_PK);
--MO_SUPPLY_POINT--
ALTER TABLE MO_SUPPLY_POINT ADD CONSTRAINT PK_SPID PRIMARY KEY (SPID_PK);
--MO_ORG--
ALTER TABLE MO_ORG ADD CONSTRAINT PK_ORGID PRIMARY KEY (ORGID_PK);
--MO_RETAILER_REGISTRATION--
ALTER TABLE MO_RETAILER_REGISTRATION ADD CONSTRAINT PK_RETAILERID PRIMARY KEY (RETAILERID_PK);
--MO_SERVICE_COMPONENT--
ALTER TABLE MO_SERVICE_COMPONENT ADD CONSTRAINT PK_SERVICECOMPONENTREF PRIMARY KEY (SERVICECOMPONENTREF_PK);
--MO_SERVICE_COMPONENT_TYPE--
ALTER TABLE MO_SERVICE_COMPONENT_TYPE ADD CONSTRAINT PK_SERVICECOMPONENT PRIMARY KEY (SERVICECOMPONENT_PK);
--MO_SERVICE_COMPONENT_VOL_ADJ--
ALTER TABLE MO_SERVICE_COMPONENT_VOL_ADJ ADD CONSTRAINT PK_ADJUSTMENTSVOLADJUNIQREF PRIMARY KEY (ADJUSTMENTSVOLADJUNIQREF_PK);
--MO_DISCHARGE_POINT--
ALTER TABLE MO_DISCHARGE_POINT ADD CONSTRAINT PK_DPID PRIMARY KEY (DPID_PK);
--MO_CALCULATED_DISCHARGE--
ALTER TABLE MO_CALCULATED_DISCHARGE ADD CONSTRAINT PK_CALCDISCHARGEID PRIMARY KEY (CALCDISCHARGEID_PK);
--MO_DISCHARGED_VOLUME--
ALTER TABLE MO_DISCHARGED_VOLUME ADD CONSTRAINT PK_DISCHARGEVOLUME PRIMARY KEY (DISCHARGEVOLUME_PK);
--MO_DISCHARGE_POINT_VOLMET_ADJ--
ALTER TABLE MO_DISCHARGE_POINT_VOLMET_ADJ ADD CONSTRAINT PK_DISCHARGEPOINTVOLMETADJ PRIMARY KEY (DISCHARGEPOINTVOLMETADJ_PK);
--MO_METER--
ALTER TABLE MO_METER ADD CONSTRAINT PK_MANUFACTURER PRIMARY KEY (MANUFACTURER_PK);
ALTER TABLE MO_METER ADD CONSTRAINT PK_MANUFACTURERSERIALNUM UNIQUE (MANUFACTURERSERIALNUM_PK);
--MO_METER_READING--
ALTER TABLE MO_METER_READING ADD CONSTRAINT PK_METER_READING PRIMARY KEY (METER_READING_PK);
--MO_METER_DPIDXREF--
ALTER TABLE MO_METER_DPIDXREF ADD CONSTRAINT PK_METERDPIDXREF PRIMARY KEY (METERDPIDXREF_PK);
--MO_CUST_ADDRESS--
ALTER TABLE MO_CUST_ADDRESS ADD CONSTRAINT PK_01_ADDRESSPROPERTY PRIMARY KEY (ADDRESSPROPERTY_PK);
ALTER TABLE MO_CUST_ADDRESS ADD CONSTRAINT PK_01_ADDRESS UNIQUE (ADDRESS_PK);
ALTER TABLE MO_CUST_ADDRESS ADD CONSTRAINT PK_02_CUSTOMERNUMBER UNIQUE (CUSTOMERNUMBER_PK);
--MO_PROPERTY_ADDRESS--
ALTER TABLE MO_PROPERTY_ADDRESS ADD CONSTRAINT PK_02_ADDRESSPROPERTY PRIMARY KEY (ADDRESSPROPERTY_PK);
ALTER TABLE MO_PROPERTY_ADDRESS ADD CONSTRAINT PK_02_ADDRESS UNIQUE (ADDRESS_PK);
ALTER TABLE MO_PROPERTY_ADDRESS ADD CONSTRAINT PK_02_STWPROPERTYNUMBER UNIQUE (STWPROPERTYNUMBER_PK);
--MO_METER_ADDRESS--
ALTER TABLE MO_METER_ADDRESS ADD CONSTRAINT PK_03_ADDRESSPROPERTY PRIMARY KEY (ADDRESSPROPERTY_PK);
ALTER TABLE MO_METER_ADDRESS ADD CONSTRAINT PK_METERSERIALNUMBER UNIQUE (METERSERIALNUMBER_PK);
ALTER TABLE MO_METER_ADDRESS ADD CONSTRAINT PK_03_ADDRESS UNIQUE (ADDRESS_PK);
--MO_ADDRESS--
ALTER TABLE MO_ADDRESS ADD CONSTRAINT PK_04_ADDRESS PRIMARY KEY (ADDRESS_PK);

--ADD PK--
--MO_TARIFF--
ALTER TABLE MO_TARIFF ADD CONSTRAINT PK_01_TARIFFCODE PRIMARY KEY (TARIFFCODE_PK);
--MO_TARIFF_VERSION--
ALTER TABLE MO_TARIFF_VERSION ADD CONSTRAINT PK_TARIFF_VERSION PRIMARY KEY (TARIFF_VERSION_PK);
ALTER TABLE MO_TARIFF_VERSION ADD CONSTRAINT PK_02_TARIFFCODE UNIQUE (TARIFFCODE_PK);
--MO_TARIFF_TYPE_MPW--
ALTER TABLE MO_TARIFF_TYPE_MPW ADD CONSTRAINT PK_MPW_TARIFF_TYPE PRIMARY KEY (TARIFF_TYPE_PK);
--MO_MPW_METER_MWMFC--
ALTER TABLE MO_MPW_METER_MWMFC ADD CONSTRAINT PK_MPW_TARIFF_MWMFC PRIMARY KEY (TARIFF_MWMFC_PK);
--MO_MPW_BLOCK_MWBT--
ALTER TABLE MO_MPW_BLOCK_MWBT ADD CONSTRAINT PK_MPW_TARIFF_MWBT PRIMARY KEY (TARIFF_MWBT_PK);
--MO_MPW_STANDBY_MWCAPCHG--
ALTER TABLE MO_MPW_STANDBY_MWCAPCHG ADD CONSTRAINT PK_MPW_TARIFF_MWCAPCHG PRIMARY KEY (TARIFF_MWCAPCHG_PK);
--MO_TARIFF_TYPE_MNPW--
ALTER TABLE MO_TARIFF_TYPE_MNPW ADD CONSTRAINT PK_MNPW_TARIFF_TYPE PRIMARY KEY (TARIFF_TYPE_PK);
--MO_MNPW_METER_MWMFC--
ALTER TABLE MO_MNPW_METER_MWMFC ADD CONSTRAINT PK_MNPW_TARIFF_MWMFC PRIMARY KEY (TARIFF_MWMFC_PK);
--MO_MNPW_BLOCK_MWBT--
ALTER TABLE MO_MNPW_BLOCK_MWBT ADD CONSTRAINT PK_MNPW_TARIFF_MWBT PRIMARY KEY (TARIFF_MWBT_PK);
--MO_MNPW_STANDBY_MWCAPCHG--
ALTER TABLE MO_MNPW_STANDBY_MWCAPCHG ADD CONSTRAINT PK_MNPW_TARIFF_MWCAPCHG PRIMARY KEY (TARIFF_MWCAPCHG_PK);
--MO_TARIFF_TYPE_AW--
ALTER TABLE MO_TARIFF_TYPE_AW ADD CONSTRAINT PK_AW_TARIFF_TYPE PRIMARY KEY (TARIFF_TYPE_PK);
--MO_AW_METER_AWMFC--
ALTER TABLE MO_AW_METER_AWMFC ADD CONSTRAINT PK_AW_TARIFF_AWMFC PRIMARY KEY (TARIFF_AWMFC_PK);
--MO_AW_BAND_CHARGE--
ALTER TABLE MO_AW_BAND_CHARGE ADD CONSTRAINT PK_AW_TARIFF_BAND_CHARGE PRIMARY KEY (TARIFF_BAND_CHARGE_PK);
--MO_TARIFF_TYPE_UW--
ALTER TABLE MO_TARIFF_TYPE_UW ADD CONSTRAINT PK_UW_TARIFF_TYPE PRIMARY KEY (TARIFF_TYPE_PK);
--MO_UW_METER_UWPFC--
ALTER TABLE MO_UW_METER_UWPFC ADD CONSTRAINT PK_UW_TARIFF_UWPFC PRIMARY KEY (TARIFF_UWPFC_PK);
--MO_TARIFF_TYPE_MS--
ALTER TABLE MO_TARIFF_TYPE_MS ADD CONSTRAINT PK_MS_TARIFF_TYPE PRIMARY KEY (TARIFF_TYPE_PK);
--MO_MS_BLOCK_MSBT--
ALTER TABLE MO_MS_BLOCK_MSBT ADD CONSTRAINT PK_MS_TARIFF_MWBT PRIMARY KEY (TARIFF_MWBT_PK);
--MO_MS_METER_MSMFC--
ALTER TABLE MO_MS_METER_MSMFC ADD CONSTRAINT PK_MS_TARIFF_MSMFC PRIMARY KEY (TARIFF_MSMFC_PK);
--MO_TARIFF_TYPE_AS--
ALTER TABLE MO_TARIFF_TYPE_AS ADD CONSTRAINT PK_AS_TARIFF_TYPE PRIMARY KEY (TARIFF_TYPE_PK);
--MO_AS_METER_ASMFC--
ALTER TABLE MO_AS_METER_ASMFC ADD CONSTRAINT PK_AS_TARIFF_ASMFC PRIMARY KEY (TARIFF_ASMFC_PK);
--MO_AS_BAND_CHARGE--
ALTER TABLE MO_AS_BAND_CHARGE ADD CONSTRAINT PK_AS_TARIFF_BAND_CHARGE PRIMARY KEY (TARIFF_BAND_CHARGE_PK);
--MO_TARIFF_TYPE_US--
ALTER TABLE MO_TARIFF_TYPE_US ADD CONSTRAINT PK_US_TARIFF_TYPE PRIMARY KEY (TARIFF_TYPE_PK);
ALTER TABLE MO_TARIFF_TYPE_US ADD CONSTRAINT PK_US_TARIFF_VERSION UNIQUE (TARIFF_VERSION_PK);
--MO_US_METER_USPFC--
ALTER TABLE MO_US_METER_USPFC ADD CONSTRAINT PK_US_TARIFF_USPFC PRIMARY KEY (TARIFF_USPFC_PK);
--MO_TARIFF_TYPE_SW--
ALTER TABLE MO_TARIFF_TYPE_SW ADD CONSTRAINT PK_SW_TARIFF_TYPE PRIMARY KEY (TARIFF_TYPE_PK);
--MO_SW_AREA_BAND--
ALTER TABLE MO_SW_AREA_BAND ADD CONSTRAINT PK_SW_TARIFF_AREA_BAND PRIMARY KEY (TARIFF_AREA_BAND_PK);
--MO_SW_BAND_CHARGE--
ALTER TABLE MO_SW_BAND_CHARGE ADD CONSTRAINT PK_SW_TARIFF_BAND_CHARGE PRIMARY KEY (TARIFF_BAND_CHARGE_PK);
--MO_SW_BLOCK_SWBT--
ALTER TABLE MO_SW_BLOCK_SWBT ADD CONSTRAINT PK_SW_TARIFF_SWBT PRIMARY KEY (TARIFF_SWBT_PK);
--MO_SW_METER_SWMFC--
ALTER TABLE MO_SW_METER_SWMFC ADD CONSTRAINT PK_SW_TARIFF_SWMFC PRIMARY KEY (TARIFF_SWMFC_PK);
--MO_TARIFF_TYPE_HD--
ALTER TABLE MO_TARIFF_TYPE_HD ADD CONSTRAINT PK_HD_TARIFF_TYPE PRIMARY KEY (TARIFF_TYPE_PK);
--MO_HD_AREA_BAND--
ALTER TABLE MO_HD_AREA_BAND ADD CONSTRAINT PK_HD_TARIFF_AREA_BAND PRIMARY KEY (TARIFF_AREA_BAND_PK);
--MO_HD_BAND_CHARGE--
ALTER TABLE MO_HD_BAND_CHARGE ADD CONSTRAINT PK_HD_TARIFF_BAND_CHARGE PRIMARY KEY (TARIFF_BAND_CHARGE_PK);
--MO_HD_BLOCK_HDBT--
ALTER TABLE MO_HD_BLOCK_HDBT ADD CONSTRAINT PK_HD_TARIFF_HDBT PRIMARY KEY (TARIFF_HDBT_PK);
--MO_HD_METER_HDMFC--
ALTER TABLE MO_HD_METER_HDMFC ADD CONSTRAINT PK_HD_TARIFF_HDMFC PRIMARY KEY (TARIFF_HDMFC_PK);
--MO_TARIFF_TYPE_TE--
ALTER TABLE MO_TARIFF_TYPE_TE ADD CONSTRAINT PK_TE_TARIFF_TYPE_PK PRIMARY KEY (TARIFF_TYPE_PK);
--MO_TE_BAND_CHARGE--
ALTER TABLE MO_TE_BAND_CHARGE ADD CONSTRAINT PK_TE_TARIFF_BAND_CHARGE_PK PRIMARY KEY (TARIFF_BAND_CHARGE_PK);
--MO_TE_BLOCK_ROBT--
ALTER TABLE MO_TE_BLOCK_ROBT ADD CONSTRAINT PK_TE_TARIFF_ROBT_PK PRIMARY KEY (TARIFF_ROBT_PK);
--MO_TE_BLOCK_BOBT--
ALTER TABLE MO_TE_BLOCK_BOBT ADD CONSTRAINT PK_TE_TARIFF_BOBT_PK PRIMARY KEY (TARIFF_BOBT_PK);




----------------------------All statements below here are previous version. New naming convention introduced ------------
----PK
----MO_CUSTOMER
----Added composite primary key to MO_CUSTOMER table. Original statement left in place
--ALTER TABLE MO_CUSTOMER ADD CONSTRAINT PK_CUSTOMERNUMBER_01 PRIMARY KEY (CUSTOMERNUMBER_PK);
--ALTER TABLE MO_CUSTOMER ADD UNIQUE (STWPROPERTYNUMBER_PK);
----ALTER TABLE MO_CUSTOMER ADD CONSTRAINT MO_CUST_STW_PK PRIMARY KEY(CUSTOMERNUMBER_PK, STWPROPERTYNUMBER_PK);
----MO_ELIGIBLE_PREMISES
--ALTER TABLE MO_ELIGIBLE_PREMISES ADD PRIMARY KEY (STWPROPERTYNUMBER_PK);
--ALTER TABLE MO_ELIGIBLE_PREMISES ADD UNIQUE (CORESPID_PK);
----MO_SUPPLY_POINT
--ALTER TABLE MO_SUPPLY_POINT ADD PRIMARY KEY (SPID_PK);
----MO_ORG
--ALTER TABLE MO_ORG ADD PRIMARY KEY (ORGID_PK);
----MO_RETAILER_REGISTRATION
--ALTER TABLE MO_RETAILER_REGISTRATION ADD PRIMARY KEY (RETAILERID_PK);
----MO_SERVICE_COMPONENT
--ALTER TABLE MO_SERVICE_COMPONENT ADD PRIMARY KEY (SERVICECOMPONENTREF_PK);
----MO_SERVICE_COMPONENT_TYPE
--ALTER TABLE MO_SERVICE_COMPONENT_TYPE ADD PRIMARY KEY (SERVICECOMPONENT_PK);
----MO_SERVICE_COMPONENT_VOL_ADJ
--ALTER TABLE MO_SERVICE_COMPONENT_VOL_ADJ ADD PRIMARY KEY (ADJUSTMENTSVOLADJUNIQREF_PK);
----MO_DISCHARGE_POINT
--ALTER TABLE MO_DISCHARGE_POINT ADD PRIMARY KEY (DPID_PK);
----MO_CALCULATED_DISCHARGE
--ALTER TABLE MO_CALCULATED_DISCHARGE ADD PRIMARY KEY (CALCDISCHARGEID_PK);
----MO_DISCHARGED_VOLUME
--ALTER TABLE MO_DISCHARGED_VOLUME ADD PRIMARY KEY (DISCHARGEVOLUME_PK);
----MO_DISCHARGE_POINT_VOLMET_ADJ
--ALTER TABLE MO_DISCHARGE_POINT_VOLMET_ADJ ADD PRIMARY KEY (DISCHARGEPOINTVOLMETADJ_PK);
----MO_METER
--ALTER TABLE MO_METER ADD PRIMARY KEY (MANUFACTURER_PK);
--ALTER TABLE MO_METER ADD UNIQUE (MANUFACTURERSERIALNUM_PK);
----MO_METER_READING
--ALTER TABLE MO_METER_READING ADD PRIMARY KEY (METER_READING_PK);
----MO_METER_DPIDXREF
--ALTER TABLE MO_METER_DPIDXREF ADD PRIMARY KEY (METERDPIDXREF_PK);
----MO_CUST_ADDRESS
--ALTER TABLE MO_CUST_ADDRESS ADD PRIMARY KEY (ADDRESSPROPERTY_PK);
--ALTER TABLE MO_CUST_ADDRESS ADD UNIQUE (ADDRESS_PK);
--ALTER TABLE MO_CUST_ADDRESS ADD UNIQUE (CUSTOMERNUMBER_PK);
----MO_PROPERTY_ADDRESS
--ALTER TABLE MO_PROPERTY_ADDRESS ADD PRIMARY KEY (ADDRESSPROPERTY_PK);
--ALTER TABLE MO_PROPERTY_ADDRESS ADD UNIQUE (ADDRESS_PK);
--ALTER TABLE MO_PROPERTY_ADDRESS ADD UNIQUE (STWPROPERTYNUMBER_PK);
----MO_METER_ADDRESS
--ALTER TABLE MO_METER_ADDRESS ADD PRIMARY KEY (ADDRESSPROPERTY_PK);
--ALTER TABLE MO_METER_ADDRESS ADD UNIQUE (METERSERIALNUMBER_PK);
--ALTER TABLE MO_METER_ADDRESS ADD UNIQUE (ADDRESS_PK);
----MO_ADDRESS
--ALTER TABLE MO_ADDRESS ADD PRIMARY KEY (ADDRESS_PK);
--
----PK
----MO_TARIFF
--ALTER TABLE MO_TARIFF ADD PRIMARY KEY (TARIFFCODE_PK);
----MO_TARIFF_VERSION
--ALTER TABLE MO_TARIFF_VERSION ADD PRIMARY KEY (TARIFF_VERSION_PK);
--ALTER TABLE MO_TARIFF_VERSION ADD UNIQUE (TARIFFCODE_PK);
----MO_TARIFF_TYPE_MPW
--ALTER TABLE MO_TARIFF_TYPE_MPW ADD PRIMARY KEY (TARIFF_TYPE_PK);
----MO_MPW_METER_MWMFC
--ALTER TABLE MO_MPW_METER_MWMFC ADD PRIMARY KEY (TARIFF_MWMFC_PK);
----MO_MPW_BLOCK_MWBT
--ALTER TABLE MO_MPW_BLOCK_MWBT ADD PRIMARY KEY (TARIFF_MWBT_PK);
----MO_MPW_STANDBY_MWCAPCHG
--ALTER TABLE MO_MPW_STANDBY_MWCAPCHG ADD PRIMARY KEY (TARIFF_MWCAPCHG_PK);
----MO_TARRIF_TYPE_MNPW
--ALTER TABLE MO_TARIFF_TYPE_MNPW ADD PRIMARY KEY (TARIFF_TYPE_PK);
----MO_MNPW_METER_MWMFC
--ALTER TABLE MO_MNPW_METER_MWMFC ADD PRIMARY KEY (TARIFF_MWMFC_PK);
----MO_MNPW_BLOCK_MWBT
--ALTER TABLE MO_MNPW_BLOCK_MWBT ADD PRIMARY KEY (TARIFF_MWBT_PK);
----MO_MNPW_STANDBY_MWCAPCHG
--ALTER TABLE MO_MNPW_STANDBY_MWCAPCHG ADD PRIMARY KEY (TARIFF_MWCAPCHG_PK);
----MO_TARIFF_TYPE_AW
--ALTER TABLE MO_TARIFF_TYPE_AW ADD PRIMARY KEY (TARIFF_TYPE_PK);
----MO_AW_METER_AWMFC
--ALTER TABLE MO_AW_METER_AWMFC ADD PRIMARY KEY (TARIFF_AWMFC_PK);
----MO_AW_BAND_CHARGE
--ALTER TABLE MO_AW_BAND_CHARGE ADD PRIMARY KEY (TARIFF_BAND_CHARGE_PK);
----MO_TARIFF_TYPE_UW
--ALTER TABLE MO_TARIFF_TYPE_UW ADD PRIMARY KEY (TARIFF_TYPE_PK);
----MO_UW_METER_UWPFC
--ALTER TABLE MO_UW_METER_UWPFC ADD PRIMARY KEY (TARIFF_UWPFC_PK);
----MO_TARIFF_TYPE_MS
--ALTER TABLE MO_TARIFF_TYPE_MS ADD PRIMARY KEY (TARIFF_TYPE_PK);
----MO_MS_BLOCK_MSBT
--ALTER TABLE MO_MS_BLOCK_MSBT ADD PRIMARY KEY (TARIFF_MWBT_PK);
----MO_MS_METER_MSMFC
--ALTER TABLE MO_MS_METER_MSMFC ADD PRIMARY KEY (TARIFF_MSMFC_PK);
----MO_TARIFF_TYPE_AS
--ALTER TABLE MO_TARIFF_TYPE_AS ADD PRIMARY KEY (TARIFF_TYPE_PK);
----MO_AS_METER_ASMFC
--ALTER TABLE MO_AS_METER_ASMFC ADD PRIMARY KEY (TARIFF_ASMFC_PK);
----MO_AS_BAND_CHARGE
--ALTER TABLE MO_AS_BAND_CHARGE ADD PRIMARY KEY (TARIFF_BAND_CHARGE_PK);
----MO_TARIFF_TYPE_US
--ALTER TABLE MO_TARIFF_TYPE_US ADD PRIMARY KEY (TARIFF_TYPE_PK);
--ALTER TABLE MO_TARIFF_TYPE_US ADD UNIQUE (TARIFF_VERSION_PK);
----MO_US_METER_USPFC
--ALTER TABLE MO_US_METER_USPFC ADD PRIMARY KEY (TARIFF_USPFC_PK);
----MO_TARIFF_TYPE_SW
--ALTER TABLE MO_TARIFF_TYPE_SW ADD PRIMARY KEY (TARIFF_TYPE_PK);
----MO_SW_AREA_BAND
--ALTER TABLE MO_SW_AREA_BAND ADD PRIMARY KEY (TARIFF_AREA_BAND_PK);
----MO_SW_BAND_CHARGE
--ALTER TABLE MO_SW_BAND_CHARGE ADD PRIMARY KEY (TARIFF_BAND_CHARGE_PK);
----MO_SW_BLOCK_SWBT
--ALTER TABLE MO_SW_BLOCK_SWBT ADD PRIMARY KEY (TARIFF_SWBT_PK);
----MO_SW_METER_SWMFC
--ALTER TABLE MO_SW_METER_SWMFC ADD PRIMARY KEY (TARIFF_SWMFC_PK);
----MO_TARIFF_TYPE_HD
--ALTER TABLE MO_TARIFF_TYPE_HD ADD PRIMARY KEY (TARIFF_TYPE_PK);
----MO_HD_AREA_BAND
--ALTER TABLE MO_HD_AREA_BAND ADD PRIMARY KEY (TARIFF_AREA_BAND_PK);
----MO_HD_BAND_CHARGE
--ALTER TABLE MO_HD_BAND_CHARGE ADD PRIMARY KEY (TARIFF_BAND_CHARGE_PK);
----MO_HD_BLOCK_HDBT
--ALTER TABLE MO_HD_BLOCK_HDBT ADD PRIMARY KEY (TARIFF_HDBT_PK);
----MO_HD_METER_HDMFC
--ALTER TABLE MO_HD_METER_HDMFC ADD PRIMARY KEY (TARIFF_HDMFC_PK);
----MO_TARIFF_TYPE_TE
--ALTER TABLE MO_TARIFF_TYPE_TE ADD PRIMARY KEY (TARIFF_TYPE_PK);
----MO_TE_BAND_CHARGE
--ALTER TABLE MO_TE_BAND_CHARGE ADD PRIMARY KEY (TARIFF_BAND_CHARGE_PK);
----MO_TE_BLOCK_ROBT
--ALTER TABLE MO_TE_BLOCK_ROBT ADD PRIMARY KEY (TARIFF_ROBT_PK);
----MO_TE_BLOCK_BOBT
--ALTER TABLE MO_TE_BLOCK_BOBT ADD PRIMARY KEY (TARIFF_BOBT_PK);

commit;
exit;
