------------------------------------------------------------------------------
-- TASK				: 	MOSL RDBMS CREATION of Supporting Lookup tables
--
-- AUTHOR         		: 	Michael Marron
--
-- FILENAME       		: 	01_DDL_MOSL_Lookup_TABLES_ALL.sql
--
-- CREATED        		: 	26/02/2016
-- Subversion $Revision: 6354 $
--	
-- DESCRIPTION 		   	: 	Creates all supporting lookup tables required for MOSL database
--
-- NOTES  			:	Used in conjunction with the following scripts to re-initialise the
-- 							database.  When re-creating the database run the scripts in order
-- 							as detailed below (.sql).
--
-- ASSOCIATED FILES		:	MOSL_PDM_CORE.xlsm
-- ASSOCIATED SCRIPTS  		:	02_TRUNC_Lookups_ALL.sql
--					
--
---------------------------- Modification History ----------------------------------------------------------
--
-- Version     	Date          Author        Description
-- -------      ----------    ------------  ------------------------------------------------
-- V0.01       	26/02/2016    M.Marron	    Initial version add LU_SPID_RANGE, LU_CONSTUCTION_SITE and LU_PUBHEALTHRESITE
-- V0.02		    26/02/2016    M.Marron      Corrected BUILDINGWATERSTATUS on LU_CONSTUCTION_SITE table, set it to Not Null
-- V0.03        14/03/2016    M.Marron      Added LU_LANDLORD, LU_CROSSBORDER, LU_CLOCKOVER & LU_DATALOGGERS.
-- v0.04        15/03/2016    M.Marron      updated comments on LU_CROSSBORDER  
-- v0.05        18/03/2016    M.Marron	    Added LU_TARIFF,  LU_SERVICE_CATEGORY, LU_SERVICE_COMP_CHARGES, LU_TARIFF_SPECIAL_AGREEMENTS
-- v0.06        31/03/2016    M.Marron	    updated LU_DATALOGGERS to add logger ID and set STWMETERREF_PK, MANUFACTURER_PK to NULLABLE 
-- v0.07        13/05/2016    M.Marron	    updated LU_CROSSBORDER to added a unique constraint on SPID_PK to avoid failures in Supply point
-- v0.08        20/06/2016    L.Smith       Added index on CORESPID_PK
-- v0.09        14/07/2016    S.Badhan      SAP CR-16. Added table LU_DISCHARGE_VOL_LIMITS.
-- v0.09        14/07/2016    O.Badmus      SAP_SENSITIVE and SAP_SENSI_EMERGENCY_PLANS
-- v0.10        18/07/2016    K.Burton      SAP_SEWERAGE_TREATMENT_WORKS
-- v0.10        21/07/2016    S.Badhan      SAP CR-20. Add column DPID_TYPE to LU_DISCHARGE_VOL_LIMITS.
-- v0.11        12/08/2016    S.Badhan      I-335. Add primarry key to LU_DATALOGGERS ON MANUFACTURERSERIALNUM_PK, STWPROPERTYNUMBER_PK.
-- v0.12        15/08/2016    S.Badhan      I-320. Add create of LU_TE_BILLING_CYCLE (moved from BT_P0002.sql).
-- v0.13        19/09/2016    S.Badhan      CR-30. Add index on LU_TARIFF_SPECIAL_AGREEMENTS.
-- v0.14        22/09/2016    K.Burton      Added LU_OWC_RECON_MEASURES for OWC files
-- v0.15        29/09/2016    S.Badhan      Remove schema name from LU_OWC_RECON_MEASURES.
-- v0.16        04/10/2016    K.Burton      Added BT_OWC_TE_DPID_REF for OWC DPIDXREF functionality
-- V0.17        26/10/2016    S.Badhan      Add LU_SS_LANDLORD for OWC functionality
-- V0.18        03/11/2016    D.Cheung      Add LU_OTHER_METER_DPID for TE missing meters
-- V0.19        10/11/2016    L.Smith       Add LU_TE_EXCLUSION for TE no_iwcs exclusions
-- V0.20        16/11/2016    L.Smith       Add LU_TE_METER_PAIRING for TE
-- v0.21        17/11/2016    D.Cheung      Add Markers for TE_ASSOCIATED and OWC to LU_TE_METER_PAIRING
--                                          Add LU_TE_METER_DPID_EXCLUSIONS table
-- v0.22        17/11/2016    L.Smith       Remove columns from U_TE_METER_PAIRING
------------------------------------------------------------------------------------------------------------
--
-- Create LU_SPID_RANGE table
CREATE TABLE LU_SPID_RANGE
(
SPID_PK VARCHAR(13) CONSTRAINT CH01_LU_SPID_PK NOT NULL,
-- STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CH01_LU_STWPROPERTYNUMBER_PK NOT NULL, removed as not needed
CORESPID_PK VARCHAR(10) CONSTRAINT CH01_LU_CORESPID_PK NOT NULL,
SERVICECATEGORY VARCHAR(1) CONSTRAINT CH01_LU_SERVICECATEGORY NOT NULL
);
--
-- set primary key
ALTER TABLE LU_SPID_RANGE ADD CONSTRAINT PK_LU_SPID PRIMARY KEY (SPID_PK);
--
-- add table and field comments
COMMENT ON Table LU_SPID_RANGE IS 'This table holds the MOSL SPID range allocated to Severn Trent Water';
COMMENT ON COLUMN LU_SPID_RANGE.SPID_PK IS 'Primary key for a SPID. It is the full 13 char value issued by MOSLand is the unique identifer for the supply point';
-- COMMENT ON COLUMN LU_SPID_RANGE.STWPROPERTYNUMBER_PK IS 'Target NO_PROPERTY ~~~STW031 - NO_PROPERTY'; removed not needed
COMMENT ON COLUMN LU_SPID_RANGE.SERVICECATEGORY IS 'Service Category~~~D2002 - Identifies the Service Category for a Supply Point (Water Services or Sewerage Services) “W” = Water and “S” = Sewerage';
--
--
-- Create LU_PUBHEALTHRESITE table
CREATE TABLE LU_PUBHEALTHRESITE
(
STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CH01_LU_STWPROPERTYNUMBER NOT NULL,
NONPUBHEALTHRELSITE  NUMBER(1) CONSTRAINT CH01_LU_NONPUBHEALTHRELSITE NOT NULL,
NONPUBHEALTHRELSITEDSC VARCHAR(255) ,
PUBHEALTHRELSITEARR NUMBER(1) CONSTRAINT CH01_LU_PUBHEALTHRELSITEARR NOT NULL
);
--
-- set primary key & Constriants
ALTER TABLE LU_PUBHEALTHRESITE ADD CONSTRAINT PK01_LU_STWPROPERTYNUMBER PRIMARY KEY (STWPROPERTYNUMBER_PK);
ALTER TABLE LU_PUBHEALTHRESITE ADD CONSTRAINT CHK02_LU_NONPUBHEALTHRELSITE  CHECK (NONPUBHEALTHRELSITE  IN (0,1));
ALTER TABLE LU_PUBHEALTHRESITE ADD CONSTRAINT CHK02_LU_PUBHEALTHRELSITEARR CHECK (PUBHEALTHRELSITEARR IN (0,1));
--
-- add table and field comments
COMMENT ON Table LU_PUBHEALTHRESITE IS 'This table holds data about SENSITIVE properties, source externally from Target but required from MOSL upload';
COMMENT ON COLUMN LU_PUBHEALTHRESITE.STWPROPERTYNUMBER_PK IS 'Target NO_PROPERTY~~~STW031 - NO_PROPERTY';
COMMENT ON COLUMN LU_PUBHEALTHRESITE.NONPUBHEALTHRELSITE  IS 'Non-Public Health Related Site Specific Arrangements Flag~~~D2093 - Indication of whether or not a site specific management plan is in place, and not for public health related reasons';
COMMENT ON COLUMN LU_PUBHEALTHRESITE.NONPUBHEALTHRELSITEDSC IS 'Non-Public Health Related Site Specific Arrangements Free Descriptor~~~D2094 - Free descriptor for indication of the nature of site specific management plan in place, when not for public health related reasons';
COMMENT ON COLUMN LU_PUBHEALTHRESITE.PUBHEALTHRELSITEARR IS 'Public Health Related Site Specific Arrangements Flag~~~D2087 - Boolean flag to Indicate whether or not a site specific management plan is in place for public health related reasons';
--
--
-- Create LU_CONSTRUCTION_SITE table  (updated BUILDINGWATERSTATUS to not null)
CREATE TABLE LU_CONSTRUCTION_SITE
(
STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CH02_LU_STWPROPERTYNUMBER NOT NULL,
BUILDINGWATERSTATUS NUMBER(1) CONSTRAINT CH01_LU_BUILDINGWATERSTATUS NOT NULL
);
--
-- set primary key
ALTER TABLE LU_CONSTRUCTION_SITE ADD CONSTRAINT PK02_LU_STWPROPERTYNUMBER PRIMARY KEY (STWPROPERTYNUMBER_PK);
ALTER TABLE LU_CONSTRUCTION_SITE ADD CONSTRAINT CHK02_LU_BUILDINGWATERSTATUS CHECK (BUILDINGWATERSTATUS IN (0,1));
--
-- add table and field comments
COMMENT ON Table LU_CONSTRUCTION_SITE IS 'This table holds data about properties which are still under construction, source externally from Target but required from MOSL upload';
COMMENT ON COLUMN LU_CONSTRUCTION_SITE.STWPROPERTYNUMBER_PK IS 'Target NO_PROPERTY~~~STW031 - NO_PROPERTY';
COMMENT ON COLUMN LU_CONSTRUCTION_SITE.BUILDINGWATERSTATUS IS 'Building Water Status~~~D2029 - Boolean flag to indicate if the site is a building construction site. ';
--
-- version 0.03 Added LU_LANDLORD, LU_CROSSBORDER, LU_CLOCKOVER & LU_DATALOGGERS
--
-- Create LU_LANDLORD   
CREATE TABLE LU_LANDLORD
(
STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CHK10_LU_STWPROPERTYNUMBER NOT NULL,
LANDLORDSPID VARCHAR(13) CONSTRAINT CHK01_LU_LANDLORDSPID NOT NULL,
SERVICECATEGORY VARCHAR(1) CONSTRAINT CHK10_LU_SERVICECATEGORY NOT NULL
);
--
-- set primary key
-- 
--
-- add table and field comments
COMMENT ON COLUMN LU_LANDLORD.STWPROPERTYNUMBER_PK IS 'Target NO_PROPERTY~~~STW031 - NO_PROPERTY to which the landlord SPID applies'; 
COMMENT ON COLUMN LU_LANDLORD.LANDLORDSPID IS 'Landlord SPID~~~D2070 - Identifies the Landlord Supply point in a multi-occupancy Eligible Premises.  The valid set for this is all SPIDs';
COMMENT ON COLUMN LU_LANDLORD.SERVICECATEGORY IS 'Service Category~~~D2002 - Identifies the Service Category for a Supply Point to which this landlord SPID applies if required';
--
-- 
-- Create LU_CROSSBORDER
CREATE TABLE LU_CROSSBORDER
(
STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CHK04_LU_STWPROPERTYNUMBER NOT NULL,
CORESPID_PK VARCHAR(10),
SPID_PK VARCHAR(13) CONSTRAINT CHK02_LU_SPID_PK NOT NULL,
SERVICECATEGORY VARCHAR(1) CONSTRAINT CHK02_LU_SERVICECATEGORY NOT NULL,
RETAILERID_PK VARCHAR(12) CONSTRAINT CHK01_LU_RETAILERID NOT NULL,
WHOLESALERID_PK VARCHAR(12) CONSTRAINT CHK01_LU_WHOLESALERID NOT NULL
);
--
-- set primary key
--
--
-- Create index on CORESPID_PK
CREATE INDEX IDX02_CORESPID_PK ON LU_CROSSBORDER
    (
      CORESPID_PK
    )
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
    (
      INITIAL 26214400 NEXT 26214400 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
    );
-- add table and field comments
COMMENT ON COLUMN LU_CROSSBORDER.STWPROPERTYNUMBER_PK IS 'Target NO_PROPERTY - NO_PROPERTY to which Crossborder Supply Point is related to'; 
COMMENT ON COLUMN LU_CROSSBORDER.CORESPID_PK IS 'CORESPID_PK if supplied by STW for CROSSBORDER';
COMMENT ON COLUMN LU_CROSSBORDER.SERVICECATEGORY IS 'Service Category (D2002) - this applies to i.e W or S. Add a row for each if required';
COMMENT ON COLUMN LU_CROSSBORDER.RETAILERID_PK IS 'Retailer ID who is responsible for this SPID';
COMMENT ON COLUMN LU_CROSSBORDER.SERVICECATEGORY IS 'Wholesaler ID who is responsible for this SPID';
--
--
-- Create LU_DATALOGGERS
CREATE TABLE LU_DATALOGGERS
(
MANUFACTURERSERIALNUM_PK VARCHAR(32)CONSTRAINT CHK01_LU_MANUFACTSN NOT NULL,
STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CHK05_LU_STWPROPERTYN NOT NULL,
STWMETERREF_PK NUMBER(32),
MANUFACTURER_PK VARCHAR(32),
DATALOGGERSERIALNUM VARCHAR(32),
DATALOGGERWHOLESALER NUMBER(1) CONSTRAINT CHK01_LU_WHOLESALER NOT NULL,
DATALOGGERNONWHOLESALER NUMBER(1) CONSTRAINT CHK01_LU_NONWHOLESALER NOT NULL
);

ALTER TABLE LU_DATALOGGERS ADD CONSTRAINT PK_LU_DATALOGGERS PRIMARY KEY (MANUFACTURERSERIALNUM_PK, STWPROPERTYNUMBER_PK);
            
ALTER TABLE LU_DATALOGGERS ADD CONSTRAINT CHK02_LU_WHOLESALER CHECK (DATALOGGERWHOLESALER IN (0,1));
ALTER TABLE LU_DATALOGGERS ADD CONSTRAINT CHK02_LU_NONWHOLESALER CHECK (DATALOGGERNONWHOLESALER IN (0,1));
--
-- add table and field comments
COMMENT ON COLUMN LU_DATALOGGERS.MANUFACTURERSERIALNUM_PK IS 'TARGET NO_UTL_EQUIP (METER serial number) Use this and PROPERTY_NO';
COMMENT ON COLUMN LU_DATALOGGERS.STWPROPERTYNUMBER_PK IS 'Target PROPERTY_NO where meter is installed'; 
COMMENT ON COLUMN LU_DATALOGGERS.STWMETERREF_PK IS 'Optional Target NO_EQUIPMENT that this logger is attached to';
COMMENT ON COLUMN LU_DATALOGGERS.MANUFACTURER_PK IS 'Optional Meter manufacture'; 
COMMENT ON COLUMN LU_DATALOGGERS.DATALOGGERSERIALNUM IS 'Optional Datalogger serial number (LOGGERID)';
COMMENT ON COLUMN LU_DATALOGGERS.DATALOGGERWHOLESALER IS 'Is this a Wholesaler logger Y (1) or No (0)';
COMMENT ON COLUMN LU_DATALOGGERS.DATALOGGERNONWHOLESALER IS 'Is this a NON Wholesaler logger Y (1) or No (0)';
--
--
-- Create LU_CLOCKOVER
CREATE TABLE LU_CLOCKOVER
(
STWMETERREF_PK NUMBER(32) CONSTRAINT CHK01_LU_STWMETERREF NOT NULL,
METERREADDATE DATE  CONSTRAINT CHK01_LU_METERREADDATE NOT NULL,
METERREAD NUMBER(12) ,
ROLLOVERINDICATOR NUMBER(1)  CONSTRAINT CHK01_LU_ROLLOVERIND NOT NULL
);
--
-- set constraint key
ALTER TABLE LU_CLOCKOVER ADD CONSTRAINT CHK02_LU_ROLLOVERIND CHECK (ROLLOVERINDICATOR IN (0,1));
--
-- add table and field comments
COMMENT ON COLUMN LU_CLOCKOVER.STWMETERREF_PK IS 'Target NO_EQUIPMENT (Meterthat this reading was for'; 
COMMENT ON COLUMN LU_CLOCKOVER.METERREADDATE IS 'Target TS_CAPTURED (Meter read date), so that the correct reading can be flagged as clock over'; 
COMMENT ON COLUMN LU_CLOCKOVER.METERREAD IS 'Target AM_READING (METER Read value) at clockover used to check that the correct reading is flagged'; 
COMMENT ON COLUMN LU_CLOCKOVER.ROLLOVERINDICATOR IS 'Rollover Indicator~~~D3020 - Default to 1 (Y). Indicates the meter read has rolled over for this meter.';
--
--
-- Create LU_SAP_FLOCA added 01/05/2016
CREATE TABLE LU_SAP_FLOCA
(
STWPROPERTYNUMBER_PK NUMBER(9),
SAPFLOCNUMBER NUMBER(30)
);
-- set constraint key
ALTER TABLE LU_SAP_FLOCA ADD CONSTRAINT PK03_LU_STWPROPERTYNUMBER PRIMARY KEY (STWPROPERTYNUMBER_PK);
-- add table and field comments
COMMENT ON COLUMN LU_SAP_FLOCA.STWPROPERTYNUMBER_PK IS 'Target no_property and is the primary key';
COMMENT ON COLUMN LU_SAP_FLOCA.SAPFLOCNUMBER IS 'SAP FLOC A identifed for the taregt no_property';
--
-- Create LU_SAP_EQUIPMENT  added 01/05/2016
CREATE TABLE LU_SAP_EQUIPMENT
(
STWMETERREF NUMBER(9),
SAPEQUIPMENT VARCHAR2(25 BYTE)
);
-- set constraint key
ALTER TABLE LU_SAP_EQUIPMENT ADD CONSTRAINT PK01_LU_STWMETERREF PRIMARY KEY (STWMETERREF);
-- add table and field comments
COMMENT ON COLUMN LU_SAP_EQUIPMENT.STWMETERREF IS 'Target NO_EQUIPMENT that the SAP equipment relates to';
COMMENT ON COLUMN LU_SAP_EQUIPMENT.SAPEQUIPMENT IS 'SAP equipment number ';
--
-- Create LU_TRAIFF -- NOT required removed 01/06/2016
--CREATE TABLE LU_TARIFF
--  (
--    TARIFFCODE_PK VARCHAR2(32 BYTE) NOT NULL ENABLE,
--    TARIFFEFFECTIVEFROMDATE DATE NOT NULL ENABLE,
--    TARIFF_EFFECTIVE_TO_DATE DATE,
--    TARIFFNAME   VARCHAR2(250 BYTE) NOT NULL ENABLE,
--    TARIFFSTATUS VARCHAR2(250 BYTE) NOT NULL ENABLE,
--    TARIFFLEGACYEFFECTIVEFROMDATE DATE,
--    TARIFFAUTHCODE       VARCHAR2(250 BYTE) NOT NULL ENABLE,
--    SERVICECOMPONENTTYPE VARCHAR2(10 BYTE) NOT NULL ENABLE
--  );
 --
-- set primary key
--
-- add table and field comments
--
-- Create LU_SERVICE_CATEGORY
 CREATE TABLE LU_SERVICE_CATEGORY
  (
    SUPPLY_POINT_CODE     VARCHAR2(2 BYTE),
    SUPPLY_POINT_DESC     VARCHAR2(32 BYTE),
    SERVICECOMPONENTDESC  VARCHAR2(32 BYTE),
    TARGET_SERV_PROV_CODE VARCHAR2(100 BYTE),
    SERVICECOMPONENTTYPE  VARCHAR2(10 BYTE)
  );
 --
-- set primary key
--
-- add table and field comments
--
-- Create LU_SERVICE_COMP_CHARGES  -NOT REQUIRED REMOVED  NOT required removed 01/06/2016
--CREATE TABLE LU_SERVICE_COMP_CHARGES
--  (
--    SERVICE_COMP_CD   VARCHAR2(5 BYTE),
--    SERVICE_COMP_DESC VARCHAR2(40 BYTE),
--    CHARGE_TYPE       VARCHAR2(10 BYTE),
--    CHARGE_DESC       VARCHAR2(70 BYTE),
--    STEP_TYPE         VARCHAR2(20 BYTE),
--    STEP_DESC         VARCHAR2(30 BYTE),
--    USAGE_UNITS       VARCHAR2(20 BYTE),
--    CHARGE_UNITS      VARCHAR2(15 BYTE)
--  );
 --
-- set primary key
--
-- add table and field comments
-- 
-- Create LU_TARIFF_SPECIAL_AGREEMENTS
CREATE TABLE LU_TARIFF_SPECIAL_AGREEMENTS
  (
    PROPERTY_NO              NUMBER,
    ACCOUNT_NO               NUMBER,
    CUSTOMER_NAME            VARCHAR2(200 BYTE),
    TARIFFCODE               VARCHAR2(32 BYTE),
    SERVICECOMPONENTTYPE     VARCHAR2(32 BYTE),
    SPECIAL_AGREEMENT_FLAG   CHAR(1 BYTE),
    SPECIAL_AGREEMENT_DESC   VARCHAR2(100 BYTE),
    OFWAT_REFERENCE_NUMBER   VARCHAR2(100 BYTE),
    STW_REFERENCE_NUMBER     VARCHAR2(100 BYTE),
    SPECIAL_AGREEMENT_FACTOR NUMBER
  );
  
CREATE INDEX LU_TARIFF_SPECIAL_AGR_IDX1 ON LU_TARIFF_SPECIAL_AGREEMENTS (PROPERTY_NO, TARIFFCODE, SERVICECOMPONENTTYPE);   
      
  --
-- set primary key
--
-- add table and field comments
-- 

-- Create LU_SPID_OWC_RETAILER table
CREATE TABLE LU_SPID_OWC_RETAILER
(
STWPROPERTYNUMBER_PK number(9),
STWACCOUNTNUMBER NUMBER(10),
CUSTOMERNAME varchar(255) ,
METERREF varchar2(20 byte),
STWSERVICETYPE varchar2(5 byte),
WCRETAILER varchar2(20 byte),
TARIFF VARCHAR2(32 BYTE),
NO_LEGAL_ENTITY number(9)
);


-- LU_DISCHARGE_VOL_LIMITS table

CREATE TABLE LU_DISCHARGE_VOL_LIMITS
(
  NO_IWCS        NUMBER(12)  CONSTRAINT CH01_NO_IWCS       NOT NULL,
  VOLUME_LIMIT   NUMBER(5)   CONSTRAINT CH01_VOLUME_LIMIT  NOT NULL,
  DPID_TYPE      VARCHAR2(9) CONSTRAINT CH02_DPID_TYPE     NOT NULL
);

ALTER TABLE LU_DISCHARGE_VOL_LIMITS ADD CONSTRAINT PK_LU_NO_IWCS PRIMARY KEY (NO_IWCS);

COMMENT ON TABLE  LU_DISCHARGE_VOL_LIMITS IS 'SAP Only Data (Not for MOSL) - Table for Discharge Point daily volume limits';
COMMENT ON COLUMN LU_DISCHARGE_VOL_LIMITS.NO_IWCS IS 'Primary key NO_IWCS';
COMMENT ON COLUMN LU_DISCHARGE_VOL_LIMITS.VOLUME_LIMIT IS 'Daily Volume limit per m3';
COMMENT ON COLUMN LU_DISCHARGE_VOL_LIMITS.DPID_TYPE IS 'Type of DPID';


CREATE TABLE SAP_SENSITIVE
  (STWPROPERTYNUMBER_PK   number(9,0) not null enable,
--   SENSITIVE              varchar2(5 byte) not null enable,
   SENSITIVE_REASON       VARCHAR2(255 BYTE));
comment on column SAP_SENSITIVE.STWPROPERTYNUMBER_PK is 'Target Property ID~~~STW031 - Property ID';
--comment on column SAP_SENSITIVE.SENSITIVE is 'Sensitive Customer Classification~~~D2005 - Customer classification for a Supply Point, for identification of where a customer is defined as vulnerable for the purposes of the Security and Emergency Measures (Water and Sewerage Undertakers) Directions ';
comment on table SAP_SENSITIVE is 'This table holds data about SENSITIVE properties, source externally from Target but required from MOSL upload';
create index IDXNO_PROP_1 on SAP_SENSITIVE (STWPROPERTYNUMBER_PK);
--alter table SAP_SENSITIVE add constraint SAP_CHK01_SENSITIVE check (SENSITIVE  in ('Y','N'));

CREATE TABLE SAP_SENSI_EMERGENCY_PLANS
  (STWPROPERTYNUMBER_PK   NUMBER(9,0) NOT NULL ENABLE,
    NONPUBHEALTHRELSITE    NUMBER(1,0) NOT NULL ENABLE,
    NONPUBHEALTHRELSITEDSC VARCHAR2(255 BYTE),
    PUBHEALTHRELSITEARR    number(1,0) not null enable,
    PUBHEALTHRELSITEDSC   varchar2(255 byte) );
comment on column SAP_SENSI_EMERGENCY_PLANS.STWPROPERTYNUMBER_PK is 'Target Property ID~~~STW031 - Property ID';
comment on column SAP_SENSI_EMERGENCY_PLANS.NONPUBHEALTHRELSITE is 'Non-Public Health Related Site Specific Arrangements Flag~~~D2093 - Indication of whether or not a site specific management plan is in place, and not for public health related reasons';
comment on column SAP_SENSI_EMERGENCY_PLANS.NONPUBHEALTHRELSITEDSC IS 'Non-Public Health Related Site Specific Arrangements Free Descriptor~~~D2094 - Free descriptor for indication of the nature of site specific management plan in place, when not for public health related reasons';
comment on column SAP_SENSI_EMERGENCY_PLANS.PUBHEALTHRELSITEARR is 'Public Health Related Site Specific Arrangements Flag~~~D2087 - Boolean flag to Indicate whether or not a site specific management plan is in place for public health related reasons';
comment on table SAP_SENSI_EMERGENCY_PLANS is 'This table holds data about SENSITIVE properties, source externally from Target but required from MOSL upload';

create index IDXNO_PROP_EMEG on SAP_SENSI_EMERGENCY_PLANS (STWPROPERTYNUMBER_PK);

CREATE TABLE SAP_SEWERAGE_TREATMENT_WORKS
(
    STWPROPERTYNUMBER_PK     NUMBER(9,0) CONSTRAINT CH01_STW_PROPERTYNUMBER NOT NULL,
    STWWORKSFLOC             VARCHAR2(10 BYTE)
);


-- LU_TE_REFDESC table

PROMPT 'Create table LU_TE_REFDESC';
CREATE TABLE LU_TE_REFDESC
  (
    TE_REFDESC      VARCHAR2(1000 BYTE) CONSTRAINT CH01_LTR_TE_REFDESC      NOT NULL ENABLE,
    TE_REVISED_NAME VARCHAR2(200 BYTE)  CONSTRAINT CH01_LTR_TE_REVISED_NAME NOT NULL ENABLE,
    TE_CATEGORY     VARCHAR2(100 BYTE)  CONSTRAINT CH01_LTR_TE_CATEGORY     NOT NULL ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 26214400 NEXT 26214400 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  );

PROMPT 'Create index LU_TE_REFDESC_IDX1';
CREATE UNIQUE INDEX LU_TE_REFDESC_IDX1 ON LU_TE_REFDESC
  (
    TE_REFDESC
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 26214400 NEXT 26214400 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  );

PROMPT 'Create table LU_TE_BILLING_CYCLE';
CREATE TABLE LU_TE_BILLING_CYCLE
  (
    LTBC_PERIOD       NUMBER     CONSTRAINT CH01_LTBC_PERIOD       NOT NULL ENABLE,
    LTBC_CYCLE_NUMBER NUMBER     CONSTRAINT CH01_LTBC_CYCLE_NUMBER NOT NULL ENABLE,
    LTBC_START        DATE       CONSTRAINT CH01_LTBC_START        NOT NULL ENABLE,
    LTBC_FINISH       DATE       CONSTRAINT CH01_LTBC_FINISH       NOT NULL ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 26214400 NEXT 26214400 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  );

PROMPT 'Create index LU_TE_BILLING_CYCLE_IDX1';
CREATE UNIQUE INDEX LU_TE_BILLING_CYCLE_IDX1 ON LU_TE_BILLING_CYCLE
  (
    LTBC_PERIOD, LTBC_CYCLE_NUMBER
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 26214400 NEXT 26214400 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  );
  
CREATE TABLE LU_OWC_RECON_MEASURES
  (
    OWC                  VARCHAR2(30 BYTE),
    CONTROL_POINT        VARCHAR2(4 BYTE),
    MO_TABLE             VARCHAR2(30 BYTE),
    OBJ_READ_MEASURE     NUMBER,
    OBJ_DROPPED_MEASURE  NUMBER,
    OBJ_INSERTED_MEASURE NUMBER
  );  

CREATE TABLE BT_OWC_TE_DPID_REF
(
  NO_IWCS                        VARCHAR2(32),
  QUIS                           NUMBER,
  ACCOUNT_NUMBER                 NUMBER(9),
  STW_PROPERTYNUMBER             NUMBER(9),
  OWC                            VARCHAR2(30)
);

CREATE TABLE LU_SS_LANDLORD
(
  SPID                          VARCHAR(13) CONSTRAINT CHK01_SS_LU_LANDLORDSPID NOT NULL,
  LANDLORDSPID                  VARCHAR(13) CONSTRAINT CHK02_SS_LU_LANDLORDSPID NOT NULL
);

ALTER TABLE LU_SS_LANDLORD ADD CONSTRAINT PK_LU_SS_LANDLORD PRIMARY KEY (SPID);

--CREATE LU_OTHER_METER_DPID MANUAL MAPPINGS TABLE - Missing TE Meters
CREATE TABLE LU_OTHER_METER_DPID
(
    DPID_PK                      VARCHAR2(32)
    ,NM_PREFERRED                VARCHAR2(255)
    ,STWACCOUNTNUMBER            NUMBER(10)
    ,STWPROPERTYNUMBER_PK        NUMBER(9)
    ,METERREF                    NUMBER(15)
--    ,SPID_PK                     VARCHAR2(13)
    ,MANUFACTURER_PK	           VARCHAR2(32)
    ,MANUFACTURERSERIALNUM_PK	   VARCHAR2(32)
);

CREATE INDEX LU_OTHER_METER_DPID_IDX1 ON LU_OTHER_METER_DPID (METERREF);
CREATE INDEX LU_OTHER_METER_DPID_IDX2 ON LU_OTHER_METER_DPID (DPID_PK, STWACCOUNTNUMBER);

CREATE TABLE LU_TE_EXCLUSION
(
  NO_IWCS                       NUMBER CONSTRAINT CHK01_LTE_NO_IWCS NOT NULL ENABLE
);


--CREATE LU_TE_METER_PAIRING - To pair target and te working meters
CREATE TABLE LU_TE_METER_PAIRING
  (
    DPID_PK                  VARCHAR2(32 BYTE),
    NO_IWCS_WORKING          NUMBER,
    MET_REF_WORKING          NUMBER,
    MANUFACTURER_PK          VARCHAR2(32 BYTE),
    SERIAL_NO                VARCHAR2(150 BYTE),
    MANUFACTURERSERIALNUM_PK VARCHAR2(32 BYTE),
    PERIOD_WORKING           NUMBER,
    TAGGED_BY                VARCHAR2(40 BYTE),
    TAGGED_WITH              VARCHAR2(40 BYTE),
    TE_PAIRING_OVERRIDE_YN   CHAR(1 BYTE),
    OWC                      VARCHAR2(32 BYTE)
  );
  
  
--CREATE LU_TE_METER_DPID_EXCLUSION MANUAL MAPPINGS TABLE - Associated TE Meters to EXCLUDE from DPIDXREF (water meters not used for calcs)
CREATE TABLE LU_TE_METER_DPID_EXCLUSION
(
    DPID_PK                      VARCHAR2(32)
    ,NM_PREFERRED                VARCHAR2(255)
    ,STWACCOUNTNUMBER            NUMBER(10)
    ,STWPROPERTYNUMBER_PK        NUMBER(9)
--    ,METERREF                    NUMBER(15)
    ,MANUFACTURER_PK	           VARCHAR2(32)
    ,MANUFACTURERSERIALNUM_PK	   VARCHAR2(32)
);

CREATE INDEX LU_TE_METER_DPID_EXC_IDX1 ON LU_OTHER_METER_DPID (MANUFACTURER_PK, MANUFACTURERSERIALNUM_PK);


commit;
exit;



  
  
