--
-- Run_1_ServProvTariffDDL.sql
-- Create tables for SPR tariff items
-- Date - 07/03/2015
-- Written By - Surinder Badhan
--

-- 1. Service Provision Tariff

DROP TABLE BT_SP_TARIFF PURGE;
--DROP PUBLIC SYNONYM BT_SP_TARIFF;

CREATE TABLE BT_SP_TARIFF
(	CD_SERV_PROV        CHAR(5)       NOT NULL,
  CD_SERVICE_ABBREV	  CHAR(8),
  DS_SERVICE	        VARCHAR2(20)  NOT NULL,
	CD_TARIFF           CHAR(10)      NOT NULL,
  DS_TARIFF	          VARCHAR2(40)  NOT NULL,
  CD_REV_CLASS_150    CHAR(5)       NOT NULL, 
  DS_REV_CLASS_150    VARCHAR2(60)  NOT NULL
 	--CONSTRAINT BT_SP_TARIFF_PK PRIMARY KEY (CD_SERV_PROV, CD_TARIFF)   USING INDEX  
) ;
COMMENT ON TABLE BT_SP_TARIFF IS 'Active Target Tariffs by Service Provision';

--CREATE PUBLIC SYNONYM BT_SP_TARIFF FOR BT_SP_TARIFF;

-- 2. Service Provision Algorithm

DROP TABLE BT_SP_TARIFF_ALG PURGE;
--DROP PUBLIC SYNONYM BT_SP_TARIFF_ALG;

CREATE TABLE BT_SP_TARIFF_ALG
(	CD_SERV_PROV        CHAR(5)       NOT NULL,
	CD_TARIFF           CHAR(10)      NOT NULL,
  CD_ALGORITHM        CHAR(5)  NOT NULL, 
  DS_ALGORITHM        VARCHAR2(40) NOT NULL, 
  CONSTRAINT BT_SP_TARIFF_ALG_PK PRIMARY KEY (CD_SERV_PROV,CD_TARIFF,CD_ALGORITHM) USING INDEX
);

COMMENT ON TABLE BT_SP_TARIFF_ALG IS 'Algorithms used by Target Tariff';
--CREATE PUBLIC SYNONYM BT_SP_TARIFF_ALG FOR BT_SP_TARIFF_ALG;


--3. Service Provision Algorithm Item

DROP TABLE BT_SP_TARIFF_ALGITEM;

--DROP PUBLIC SYNONYM BT_SP_TARIFF_ALGITEM;

CREATE TABLE BT_SP_TARIFF_ALGITEM
(	CD_SERV_PROV        CHAR(5)       NOT NULL,
	CD_TARIFF           CHAR(10)      NOT NULL,
  CD_ALGORITHM        CHAR(5)       NOT NULL, 
  CD_BILL_ALG_ITEM    CHAR(5)       NOT NULL,
  DS_BILL_ALG_ITEM    VARCHAR2(40)  NOT NULL 
  --CONSTRAINT BT_SP_TARIFF_ALGITEM_PK PRIMARY KEY (CD_SERV_PROV, CD_TARIFF, CD_ALGORITHM) USING INDEX
) ;

COMMENT ON TABLE BT_SP_TARIFF_ALGITEM  IS 'Algorithm Items used by Tariff, Algorithm';
--CREATE PUBLIC SYNONYM BT_SP_TARIFF_ALGITEM FOR BT_SP_TARIFF_ALGITEM;


--4. Service Provision Tariff Reference Table

DROP TABLE  BT_SP_TARIFF_REFTAB;
--DROP PUBLIC SYNONYM BT_SP_TARIFF_REFTAB;

CREATE TABLE BT_SP_TARIFF_REFTAB
(	CD_SERV_PROV        CHAR(5)       NOT NULL,
	CD_TARIFF           CHAR(10)      NOT NULL,
  CD_ALGORITHM        CHAR(5)       NOT NULL, 
  TP_EQUIPMENT        CHAR(2),
  TP_REF_TAB          NUMBER(3)     NOT NULL, 
  NM_REF_TAB          VARCHAR2(60)  NOT NULL, 
  CONSTRAINT BT_SP_TARIFF_REFTAB_PK PRIMARY KEY (CD_SERV_PROV, CD_TARIFF, CD_ALGORITHM) USING INDEX
) ;

CREATE INDEX BT_SP_TARIFF_REFTAB_IDX1 ON BT_SP_TARIFF_REFTAB (CD_TARIFF, CD_SERV_PROV, TP_EQUIPMENT);
   
COMMENT ON TABLE BT_SP_TARIFF_REFTAB  IS 'Reft Tabs used by Tariff, Algorithm';

--CREATE PUBLIC SYNONYM BT_SP_TARIFF_REFTAB FOR BT_SP_TARIFF_REFTAB;


--5. Service Provision Tariff External Reference Table

DROP TABLE BT_SP_TARIFF_EXTREF PURGE;
CREATE TABLE BT_SP_TARIFF_EXTREF
(	CD_SERV_PROV        CHAR(5)       NOT NULL,
	CD_TARIFF           CHAR(10)      NOT NULL,
  CD_ALGORITHM        CHAR(5)       NOT NULL, 
  TP_ENTITY_332	      CHAR(5)       NOT NULL,
  NO_EXT_REFERENCE    NUMBER(3)     NOT NULL,
  DS_EXT_REFERENCE    VARCHAR(30),
	CONSTRAINT BT_SP_TARIFF_EXTREF_PK PRIMARY KEY (CD_SERV_PROV, CD_TARIFF, CD_ALGORITHM, TP_ENTITY_332, NO_EXT_REFERENCE)   USING INDEX
);


COMMENT ON TABLE BT_SP_TARIFF_EXTREF  IS 'External References used by Tariff/Alg';
--CREATE PUBLIC SYNONYM BT_SP_TARIFF_EXTREF FOR BT_SP_TARIFF_EXTREF;


--6. SPR Tariffs

DROP TABLE BT_SPR_TARIFF PURGE;
--DROP PUBLIC SYNONYM BT_SPR_TARIFF;

CREATE TABLE BT_SPR_TARIFF
(	CD_COMPANY_SYSTEM   CHAR(4)       NOT NULL,
  NO_PROPERTY         NUMBER(9)     NOT NULL,
  NO_SERV_PROV        NUMBER(3)     NOT NULL,
  NO_ACCOUNT          NUMBER(9),
  NO_COMBINE_054      NUMBER(9)     NOT NULL,
  CD_SERV_PROV        CHAR(5)       NOT NULL,
	CD_TARIFF           CHAR(10)      NOT NULL,
  NO_TARIFF_GROUP     NUMBER(3)     NOT NULL , 
  NO_TARIFF_SET       NUMBER(3)     NOT NULL ,
  DT_START            DATE          NOT NULL,  
  DT_END              DATE   
 --	CONSTRAINT BT_SPR_TARIFF_PK PRIMARY KEY (NO_COMBINE_054, NO_TARIFF_GROUP, NO_TARIFF_SET)   USING INDEX 
) ;

CREATE INDEX BT_SPR_TARIFF_IDX1 ON BT_SPR_TARIFF (NO_COMBINE_054);

CREATE INDEX BT_SPR_TARIFF_IDX2 ON BT_SPR_TARIFF (NO_PROPERTY, NO_SERV_PROV, NO_ACCOUNT);

CREATE INDEX BT_SPR_TARIFF_IDX3 ON BT_SPR_TARIFF (CD_COMPANY_SYSTEM, NO_PROPERTY);

COMMENT ON TABLE BT_SPR_TARIFF  IS 'List of Tariffs for Property';
--CREATE PUBLIC SYNONYM BT_SPR_TARIFF FOR BT_SPR_TARIFF;


--7. SPR Tariff Algorithm items

DROP TABLE BT_SPR_TARIFF_ALGITEM PURGE;
--DROP PUBLIC SYNONYM BT_SPR_TARIFF_ALGITEM;

CREATE TABLE BT_SPR_TARIFF_ALGITEM
(	CD_COMPANY_SYSTEM   CHAR(4)       NOT NULL,
  NO_PROPERTY         NUMBER(9)     NOT NULL,
  NO_SERV_PROV        NUMBER(3)     NOT NULL,
  NO_COMBINE_054      NUMBER(9)     NOT NULL,
  CD_SERV_PROV        CHAR(5)       NOT NULL,
	CD_TARIFF           CHAR(10)      NOT NULL,
  NO_TARIFF_GROUP     NUMBER(3)     NOT NULL,
  NO_TARIFF_SET       NUMBER(3)     NOT NULL, 
  CD_BILL_ALG_ITEM	  CHAR(5)       NOT NULL,
  DT_START        	  DATE	        NOT NULL,
  DT_END         	    DATE,
  DS_VALUE            CHAR(20),     
  DT_VALUE            DATE,    
  NO_VALUE            NUMBER(12),
  TP_REF_TAB          NUMBER(3),    
  CD_REF_TAB          CHAR(5)  
	--CONSTRAINT BT_SPR_TARIFF_ALGITEM_PK PRIMARY KEY (CD_SERV_PROV, CD_TARIFF, NO_COMBINE_322, CD_SEASON, NO_PROCESSING_SEQ, NO_SEQ)   USING INDEX 
) ;

CREATE INDEX BT_SPR_TARIFF_ALGITEM_IDX1 ON BT_SPR_TARIFF_ALGITEM (NO_COMBINE_054);

CREATE INDEX BT_SPR_TARIFF_ALGITEM_IDX2 ON BT_SPR_TARIFF_ALGITEM (NO_PROPERTY, NO_SERV_PROV, CD_BILL_ALG_ITEM );

COMMENT ON TABLE BT_SPR_TARIFF_ALGITEM  IS 'BT_SPR_TARIFF_ALGITEM';
--CREATE PUBLIC SYNONYM BT_SPR_TARIFF_ALGITEM FOR BT_SPR_TARIFF_ALGITEM;

--8. SPR Tariff External Reference

DROP TABLE BT_SPR_TARIFF_EXTREF PURGE;
--DROP PUBLIC SYNONYM BT_SPR_TARIFF_EXTREF;

CREATE TABLE BT_SPR_TARIFF_EXTREF
( CD_COMPANY_SYSTEM   CHAR(4)       NOT NULL,
  NO_PROPERTY         NUMBER(9)     NOT NULL,
  NO_SERV_PROV        NUMBER(3),
  NO_COMBINE_054      NUMBER(9)     NOT NULL,
  CD_SERV_PROV        CHAR(5)       NOT NULL,
	CD_TARIFF           CHAR(10)      NOT NULL,
  NO_TARIFF_GROUP     NUMBER(3)     NOT NULL,
  NO_TARIFF_SET       NUMBER(3)     NOT NULL, 
  TP_ENTITY_332       CHAR(5)       NOT NULL,
  DS_EXT_REF_GROUP    VARCHAR2(30)  NOT NULL,
  NO_EXT_REFERENCE    NUMBER(3)     NOT NULL,   
  DS_EXT_REFERENCE    VARCHAR2(30)  NOT NULL,
  NO_EXT_REF_DEBT     NUMBER(9)     NOT NULL,    
  CD_EXT_REF          VARCHAR2(60),
  CD_WORK_ORDER       NUMBER(9),      
  DT_EXT_REF          DATE,
  FG_EXT_REF          CHAR(1),
  NO_EXT_REF          NUMBER(12),
  CD_REF_TAB          CHAR(5),      
  TP_REF_TAB          NUMBER(3)  
	--CONSTRAINT BT_SPR_TARIFF_EXTREF_PK PRIMARY KEY (CD_SERV_PROV,  CD_TARIFF, TP_ENTITY_332)   USING INDEX
);

CREATE INDEX BT_SPR_TARIFF_EXTREF ON BT_SPR_TARIFF_EXTREF (NO_PROPERTY, NO_SERV_PROV, TP_ENTITY_332, DS_EXT_REFERENCE);

COMMENT ON TABLE BT_SPR_TARIFF_EXTREF  IS 'BT_SPR_TARIFF_EXTREF';

--CREATE PUBLIC SYNONYM BT_SPR_TARIFF_EXTREF FOR BT_SPR_TARIFF_EXTREF;

 
--9. SP Tariff Split

DROP TABLE BT_SP_TARIFF_SPLIT PURGE;
--DROP PUBLIC SYNONYM BT_SP_TARIFF_SPLIT;

CREATE TABLE BT_SP_TARIFF_SPLIT
(	CD_SERVICE_PROV       CHAR(5) NOT NULL,
	CD_TARIFF             CHAR(10) NOT NULL,
	CD_BILL_ALG_ITEM      CHAR(5), 
	CD_REF_TAB            CHAR(5), 
	CD_SPLIT_TARIFF       VARCHAR2(16), 
	DS_SPLIT_TARIFF       VARCHAR2(4000)
	--CONSTRAINT BT_SP_TARIFF_SPLIT_PK PRIMARY KEY (CD_SERV_PROV,  CD_TARIFF, TP_ENTITY_332)   USING INDEX
);


CREATE INDEX BT_SP_TARIFF_SPLIT_IDX1 ON BT_SP_TARIFF_SPLIT (CD_TARIFF); 

CREATE INDEX BT_SP_TARIFF_SPLIT_IDX2 ON BT_SP_TARIFF_SPLIT (CD_TARIFF, CD_BILL_ALG_ITEM, CD_REF_TAB); 
 
COMMENT ON TABLE BT_SP_TARIFF_SPLIT  IS 'BT_SP_TARIFF_SPLIT';

--CREATE PUBLIC SYNONYM BT_SP_TARIFF_SPLIT FOR BT_SP_TARIFF_SPLIT;

-- MPW charges

DROP TABLE BT_SC_MPW PURGE;
--DROP PUBLIC SYNONYM BT_SC_MPW;

CREATE TABLE BT_SC_MPW
(	NO_PROPERTY             NUMBER(9)     NOT NULL,
  NO_SERV_PROV            NUMBER(3)     NOT NULL,
  NO_COMBINE_054          NUMBER(9)     NOT NULL,
  CD_SERV_PROV            CHAR(5)       NOT NULL,
  D2079_MAXDAILYDMD       NUMBER(12)    NOT NULL, 
	D2080_DLYRESVDCAP       NUMBER(12)    NOT NULL,   
	D2056_TARIFFCODE        VARCHAR2(32)  NOT NULL,  
 	CONSTRAINT BT_SC_MPW_PK PRIMARY KEY (NO_COMBINE_054)   USING INDEX   
) ;

--CREATE INDEX BT_SC_MPW_IDX1 ON BT_SC_MPW (NO_PROPERTY, NO_COMBINE_054);

COMMENT ON TABLE BT_SC_MPW  IS 'BT_SC_MPW';
--CREATE PUBLIC SYNONYM BT_SC_MPW FOR BT_SC_MPW;

-- Unmeasured (UW)      

DROP TABLE BT_SC_UW PURGE;
--DROP PUBLIC SYNONYM BT_SC_UW;
                  
CREATE TABLE BT_SC_UW
(	NO_PROPERTY               NUMBER(9)       NOT NULL,
  NO_SERV_PROV              NUMBER(3)       NOT NULL,
  NO_COMBINE_054            NUMBER(9)       NOT NULL,
  CD_SERV_PROV              CHAR(5)         NOT NULL,
  D2018_TYPEACOUNT          NUMBER(3),
	D2019_TYPEBCOUNT          NUMBER(3),   
  D2020_TYPECCOUNT          NUMBER(3),
	D2021_TYPEDCOUNT          NUMBER(3),
  D2022_TYPEECOUNT          NUMBER(3),
	D2024_TYPEFCOUNT          NUMBER(3),
  D2046_TYPEGCOUNT          NUMBER(3),
	D2048_TYPEHCOUNT          NUMBER(3),
  D2058_TYPEADESCRIPTION    VARCHAR2(255),
  D2059_TYPEBDESCRIPTION    VARCHAR2(255),
  D2060_TYPECDESCRIPTION    VARCHAR2(255),
  D2061_TYPEDDESCRIPTION    VARCHAR2(255),    
  D2062_TYPEEDESCRIPTION    VARCHAR2(255),
  D2064_TYPEFDESCRIPTION    VARCHAR2(255), 
  D2065_TYPEGDESCRIPTION    VARCHAR2(255),
  D2069_TYPEHDESCRIPTION    VARCHAR2(255),   
  D2067_TARIFFCODE          VARCHAR2(32)    NOT NULL,  
  NO_TARIFF_GROUP           NUMBER(3)       NOT NULL , 
  NO_TARIFF_SET             NUMBER(3)       NOT NULL ,  
 	CONSTRAINT BT_SC_UW_PK PRIMARY KEY (NO_COMBINE_054, NO_TARIFF_GROUP, NO_TARIFF_SET)   USING INDEX 
) ;
--CREATE INDEX BT_SC_UW_IDX1 ON BT_SC_UW (NO_PROPERTY, NO_COMBINE_054);

COMMENT ON TABLE BT_SC_UW  IS 'BT_SC_UW';
--CREATE PUBLIC SYNONYM BT_SC_UW FOR BT_SC_UW;
/
exit;

