--
-- DDL_BT_METER_SPID.sql
-- Create Meter SPIDs temp table
-- Date - 11/04/2016
-- Written By - Dominic Cheung
--
-- Subversion $Revision: 4023 $
--

--DROP TABLE BT_METER_SPID PURGE;
--DROP PUBLIC SYNONYM BT_METER_SPID;

 CREATE TABLE BT_METER_SPID 
  (
    CORESPID                VARCHAR2(10),
 	NO_PROPERTY             NUMBER(9), 
    SPID_PK                 VARCHAR2(13),
    SUPPLY_POINT_CODE       VARCHAR2(2)
   );

CREATE INDEX BT_METER_SPID_IDX1 ON BT_METER_SPID (NO_PROPERTY, CORESPID); 

CREATE INDEX BT_METER_SPID_IDX2 ON BT_METER_SPID (CORESPID); 

COMMENT ON TABLE BT_METER_SPID  IS 'Meter SPIDs temp table BT_METER_SPID';
--CREATE PUBLIC SYNONYM BT_METER_SPID FOR BT_METER_SPID;

commit;
exit;


