--Create table BT_SP_TARIFF_REFTAB
--N.Henderson - 12/04/2016
-- Subversion $Revision: 4023 $
--Attempt to drop the table first. Will generate warnings if does not
--exist but can be ignored.

--DROP TABLE BT_SP_TARIFF_REFTAB PURGE;


  CREATE TABLE BT_SP_TARIFF_REFTAB 
   (CD_SERV_PROV CHAR(5 BYTE) NOT NULL ENABLE, 
	CD_TARIFF CHAR(10 BYTE) NOT NULL ENABLE, 
	CD_ALGORITHM CHAR(5 BYTE) NOT NULL ENABLE, 
	TP_EQUIPMENT CHAR(2 BYTE), 
	TP_REF_TAB NUMBER(3,0) NOT NULL ENABLE, 
	NM_REF_TAB VARCHAR2(60 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT BT_SP_TARIFF_REFTAB_PK PRIMARY KEY (CD_SERV_PROV, CD_TARIFF, CD_ALGORITHM)
  );

   COMMENT ON TABLE BT_SP_TARIFF_REFTAB  IS 'Reft Tabs used by Tariff, Algorithm';

  --Statement Below commented out as there is already an index being created on this field as 
  --it is a primary key
  --CREATE UNIQUE INDEX BT_SP_TARIFF_REFTAB_PK01 ON BT_SP_TARIFF_REFTAB (CD_SERV_PROV, CD_TARIFF, CD_ALGORITHM);
  CREATE INDEX BT_SP_TARIFF_REFTAB_IDX1 ON BT_SP_TARIFF_REFTAB (CD_TARIFF, CD_SERV_PROV, TP_EQUIPMENT);

   commit;
   exit;
