--
-- 20_DDL_BT_SENSI_SITE_SPECIFIC.sql
-- Create BT SENSI_SITE_SPECIFIC table
-- Subversion $Revision: 4584 $
-- Date - 24/06/2016
-- Written By - Ola Badmus
--
  
CREATE TABLE BT_SENSI_SITE_SPECIFIC
  (
    NO_LEGAL_ENTITY NUMBER(9,0),
    DIALYSIS       VARCHAR2(10 BYTE),
    HAEMO           VARCHAR2(10 BYTE),
    "HOUSE, OLD"      VARCHAR2(10 BYTE),
    LEARNING       VARCHAR2(10 BYTE),
    HEARING         VARCHAR2(10 BYTE),
    SIGHT           VARCHAR2(10 BYTE),
    VOCAL          VARCHAR2(10 BYTE),
    SENSITIVE       VARCHAR2(5 BYTE)
  ) ;
  
CREATE INDEX IND_BT_SENSI_SITE_SPEC ON BT_SENSI_SITE_SPECIFIC (NO_LEGAL_ENTITY);


COMMENT ON COLUMN BT_SENSI_SITE_SPECIFIC.DIALYSIS IS 'Dialysis on Site';
COMMENT ON COLUMN BT_SENSI_SITE_SPECIFIC.HAEMO IS 'Haemodialysis on Site';
COMMENT ON COLUMN BT_SENSI_SITE_SPECIFIC."HOUSE, OLD"  IS 'Pensioner Permanently Living on Site';
COMMENT ON COLUMN BT_SENSI_SITE_SPECIFIC. LEARNING IS 'Contact Person has a Learning Disability';
COMMENT ON COLUMN BT_SENSI_SITE_SPECIFIC.HEARING IS 'Contact Person has a Hearing Impairment';
COMMENT ON COLUMN BT_SENSI_SITE_SPECIFIC.SIGHT IS 'Contact Person has a Visual Impairment';
COMMENT ON COLUMN BT_SENSI_SITE_SPECIFIC.VOCAL IS 'Contact Person has a Vocal Impairment';

commit;
EXIT;
