------------------------------------------------------------------------------
-- TASK						: 	MOSL RDBMS PATCHES 
--
-- AUTHOR         			: 	Nigel Henderson
--
-- FILENAME       			: 	P00012.sql
--
--
-- Subversion $Revision: 5300 $	
--
--Date 						16/03/2016
--Issue: 					Rework on MO_CUSTOMER table.  Composite PK requried on 
--							CUSTOMERNUMBER_PK and STWPROPERTYNUMBER_PK
--							with new FK's from MO_ELIGIBLE_PREMISES
--							and MO_CUST_ADDRESS
--
-- Changes applied
---------------------------- Modification History ----------------------------------------------------------
--
-- Version     	Date            Author         	Description
-- ---------    ----------      -------         -----------------------------------------------------------
-- V0.01		    31/08/2016			S.Badhan		    Remove addition of PRIMARY KEY on MO_CUSTOMER, already exists.
-- 
------------------------------------------------------------------------------------------------------------


--DISABLE AND DROP CONSTRAINTS
ALTER TABLE MO_ELIGIBLE_PREMISES DISABLE CONSTRAINT  FK_CUSTOMERID_PK;
ALTER TABLE MO_ELIGIBLE_PREMISES DROP CONSTRAINT  FK_CUSTOMERID_PK;
ALTER TABLE MO_CUST_ADDRESS DISABLE CONSTRAINT FK_CUSTOMERNUMBER_PK;
ALTER TABLE MO_CUST_ADDRESS DROP CONSTRAINT FK_CUSTOMERNUMBER_PK;
ALTER TABLE MO_CUSTOMER DISABLE CONSTRAINT PK_01_CUSTOMERNUMBER;
ALTER TABLE MO_CUSTOMER DROP CONSTRAINT PK_01_CUSTOMERNUMBER;
--ALTER TABLE MO_CUSTOMER DISABLE CONSTRAINT PK_CUSTOMER_COMP;
--ALTER TABLE MO_CUSTOMER DROP CONSTRAINT PK_CUSTOMER_COMP;
ALTER TABLE MO_CUSTOMER DISABLE CONSTRAINT FK_STWPROPERTYNUMBER_PK01;
ALTER TABLE MO_CUSTOMER DROP CONSTRAINT FK_STWPROPERTYNUMBER_PK01;

--ALTER CUSTOMERNUMBER_PK SO THAT IS CAN BE USED AS A FOREIGN KEY LATER
--ALTER TABLE MO_CUST_ADDRESS ADD UNIQUE (CUSTOMERNUMBER_PK);

--ADD COMPOSITE PRIMARY KEY ON MO_CUSTOMER 
--ALTER TABLE MO_CUSTOMER ADD CONSTRAINT PK_CUSTOMER_COMP PRIMARY KEY (CUSTOMERNUMBER_PK,STWPROPERTYNUMBER_PK);

--ADD FK FOR THE MO_ELIGIBLE_PREMISES TABLE
ALTER TABLE "MO_CUSTOMER" ADD CONSTRAINT FK_CUST_PROP FOREIGN KEY("STWPROPERTYNUMBER_PK") REFERENCES "MO_ELIGIBLE_PREMISES"("STWPROPERTYNUMBER_PK");
--ADD FK FOR THE MO_CUST_ADDRESS TABLE
ALTER TABLE "MO_CUSTOMER" ADD CONSTRAINT FK_CUST_ADDR FOREIGN KEY("CUSTOMERNUMBER_PK") REFERENCES "MO_CUST_ADDRESS"("CUSTOMERNUMBER_PK");
commit;
exit;

