--
-- CREATED        		: 	19/05/2016
--	
-- DESCRIPTION 		   	: 	Add Customer Constraints
--
--
-- Subversion $Revision: 5831 $	
--							
--
-- ASSOCIATED FILES		:	
-- ASSOCIATED SCRIPTS  	:	
--
--
---------------------------- Modification History ----------------------------------------------------------
--
-- Version    Date            Author       Description
-- ---------  ----------      -------      -----------------------------------------------------------------
-- V0.02      13/10/2016      S.Badhan     Remove drop of FK_CUST_ADDR, does not exist
-- V0.01		  19/05/201       M.Marron	   Drop FK_CUST_ADDR constraints to MOUTRAN tariff tables
------------------------------------------------------------------------------------------------------------
-- CHANGES
------------------------------------------------------------------------------------------------------------
--ALTER TABLE MO_CUSTOMER DROP CONSTRAINT FK_CUST_ADDR;
--commit;
exit;