--DB patch - 15 script
--
-- Subversion $Revision: 4023 $	
--
------------------------------------------------------

---- add sewerage charge adjustment table

CREATE TABLE MO_TARIFF_TYPE_SCA
(
TARIFF_TYPE_PK NUMBER(12) NOT NULL,
TARIFF_VERSION_PK NUMBER(12) ,
SECTION154A NUMBER(6,2) 
);
ALTER TABLE MO_TARIFF_TYPE_SCA ADD PRIMARY KEY (TARIFF_TYPE_PK);
---- add water charge adjustment table

CREATE TABLE MO_TARIFF_TYPE_WCA
(
TARIFF_TYPE_PK NUMBER(12) NOT NULL,
TARIFF_VERSION_PK NUMBER(12) ,
SECTION154A NUMBER(6,2) 
);
ALTER TABLE MO_TARIFF_TYPE_WCA ADD PRIMARY KEY (TARIFF_TYPE_PK);

----add table  Tariff Standing Data (per Wholesaler)

CREATE TABLE MO_TARIFF_STANDING_DATA
(
WHOLESALER VARCHAR2(10) NOT NULL,
DEFAULTRETURNTOSEWER NUMBER(5,2) ,
VACANCYCHARGINGMETHODWATER VARCHAR(128) ,
VACANCYCHARGINGMETHODSEWERAGE VARCHAR(128) ,
TEMPDISCONCHARGINGMETHODWAT VARCHAR(128) ,
TEMPDISCONCHARGINGMETHODSEW VARCHAR(128)  
);
ALTER TABLE MO_TARIFF_STANDING_DATA ADD PRIMARY KEY (WHOLESALER);
---- add state column to tariff version table
ALTER TABLE MO_TARIFF_VERSION ADD STATE VARCHAR2(10);

---- remove tariff standing fields from mo_tariff and mo_tariff_version
ALTER TABLE MO_TARIFF_VERSION DROP COLUMN DEFAULTRETURNTOSEWER;
ALTER TABLE MO_TARIFF DROP COLUMN vacancychargingmethodwater;
ALTER TABLE MO_TARIFF DROP COLUMN vacancychargingmethodsewerage;
ALTER TABLE MO_TARIFF DROP COLUMN TEMPDISCONCHARGINGMETHODWAT;
ALTER TABLE MO_TARIFF DROP COLUMN TEMPDISCONCHARGINGMETHODSEW;
---- remove unique constraint on tariff version
ALTER TABLE MO_TARIFF_VERSION DROP CONSTRAINT PK_02_TARIFFCODE;
commit;
exit;
