------------------------------------------------------------------------------
-- TASK				: 	MOSL RDBMS PATCHES 
--
-- AUTHOR         			: 	Nigel Henderson
--
-- FILENAME       			: 	MO_P0013.sql
--
--
-- Subversion $Revision: 5329 $	
--
-- CREATED        			: 	21/03/2016
--	
-- DESCRIPTION 		   	: 	This file contains all ongoing patches that are made to the MOSL database
--
-- NOTES  				:	Place a summery at the top of the file with more detailed information 
--						where the patch is applied in this script (if needed)
--
-- ASSOCIATED FILES			:	
-- ASSOCIATED SCRIPTS  		:	
--
--
---------------------------- Modification History ----------------------------------------------------------
--
-- Version     	Date          Author         Description
-- ---------    ----------    -------        ------------------------------------------------
-- V0.01			21/03/2016		NJH		 Primary key changes 
--									 Constraint changes	
--									 Indexes
-- V0.02		    1/08/2016			S.Badhan		    Remove disable of FK_SERVICECOMPONENTREF_PK01, does not exist.
--
------------------------------------------------------------------------------------------------------------
--Changes



--ALTER PRIMARY KEY ON MO_SERVICE_COMPONENT
ALTER TABLE MO_SERVICE_COMPONENT MODIFY (SERVICECOMPONENTREF_PK NUMBER(12,0));
--ALTER PRIMARY KEY ON MO_SERVICE_COMPONENT_TYPE
ALTER TABLE MO_SERVICE_COMPONENT_TYPE MODIFY (SERVICECOMPONENT_PK NUMBER (12,0));
ALTER CONSTRAINT ON MO_SERVICE_COMPONENT



--ALTER CONSTRAINT RF01_STWSERVICETYPE ON MO_SERVICE_COMPONENT
ALTER TABLE MO_SERVICE_COMPONENT DROP CONSTRAINT RF01_STWSERVICETYPE;
ALTER TABLE MO_SERVICE_COMPONENT ADD CONSTRAINT RF01_STWSERVICETYPE CHECK (STWSERVICETYPE IN ('W','UW','TW','XSYOR','XNTHA','US','XUWES','SU','XSWES','MSWD','UNSS','XZNWE','XZWEL','XDANG','XDYOR','UD','XNWES','XSANG','XUYOR','XFYOR','XNYOR','XNNWE','XZTHA','SW','XUANG','XFWEL','XFNWE','XNWEL','XUTHA','XZYOR','XUWEL','PP01','XFWES','XSNW','XFTHA','XSWEL','S','XDNW','XSTHA','XUNWE')); 


--ALTER DATA TYPES ON GPS RELATED COLUMNS
ALTER TABLE MO_METER MODIFY (METEROUTREADERGPSX NUMBER(7,1));
ALTER TABLE MO_METER MODIFY (METEROUTREADERGPSY NUMBER(7,1));
ALTER TABLE MO_METER MODIFY (GPSX NUMBER(7,1));
ALTER TABLE MO_METER MODIFY (GPSY NUMBER(7,1));

--FIX MO_METER TABLE
ALTER TABLE MO_METER RENAME COLUMN SUPPLYPOINTREF TO FREEDESCRIPTOR;
ALTER TABLE MO_METER MODIFY (FREEDESCRIPTOR VARCHAR(1024));
ALTER TABLE MO_METER MODIFY (METERADDITIONREASON NULL);

--DISABLE FOREIGN KEY CONSTRAINT ON MO_SERVICE_COMPONENT_TYPE, TEMPORARY ONLY, WILL NEED TO BE ENABLED AGAIN AT SOME POINT
--ALTER TABLE MO_SERVICE_COMPONENT DISABLE CONSTRAINT FK_SERVICECOMPONENTREF_PK01;


--ADD INDEXES
CREATE INDEX idx01_CORESPID_PK on LU_SPID_RANGE (CORESPID_PK);
CREATE INDEX idx01_STWPROPERTYNUMBER_PK ON LU_CROSSBORDER (STWPROPERTYNUMBER_PK);
--CREATE INDEX idx02_CORESPID_PK ON LU_SPID_RANGE (CORESPID_PK);

commit;
exit;


