------------------------------------------------------------------------------
-- TASK				: 	MIG RDBMS PATCHES 
--
-- AUTHOR         		: 	D.Cheung
--
-- FILENAME       		: 	P00002.sql
--
--
-- Subversion $Revision: 4023 $	
--
--Date 					11/05/2016
--
--Issue: 				JOBREFs entries for TARIFF jobs not being created in MIG_JOBREF as part of BUILD or BATCH 
-- 
--Changes				Manually insert TARIFF entries into MIG_JOBREF 
--
--
--
---------------------------- Modification History ----------------------------------------------------------
--
-- Version     		Date            Author         	Description
-- ---------      	----------      -------         ------------------------------------------------
-- v0.01			11/05/2016		D.Cheung		 
--
--
-- 
------------------------------------------------------------------------------------------------------------
--INSERT MIG_JOBREF RECORDS FOR TARRIFF JOBS
------------------------------------------------
INSERT INTO MIG_JOBREF (NO_JOB, NM_PROCESS, ERR_TOLERANCE, EXP_TOLERANCE, WAR_TOLERANCE, NO_STREAM, NO_RANGE_MIN, NO_RANGE_MAX, NO_COMMIT) VALUES(10, 'P_MOU_TRAN_TARIFF_AS', 999, 999, 999, 50, 1, 999999999, 999);
INSERT INTO MIG_JOBREF (NO_JOB, NM_PROCESS, ERR_TOLERANCE, EXP_TOLERANCE, WAR_TOLERANCE, NO_STREAM, NO_RANGE_MIN, NO_RANGE_MAX, NO_COMMIT) VALUES (11, 'P_MOU_TRAN_TARIFF_AW', 999, 999, 999, 50, 1, 999999999, 999);
INSERT INTO MIG_JOBREF (NO_JOB, NM_PROCESS, ERR_TOLERANCE, EXP_TOLERANCE, WAR_TOLERANCE, NO_STREAM, NO_RANGE_MIN, NO_RANGE_MAX, NO_COMMIT) VALUES (12, 'P_MOU_TRAN_TARIFF_MPW', 999, 999, 999, 50, 1, 999999999, 999);
INSERT INTO MIG_JOBREF (NO_JOB, NM_PROCESS, ERR_TOLERANCE, EXP_TOLERANCE, WAR_TOLERANCE, NO_STREAM, NO_RANGE_MIN, NO_RANGE_MAX, NO_COMMIT) VALUES (13, 'P_MOU_TRAN_TARIFF_MS', 999, 999, 999, 50, 1, 999999999, 999);
INSERT INTO MIG_JOBREF (NO_JOB, NM_PROCESS, ERR_TOLERANCE, EXP_TOLERANCE, WAR_TOLERANCE, NO_STREAM, NO_RANGE_MIN, NO_RANGE_MAX, NO_COMMIT) VALUES (14, 'P_MOU_TRAN_TARIFF_SW', 999, 999, 999, 50, 1, 999999999, 999);
INSERT INTO MIG_JOBREF (NO_JOB, NM_PROCESS, ERR_TOLERANCE, EXP_TOLERANCE, WAR_TOLERANCE, NO_STREAM, NO_RANGE_MIN, NO_RANGE_MAX, NO_COMMIT) VALUES (15, 'P_MOU_TRAN_TARIFF_TE', 999, 999, 999, 50, 1, 999999999, 999);
INSERT INTO MIG_JOBREF (NO_JOB, NM_PROCESS, ERR_TOLERANCE, EXP_TOLERANCE, WAR_TOLERANCE, NO_STREAM, NO_RANGE_MIN, NO_RANGE_MAX, NO_COMMIT) VALUES (16, 'P_MOU_TRAN_TARIFF_US', 999, 999, 999, 50, 1, 999999999, 999);
INSERT INTO MIG_JOBREF (NO_JOB, NM_PROCESS, ERR_TOLERANCE, EXP_TOLERANCE, WAR_TOLERANCE, NO_STREAM, NO_RANGE_MIN, NO_RANGE_MAX, NO_COMMIT) VALUES (17, 'P_MOU_TRAN_TARIFF_UW', 999, 999, 999, 50, 1, 999999999, 999);
INSERT INTO MIG_JOBREF (NO_JOB, NM_PROCESS, ERR_TOLERANCE, EXP_TOLERANCE, WAR_TOLERANCE, NO_STREAM, NO_RANGE_MIN, NO_RANGE_MAX, NO_COMMIT) VALUES (18, 'P_MOU_TRAN_TARIFF_HD', 999, 999, 999, 50, 1, 999999999, 999);
              
commit;
exit;
