------------------------------------------------------------------------------
-- TASK				: 	MOSL RDBMS CREATION of Supporting Lookup tables
--
-- AUTHOR         		: 	Michael Marron
--
-- FILENAME       		: 	01_DDL_MOSL_Lookup_TABLES_ALL.sql
--
-- CREATED        		: 	26/02/2016
-- Subversion $Revision: 4023 $
--	
-- DESCRIPTION 		   	: 	Creates all supporting lookup tables required for MOSL database
--
-- NOTES  			:	Used in conjunction with the following scripts to re-initialise the
-- 							database.  When re-creating the database run the scripts in order
-- 							as detailed below (.sql).
--
-- ASSOCIATED FILES		:	MOSL_PDM_CORE.xlsm
-- ASSOCIATED SCRIPTS  		:	02_TRUNC_Lookups_ALL.sql
--					
--
---------------------------- Modification History ----------------------------------------------------------
--
-- Version     		Date          	Author         		Description
-- ---------      	----------     -------            	 ------------------------------------------------
-- V0.01       		26/02/2016    	M.Marron	     	Initial version add LU_SPID_RANGE, LU_CONSTUCTION_SITE and LU_PUBHEALTHRESITE
-- V0.02		    26/02/2016      M.Marron            Corrected BUILDINGWATERSTATUS on LU_CONSTUCTION_SITE table, set it to Not Null
-- V0.03            14/03/2016      M.Marron            Added LU_LANDLORD, LU_CROSSBORDER, LU_CLOCKOVER & LU_DATALOGGERS.
-- v0.04            15/03/2016      M.Marron            updated comments on LU_CROSSBORDER  
-- v0.05            18/03/2016      M.Marron	        Added LU_TARIFF,  LU_SERVICE_CATEGORY, LU_SERVICE_COMP_CHARGES, LU_TARIFF_SPECIAL_AGREEMENTS
-- v0.06            31/03/2016      M.Marron	        updated LU_DATALOGGERS to add logger ID and set STWMETERREF_PK, MANUFACTURER_PK to NULLABLE 
-- v0.07            13/05/2016      M.Marron	        updated LU_CROSSBORDER to added a unique constraint on SPID_PK to avoid failures in Supply point 
------------------------------------------------------------------------------------------------------------
--
-- Create LU_SPID_RANGE table
CREATE TABLE LU_SPID_RANGE
(
SPID_PK VARCHAR(13) CONSTRAINT CH01_LU_SPID_PK NOT NULL,
-- STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CH01_LU_STWPROPERTYNUMBER_PK NOT NULL, removed as not needed
CORESPID_PK VARCHAR(10) CONSTRAINT CH01_LU_CORESPID_PK NOT NULL,
SERVICECATEGORY VARCHAR(1) CONSTRAINT CH01_LU_SERVICECATEGORY NOT NULL
);
--
-- set primary key
ALTER TABLE LU_SPID_RANGE ADD CONSTRAINT PK_LU_SPID PRIMARY KEY (SPID_PK);
--
-- add table and field comments
COMMENT ON Table LU_SPID_RANGE IS 'This table holds the MOSL SPID range allocated to Severn Trent Water';
COMMENT ON COLUMN LU_SPID_RANGE.SPID_PK IS 'Primary key for a SPID. It is the full 13 char value issued by MOSLand is the unique identifer for the supply point';
-- COMMENT ON COLUMN LU_SPID_RANGE.STWPROPERTYNUMBER_PK IS 'Target NO_PROPERTY ~~~STW031 - NO_PROPERTY'; removed not needed
COMMENT ON COLUMN LU_SPID_RANGE.SERVICECATEGORY IS 'Service Category~~~D2002 - Identifies the Service Category for a Supply Point (Water Services or Sewerage Services) “W” = Water and “S” = Sewerage';
--
--
-- Create LU_PUBHEALTHRESITE table
CREATE TABLE LU_PUBHEALTHRESITE
(
STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CH01_LU_STWPROPERTYNUMBER NOT NULL,
NONPUBHEALTHRELSITE  NUMBER(1) CONSTRAINT CH01_LU_NONPUBHEALTHRELSITE NOT NULL,
NONPUBHEALTHRELSITEDSC VARCHAR(255) ,
PUBHEALTHRELSITEARR NUMBER(1) CONSTRAINT CH01_LU_PUBHEALTHRELSITEARR NOT NULL
);
--
-- set primary key & Constriants
ALTER TABLE LU_PUBHEALTHRESITE ADD CONSTRAINT PK01_LU_STWPROPERTYNUMBER PRIMARY KEY (STWPROPERTYNUMBER_PK);
ALTER TABLE LU_PUBHEALTHRESITE ADD CONSTRAINT CHK02_LU_NONPUBHEALTHRELSITE  CHECK (NONPUBHEALTHRELSITE  IN (0,1));
ALTER TABLE LU_PUBHEALTHRESITE ADD CONSTRAINT CHK02_LU_PUBHEALTHRELSITEARR CHECK (PUBHEALTHRELSITEARR IN (0,1));
--
-- add table and field comments
COMMENT ON Table "LU_PUBHEALTHRESITE" IS 'This table holds data about SENSITIVE properties, source externally from Target but required from MOSL upload';
COMMENT ON COLUMN LU_PUBHEALTHRESITE.STWPROPERTYNUMBER_PK IS 'Target NO_PROPERTY~~~STW031 - NO_PROPERTY';
COMMENT ON COLUMN LU_PUBHEALTHRESITE.NONPUBHEALTHRELSITE  IS 'Non-Public Health Related Site Specific Arrangements Flag~~~D2093 - Indication of whether or not a site specific management plan is in place, and not for public health related reasons';
COMMENT ON COLUMN LU_PUBHEALTHRESITE.NONPUBHEALTHRELSITEDSC IS 'Non-Public Health Related Site Specific Arrangements Free Descriptor~~~D2094 - Free descriptor for indication of the nature of site specific management plan in place, when not for public health related reasons';
COMMENT ON COLUMN LU_PUBHEALTHRESITE.PUBHEALTHRELSITEARR IS 'Public Health Related Site Specific Arrangements Flag~~~D2087 - Boolean flag to Indicate whether or not a site specific management plan is in place for public health related reasons';
--
--
-- Create LU_CONSTRUCTION_SITE table  (updated BUILDINGWATERSTATUS to not null)
CREATE TABLE LU_CONSTRUCTION_SITE
(
STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CH02_LU_STWPROPERTYNUMBER NOT NULL,
BUILDINGWATERSTATUS NUMBER(1) CONSTRAINT CH01_LU_BUILDINGWATERSTATUS NOT NULL
);
--
-- set primary key
ALTER TABLE LU_CONSTRUCTION_SITE ADD CONSTRAINT PK02_LU_STWPROPERTYNUMBER PRIMARY KEY (STWPROPERTYNUMBER_PK);
ALTER TABLE LU_CONSTRUCTION_SITE ADD CONSTRAINT CHK02_LU_BUILDINGWATERSTATUS CHECK (BUILDINGWATERSTATUS IN (0,1));
--
-- add table and field comments
COMMENT ON Table "LU_CONSTRUCTION_SITE" IS 'This table holds data about properties which are still under construction, source externally from Target but required from MOSL upload';
COMMENT ON COLUMN LU_CONSTRUCTION_SITE.STWPROPERTYNUMBER_PK IS 'Target NO_PROPERTY~~~STW031 - NO_PROPERTY';
COMMENT ON COLUMN LU_CONSTRUCTION_SITE.BUILDINGWATERSTATUS IS 'Building Water Status~~~D2029 - Boolean flag to indicate if the site is a building construction site. ';
--
-- version 0.03 Added LU_LANDLORD, LU_CROSSBORDER, LU_CLOCKOVER & LU_DATALOGGERS
--
-- Create LU_LANDLORD   
CREATE TABLE LU_LANDLORD
(
STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CHK10_LU_STWPROPERTYNUMBER NOT NULL,
LANDLORDSPID VARCHAR(13) CONSTRAINT CHK01_LU_LANDLORDSPID NOT NULL,
SERVICECATEGORY VARCHAR(1) CONSTRAINT CHK10_LU_SERVICECATEGORY NOT NULL
);
--
-- set primary key
-- 
--
-- add table and field comments
COMMENT ON COLUMN LU_LANDLORD.STWPROPERTYNUMBER_PK IS 'Target NO_PROPERTY~~~STW031 - NO_PROPERTY to which the landlord SPID applies'; 
COMMENT ON COLUMN LU_LANDLORD.LANDLORDSPID IS 'Landlord SPID~~~D2070 - Identifies the Landlord Supply point in a multi-occupancy Eligible Premises.  The valid set for this is all SPIDs';
COMMENT ON COLUMN LU_LANDLORD.SERVICECATEGORY IS 'Service Category~~~D2002 - Identifies the Service Category for a Supply Point to which this landlord SPID applies if required';
--
-- 
-- Create LU_CROSSBORDER
CREATE TABLE LU_CROSSBORDER
(
STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CHK04_LU_STWPROPERTYNUMBER NOT NULL,
CORESPID_PK VARCHAR(10),
SPID_PK VARCHAR(13) CONSTRAINT CHK02_LU_SPID_PK NOT NULL,
SERVICECATEGORY VARCHAR(1) CONSTRAINT CHK02_LU_SERVICECATEGORY NOT NULL,
RETAILERID_PK VARCHAR(12) CONSTRAINT CHK01_LU_RETAILERID NOT NULL,
WHOLESALERID_PK VARCHAR(12) CONSTRAINT CHK01_LU_WHOLESALERID NOT NULL
);
--
-- set primary key
--
--
-- add table and field comments
COMMENT ON COLUMN LU_CROSSBORDER.STWPROPERTYNUMBER_PK IS 'Target NO_PROPERTY - NO_PROPERTY to which Crossborder Supply Point is related to'; 
COMMENT ON COLUMN LU_CROSSBORDER.CORESPID_PK IS 'CORESPID_PK if supplied by STW for CROSSBORDER';
COMMENT ON COLUMN LU_CROSSBORDER.SERVICECATEGORY IS 'Service Category (D2002) - this applies to i.e W or S. Add a row for each if required';
COMMENT ON COLUMN LU_CROSSBORDER.RETAILERID_PK IS 'Retailer ID who is responsible for this SPID';
COMMENT ON COLUMN LU_CROSSBORDER.SERVICECATEGORY IS 'Wholesaler ID who is responsible for this SPID';
--
--
-- Create LU_DATALOGGERS
CREATE TABLE LU_DATALOGGERS
(
MANUFACTURERSERIALNUM_PK VARCHAR(32)CONSTRAINT CHK01_LU_MANUFACTSN NOT NULL,
STWPROPERTYNUMBER_PK NUMBER(9) CONSTRAINT CHK05_LU_STWPROPERTYN NOT NULL,
STWMETERREF_PK NUMBER(32),
MANUFACTURER_PK VARCHAR(32),
DATALOGGERSERIALNUM VARCHAR(32),
DATALOGGERWHOLESALER NUMBER(1) CONSTRAINT CHK01_LU_WHOLESALER NOT NULL,
DATALOGGERNONWHOLESALER NUMBER(1) CONSTRAINT CHK01_LU_NONWHOLESALER NOT NULL
);

ALTER TABLE LU_DATALOGGERS ADD CONSTRAINT CHK02_LU_WHOLESALER CHECK (DATALOGGERWHOLESALER IN (0,1));
ALTER TABLE LU_DATALOGGERS ADD CONSTRAINT CHK02_LU_NONWHOLESALER CHECK (DATALOGGERNONWHOLESALER IN (0,1));
--
-- add table and field comments
COMMENT ON COLUMN LU_DATALOGGERS.MANUFACTURERSERIALNUM_PK IS 'TARGET NO_UTL_EQUIP (METER serial number) Use this and PROPERTY_NO';
COMMENT ON COLUMN LU_DATALOGGERS.STWPROPERTYNUMBER_PK IS 'Target PROPERTY_NO where meter is installed'; 
COMMENT ON COLUMN LU_DATALOGGERS.STWMETERREF_PK IS 'Optional Target NO_EQUIPMENT that this logger is attached to';
COMMENT ON COLUMN LU_DATALOGGERS.MANUFACTURER_PK IS 'Optional Meter manufacture'; 
COMMENT ON COLUMN LU_DATALOGGERS.DATALOGGERSERIALNUM IS 'Optional Datalogger serial number';
COMMENT ON COLUMN LU_DATALOGGERS.DATALOGGERWHOLESALER IS 'Is this a Wholesaler logger Y (1) or No (0)';
COMMENT ON COLUMN LU_DATALOGGERS.DATALOGGERNONWHOLESALER IS 'Is this a NON Wholesaler logger Y (1) or No (0)';
--
--
-- Create LU_CLOCKOVER
CREATE TABLE LU_CLOCKOVER
(
STWMETERREF_PK NUMBER(32) CONSTRAINT CHK01_LU_STWMETERREF NOT NULL,
METERREADDATE DATE  CONSTRAINT CHK01_LU_METERREADDATE NOT NULL,
METERREAD NUMBER(12) ,
ROLLOVERINDICATOR NUMBER(1)  CONSTRAINT CHK01_LU_ROLLOVERIND NOT NULL
);
--
-- set constraint key
ALTER TABLE LU_CLOCKOVER ADD CONSTRAINT CHK02_LU_ROLLOVERIND CHECK (ROLLOVERINDICATOR IN (0,1));
--
-- add table and field comments
COMMENT ON COLUMN LU_CLOCKOVER.STWMETERREF_PK IS 'Target NO_EQUIPMENT (Meterthat this reading was for'; 
COMMENT ON COLUMN LU_CLOCKOVER.METERREADDATE IS 'Target TS_CAPTURED (Meter read date), so that the correct reading can be flagged as clock over'; 
COMMENT ON COLUMN LU_CLOCKOVER.METERREAD IS 'Target AM_READING (METER Read value) at clockover used to check that the correct reading is flagged'; 
COMMENT ON COLUMN LU_CLOCKOVER.ROLLOVERINDICATOR IS 'Rollover Indicator~~~D3020 - Default to 1 (Y). Indicates the meter read has rolled over for this meter.';
--
-- Create LU_TRAIFF 
CREATE TABLE LU_TARIFF
  (
    TARIFFCODE_PK VARCHAR2(32 BYTE) NOT NULL ENABLE,
    TARIFFEFFECTIVEFROMDATE DATE NOT NULL ENABLE,
    TARIFF_EFFECTIVE_TO_DATE DATE,
    TARIFFNAME   VARCHAR2(250 BYTE) NOT NULL ENABLE,
    TARIFFSTATUS VARCHAR2(250 BYTE) NOT NULL ENABLE,
    TARIFFLEGACYEFFECTIVEFROMDATE DATE,
    TARIFFAUTHCODE       VARCHAR2(250 BYTE) NOT NULL ENABLE,
    SERVICECOMPONENTTYPE VARCHAR2(10 BYTE) NOT NULL ENABLE
  );
 --
-- set primary key
--
-- add table and field comments
--
-- Create LU_SERVICE_CATEGORY
 CREATE TABLE LU_SERVICE_CATEGORY
  (
    SUPPLY_POINT_CODE     VARCHAR2(2 BYTE),
    SUPPLY_POINT_DESC     VARCHAR2(32 BYTE),
    SERVICECOMPONENTDESC  VARCHAR2(32 BYTE),
    TARGET_SERV_PROV_CODE VARCHAR2(100 BYTE),
    SERVICECOMPONENTTYPE  VARCHAR2(10 BYTE)
  );
 --
-- set primary key
--
-- add table and field comments
--
-- Create LU_SERVICE_COMP_CHARGES  
CREATE TABLE LU_SERVICE_COMP_CHARGES
  (
    SERVICE_COMP_CD   VARCHAR2(5 BYTE),
    SERVICE_COMP_DESC VARCHAR2(40 BYTE),
    CHARGE_TYPE       VARCHAR2(10 BYTE),
    CHARGE_DESC       VARCHAR2(70 BYTE),
    STEP_TYPE         VARCHAR2(20 BYTE),
    STEP_DESC         VARCHAR2(30 BYTE),
    USAGE_UNITS       VARCHAR2(20 BYTE),
    CHARGE_UNITS      VARCHAR2(15 BYTE)
  );
 --
-- set primary key
--
-- add table and field comments
-- 
-- Create LU_TARIFF_SPECIAL_AGREEMENTS
CREATE TABLE LU_TARIFF_SPECIAL_AGREEMENTS
  (
    PROPERTY_NO              NUMBER,
    ACCOUNT_NO               NUMBER,
    CUSTOMER_NAME            VARCHAR2(200 BYTE),
    TARIFFCODE               VARCHAR2(32 BYTE),
    SERVICECOMPONENTTYPE     VARCHAR2(32 BYTE),
    SPECIAL_AGREEMENT_FLAG   CHAR(1 BYTE),
    SPECIAL_AGREEMENT_DESC   VARCHAR2(100 BYTE),
    OFWAT_REFERENCE_NUMBER   VARCHAR2(100 BYTE),
    STW_REFERENCE_NUMBER     VARCHAR2(100 BYTE),
    SPECIAL_AGREEMENT_FACTOR NUMBER
  );
  --
-- set primary key
--
-- add table and field comments
-- 

commit;
exit;



  
  
